### ISSUE TITLE
No example showing in syntax highlighting settings pane

### ISSUE THREAD

**Issue by Morgul** [vsch/idea-multimarkdown#1]
When attempting to set custom colors in the preference pane, there's no preview example:

<img width="1003" alt="screen shot 2015-08-20 at 9 44 08 am" src="https://cloud.githubusercontent.com/assets/770655/9386254/40a2e944-4720-11e5-95ef-d94fde98d3a4.png">

It would be nice to have that, like the other syntax highlighting preferences. :)

**Comment by Morgul** [comment]
Additionally, hitting 'Apply' doesn't seem to update any documents I have open behind the preferences modal, so I have to hit 'OK', see if I like the color I picked, and then re-open the preferences pane.

**Comment by vsch** [comment]
It is a bug.

Yes, I completely agree. It is a fix that I am planning to implement in the immediate future. If it is any consolation, I feel your pain. It took me forever to get the colors tweaked for the Default color scheme since I could not see the results until I closed the settings dialog. :(

The difficulty in adding the sample text is from the original markdown plugin that I forked. It uses Annotations to do syntax highlighting because it parses with pegdown. So it does not have a Lexer that IntelliJ expects and uses for syntax highlighting. The sample pane does not invoke the Annotator so adding a sample text will result in text that is not highlighted, which would not be any better.

Last night, I figured out how I can wrap pegdown so it will present Parser and Lexer interfaces, without major kludging. I had to do something close to it to get the highlighting working in Annotator. So there is a light at the end of that tunnel.

I thought I would need to re-implement pegdown in Grammar-Kit to be able to add all the IntelliJ goodies like error annotations, code navigation, folding, formatting, code completion, etc. Now I can do it much faster by wrapping it and get to a rewrite much later.

**Comment by Morgul** [comment]
That makes total sense. I'd previously been using the plugin you forked, and one of my biggest complaints was always the lack of imbedded syntax highlighting for html blocks. I had caught the issue that they said it would be a huge rewrite, so I'm super excited that you figured out a quick work around!

So, If I'm understanding correctly, this bug won't get fixed until you do the wrapping of pegdown? (Doesn't bother me; I finished changing my colors, and now probably won't mess with it again for months) At the same time, I should get (or be close to getting) some other features I've really wanted, so all in all, this is pretty exciting.

**Comment by vsch** [comment]
Part of the same Annotations problem. Hitting apply does not invoke Annotator until after the dialog is closed. 

I am planning the fix out by September 8th, or sooner if I can. It is stopping me from adding all the other stuff that I want, including injected languages, like HTML. Once you get used to IntelliJ creature comforts it is an irritant to work without them.

**Comment by vsch** [comment]
Fixed. Plugin available for download from the official site. I also fixed the TODO not being parsed. However, the todo's are limited to comments . Could not make it work for now anywhere else. Also fixed Scratch files not being accepted by the plugin.

<img width="886" alt="screen shot 2015-08-24 at 3 20 05 am" src="https://cloud.githubusercontent.com/assets/10299086/9434697/63ceaed4-4a0f-11e5-8a97-cf3bd537584d.png">

<img width="919" alt="screen shot 2015-08-24 at 3 21 28 am" src="https://cloud.githubusercontent.com/assets/10299086/9434698/69774c88-4a0f-11e5-9f3c-4841b2ad144b.png">
