### ISSUE TITLE
Align project with CommonMark

### ISSUE THREAD

**Issue by mikehaas763** [vsch/idea-multimarkdown#10]
CommonMark is a spec of Markdown created by many big names in the industry (Github, Jeff Atwood). I won't explain a lot of what it is as it can be read about here: http://commonmark.org/

I believe IntelliJ IDE's need a plugin that follows CommonMark and think this plugin would be a great option to base it off of. Particularly it could use the java implementation that already exists: https://github.com/atlassian/commonmark-java

I'd be willing to spend some time getting some initial prototypes working.

Thoughts?

**Comment by vsch** [comment]
Thank you for bringing the https://github.com/atlassian/commonmark-java project to my attention. I will investigate it for use as the parser. I spent some time searching for a Java implementation of a Markdown parser but for some reason did not notice this particular project. Too bad he current implementation is not quite ready to replace pegdown. I am even considering contributing to it to make it happen sooner. It all depends on how much effort that will take and how much time I have to devote to it.

I will definitely take you up on the offer to get it off the ground. Give me a couple of days to investigate its current state and estimate the effort in getting it up to pegdown level, so the switch will not be a step backwards.

I did look at the commonmark spec when I forked this plugin and walked away with mixed feelings because I think it will simply wind up being another Markdown extended specification in the real world whose features will need to be supported. If it is widely adopted it will take a very long time. No one is going to update all the existing sources from all the popular flavours of Markdown any time soon. It is a backwards compatibility issue that Microsoft had to wrestle with for years. No quick and easy way out. People tend to use whatever works not what is documented. So it makes it very difficult to make a break and not support old flavours.

Compatibility with any popular Markdown variety used by IntelliJ developers is a necessary evil. Otherwise, the plugin will support a good specification that everyone would love to use but cannot because they are producing documents for a platform that implements its own flavour of Markdown. Take GitHub as a good example.

I suspect that in the end the plugin will have to recognize many dialects, selectable through setting options.

**Comment by vsch** [comment]
@mikehaas763, after maintaining and extending pegdown for the last six months I have come to the inevitable conclusion that moving to commonmark based parser is a necessity. The benefit of a spec is very attractive but the speed and extensibility are my main drivers. 

The speed of the current parser is a huge stumbling block for me. It causes typing delays which I annoy me to no end. The commonmark-java version is 10-20 times faster which should allow for rich syntax highlighting without a penalty in typing response.

Markdown parsing is best implemented in a non-regular expression grammar for speed, ease of understanding, extending and maintaining the parser. pegdown suffers in all of these areas plus adds a few weaknesses of its own. Additionally, I have been practically the only contributor of bug fixes and enhancements to pegdown, which is not a good sign for the long term evolution of that project.

I will complete a one or two more basic features that I consider must have for the plugin like auto-formatting and probably some live template support. After which I will move the implementation to the atlassian/commonmark-java version. I will have to add GFM extensions and other enhancements that I implemented in pegdown so that the commonmark based plugin is fully backwards compatible with the current version.

Thank you again for bringing that option to my attention.

**Comment by vsch** [comment]
@mikehaas763, there is a new profile option in parser settings "CommonMark" that configures parser for CommonMark. 

Fixed in EAP update channel or download and install plugin from disk: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.1.0.4.zip

**Comment by vsch** [comment]
Full support for formatting, list indent/un-indent based on list processing setting added in next release.
