### ISSUE TITLE
Getting IllegalArgumentException: parent must be showing Error Loading .md File

### ISSUE THREAD

**Issue by mikeschinkel** [vsch/idea-multimarkdown#122]
Just installed 1.3.2 and loaded a simple .MD file and got this logged error:

IllegalArgumentException: parent must be showing: javax.swing.JPanel[,0,0,0x0,invalid,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=]

I also was not able to find any menu options but I did find MultiMarkdown in the Keymap and set some keys both the keys don't trigger a preview, for example.

I am extremely interested buying in your product if you can get it to work.  See my prior blog:

http://mikeschinkel.com/blog/the-world-needs-a-markdown-ide-for-programmer-docs/

**Comment by vsch** [comment]
@mikeschinkel, thank you for your interest. There is a newer version that fixes Java 1.6 and 1.7 compatibility and a few other bugs reported since the release.  You will need to download it and install plugin from disk in Preferences > Plugins. <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.2.1.zip>

All the configuration is in Preferences > Languages & Frameworks > MultiMarkdown. The rest is in KeyMap and Editor > Fonts & Colors > MultiMarkdown.

If you still have issues please let me know of your system details, mainly:

1. JetBrains Product and version
2. Boot JDK
3. OS you are using.

The first two you can just send me screenshot of the about box for the product.

All these affect the plugin operation and I am resolving compatibility issues as I become aware of them. With a dozen products, half dozen active versions of each product, 3 major OS types, and a half dozen Java JDK versions, it is very hard to get it perfect, especially when the product is in very active development. 

As it is I am testing a few JB products, here is a section of my dock of JB products <img width="394" alt="screen shot 2016-01-01 at 12 02 21 am" src="https://cloud.githubusercontent.com/assets/10299086/12069796/fdfcfd0a-b01a-11e5-90fe-a8cb72e4f0ce.png"> that I use for sanity testing a release, with JDK 1.6, 1.8 JetBrains Bundled, 1.8u51 Oracle, 1.8u66 Oracle. It takes a few hours just for sanity tests.

I am currently finishing up the next release which will have language injections for code fence, verbatim blocks and html blocks, completion, annotation and refactoring for all link elements and anchor references, for footnotes and reference links and reference images.

I am using the latest version and don't know how I managed to work with markdown without these. I quickly read through your last blog and I agree. This is what motivated me to dive into this plugin. I felt markdown needs to be supported in JetBrains IDEs like the rest of the languages otherwise keeping the documentation updated and all links valid is a nightmare.

Let me know if you want to try the latest unreleased version and I will get you an installation zip. I will also go through your last blog with a fine comb for my todo list. ;)

**Comment by mikeschinkel** [comment]
Thanks for the support! 

At first blush it seems to work.  

But it took me a while to figure out I needed to first get a trial license to see the preview. I thought it was just not working.  Maybe you should have your preview buttons pop up a notice so it will be obvious?

BTW, first this I notice that is not working is this is not translated:

    [dotfiles hooray!](dotfiles hooray!)

I'll add new tickets for any feedback or other bugs or feature requests that come up.

I am very excited to start using it, will be buying a license to support your efforts, and [just tweeted about it](https://twitter.com/mikeschinkel/status/683828624701657089) _(I have a few more followers than the average, mostly WordPress people)._

> Let me know if you want to try the latest unreleased version and I will get you an installation zip. I will also go through your last blog with a fine comb for my todo list. ;)

I will be honored, but more I will be appreciative if you do! :-)

**Comment by vsch** [comment]
I am surprised that the preview was not working on your system without a trial license. The unlicensed version has a preview tab, like the open source version.

Before you buy a license contact me by e-mail vladimir@vladsch.com . I'll send you a complimentary license. 

I would like you to try out the latest version that I am preparing for release. It has much more than the last release, including code injections into: verbatim, code fence blocks, html blocks and multi-line image URLs to support gravizo.com UML diagram embedding.

I was going to release it today but spent the day resolving parser bugs in the pegdown library. So the release will be tomorrow. It is worth a try. I made some animated gifs for users that wanted the UML features. You can see them in #103 or when I get your e-mail, I'll send you a link to the live version.

**Comment by mikeschinkel** [comment]
> Before you buy a license contact me by e-mail vladimir@vladsch.com . I'll send you a complimentary license.

That is nice, but I'm happy to support you. It's not expensive to me.

> I would like you to try out the latest version that I am preparing for release. It has much more than the last release, including code injections into: verbatim, code fence blocks, html blocks and multi-line image URLs to support gravizo.com UML diagram embedding.

Nice.  However at the moment I am trying to stabilize my system so I can get ready for the rush of client work early in the new year.  How about I as to try it when I come across a limitation I need that it will address?

**Comment by vsch** [comment]
Fair enough. IntelliJ IDE will prompt you for the update when it is released in a day or so.
