### ISSUE TITLE
language name completion

### ISSUE THREAD

**Issue by linux-china** [vsch/idea-multimarkdown#128]
Now language injection for  verbatim blocks is done.  Could you implement language name completion after ``` ?

**Comment by vsch** [comment]
@linux-china, The language completions are there except the code fence has to be a valid Markdown code fence so that it is recognized as such by the parser. The `|` below marks the cursor where completion of language will happen.

    ```|
    anything but blank lines
    ```

It is a bit awkward but until I implement contextual live templates that will insert a code fence for you and put the cursor in place for language completions, it is the only way to have it working.
