### ISSUE TITLE
Contrast with other markdown plugins

### ISSUE THREAD

**Issue by binkley** [vsch/idea-multimarkdown#13]
Would you update your README.md to include a contrast with the gfm plugin (https://github.com/shyykoserhiy/gfm-plugin) and JetBrains' "Markdown support" plugin (https://plugins.jetbrains.com/plugin/7793?pr=idea)?

On the surface your solution looks much lighter than gfm (gfm downloads a Chromium lib for your platform).

Thanks!

**Comment by vsch** [comment]
@binkley, at first I tried to understand what you meant by "contrast with" and "looks much lighter". I wasn't sure if it was a critique or a veiled compliment. :) 

Do you mean that it looks like it does a lot less because it is much smaller? And you wish there was something in the readme so that you did not spend so much time evaluating/using others before trying MultiMarkdown? If my understanding is right, then I thank you for the compliment.

In the end people will make up their minds through experience. I also can't think of how to phrase it so it does not come off as desperate, self-serving hype. What would I say in the readme: "The others are just BIGGER not BETTER"? 

**If you can suggest the wording then I would be grateful**. Marketing is not my forté.

As for me, I am very satisfied with the reception of the plugin. The feedback is great and the popularity is growing organically. It will probably hit 50,000 downloads after a month of being released.

Maybe if more people went to the Comment and Rate page for the plugin and rated it, the extra ratings might help others make up their mind. I think this too will take care of itself with time.

Thank you for the motivating feedback. :+1:

**Comment by Morgul** [comment]
@vsch You can probably manage this by simply making a table of features. You hardly have to comment beyond that, just keep it as fair as you can.

**Comment by vsch** [comment]
My concern is once I add the table then I will have to maintain its accuracy both for new features that i add and features added into the other products. Otherwise it will be outdated. To be honest, I am overloaded as is with all the changes I still have to implement. I will keep this issue open for later consideration.

**Comment by Morgul** [comment]
@vsch That's a very fair point. Probably best to consider once this stabilizes.

**Comment by vsch** [comment]
I can't wait for that. I was hoping to be there already. I look forward to a break considering I really did not expect to be putting in that much effort into it. It is a perfect example of "Fools rush in where angels fear to tread." :)

**Comment by binkley** [comment]
Hi @vsch, I was looking for motivation to switch from gfm.  It's fat but does the job.  However, your plugin looks rather nice, and I want to give it a go.  Cheers!

**Comment by dmolesUC3** [comment]
[Gfm](https://github.com/ShyykoSerhiy/gfm-plugin) is big because it embeds Chromium [via JXBrowser](https://www.teamdev.com/jxbrowser) to provide a faithful GitHub-flavored preview. As far as I can tell (@binkley, maybe you can tell me different?) it doesn't have any editor support of its own, but it works great alongside idea-multimarkdown or the JetBrains plugin, by adding an extra "Gfm Preview" tab.

**Comment by ShyykoSerhiy** [comment]
The author of [Gfm](https://github.com/ShyykoSerhiy/gfm-plugin) is here.:)
It's true, that [Gfm](https://github.com/ShyykoSerhiy/gfm-plugin) doesn't have any editor support of its own. It doesn't add any file associations for markdown files in order to avoid clashes with other plugins. It does what it says it does: only provides a way to view markdown preview via offline or online (Github service) mechanisms. 

As for big size - yeah it's huge. Initially I've considered  using JavaFX or https://github.com/oswetto/Loboevolution or JXBrowser as webView. Ended up with supporting all of them. The reason for using JXBrowser is simple - jre6 support. The reason for using Loboevolution - pure java === arm support(works on Raspberry Pi 2 for example). The reason for using (and supporting) JavaFX - hope that somewhere in the future everybody will run JetBrains products with jre8+. 

Anyway, [idea-multimarkdown](https://github.com/vsch/idea-multimarkdown/) looks like neat project to me :+1: . In fact I've switched from idea-markdown to idea-multimarkdown by myself. But I use gfm-plugin too because WebStorm 11 EAP on OS X uses embedded jre8 from JetBrains without support for JavaFX WebView.

**Comment by vsch** [comment]
@ShyykoSerhiy, nice to hear you switched from idea-markdown. BTW, I used your plugin as a reference when I was trying to get WebView working. It's in the credits in NOTICE too. I think you did a great job.

I agree that your decision not to have an editor was the right one. The way you have it implemented it can be used along any implementation of another editor/preview and anyone who wants authentic GFM preview should use your plugin along with any other markdown plugin they want. It works great.

I can add an option not to display the Preview tab in my plugin so that someone who wants the editor but with Gfm plugin's preview can avoid having an unused tab. No one asked for it but then most feedback happens when I mess up and break a few too many things. :)

I looked at JXBrowser but I'm too old school and could not justify having a 1/4 GB distribution. However, it would make compatibility with all versions a LOT easier.

I don't know if your complementary JXBrowser license allows it but if it does, you could add to your plugin a tool window to open browsing windows using JXBrowser in the IDE. It would eliminate having to switch apps for access to project pages that don't need debugging but do need to be accessed frequently. If you could also provide a Service to open URL's then I can modify my plugin to see if yours is installed and direct external URLs from my preview to your tool window, instead of the desktop browser. I think it would be an awesome feature which would expand your user base. Not everyone wants or needs exact GitHub preview or even markdown but most need to browse and JXBrowser is the best option for that.

I would offer to make the mod and PR but right now I'm busier than a one legged man at an ass kicking contest, so it would take a while. But if you are looking to add nifty features to your plugin... you have my vote :+1:

**Comment by vsch** [comment]
@binkley, I think I will have some time to put together a comparison between Markdown plugins. With the latest version there are enough differences to warrant a table.
