### ISSUE TITLE
idea-multimarkdown and math equations

### ISSUE THREAD

**Issue by JimStearns206** [vsch/idea-multimarkdown#132]
Does idea-multimarkdown or compatible plug-in support math symbols, as in ${e}^{i\pi }+1=0$ ?

**Comment by vsch** [comment]
@JimStearns206, to have the equation in the text you need to embed it as an multi-line URL to some LaTex on line processor. <http://www.codecogs.com/latex/eqneditor.php> will handle creating images and producing encoded URLs.

Here is an example: 

Markdown source:

```markdown
You can include text before ![LaTex Embedded Image](http://latex.codecogs.com/gif.latex?
\begin{align*}
x^2 + y^2 &= 1 \\
y &= \sqrt{1 - x^2}
\end{align*}
)
and after the the image but the after has to come on its own line, the closing `)` 
has to be the only non-blank on its line so that the URL content is not constrained. 
If you need to include a single `)` inside the content, just indent it by an extra 4 
spaces and it will be ignored as a terminating `)` of URL content.  
```

Multi-line URL image tags were added specifically to handle online URL to image processing services, initially the request came in for UML diagrams.

You don't get much control over alignment but it is a quick and cheap solution that displays math equations.

Also requires support of the markdown processor that used in the rendering of the final document. GitHub will handle multi-line URLs for gravizo.com UML diagrams but not LaTex. At least not this one.

Rendering in idea-multimarkdown:

<img width="616" alt="screen shot 2016-01-06 at 4 03 22 pm" src="https://cloud.githubusercontent.com/assets/10299086/12154854/f43ab55e-b48f-11e5-8d95-2f657fc8ba5a.png">

Rendering on GitHub:

<img width="616" alt="screen shot 2016-01-06 at 4 10 54 pm" src="https://cloud.githubusercontent.com/assets/10299086/12154871/1bbe6170-b490-11e5-85b1-ab012dc9cee6.png">

The other option is to use the single line image link with a url encoded: `
<img src="<img src="http://latex.codecogs.com/gif.latex?%5Cbegin%7Balign*%7D%20x%5E2%20&plus;%20y%5E2%20%26%3D%201%20%5C%5C%20y%20%26%3D%20%5Csqrt%7B1%20-%20x%5E2%7D%20%5Cend%7Balign*%7D">`

will render as: <img src="http://latex.codecogs.com/gif.latex?%5Cbegin%7Balign*%7D%20x%5E2%20&plus;%20y%5E2%20%26%3D%201%20%5C%5C%20y%20%26%3D%20%5Csqrt%7B1%20-%20x%5E2%7D%20%5Cend%7Balign*%7D"> in idea-multimarkdown preview and should be handled correctly by most markdown processors.
 
I could add a quick-fix into idea-multimarkdown that will let you convert between the multi-line and single line URL encoded formats so that you can edit and preview the results in comfort and then convert to the image tag that will be processed correctly by any markdown processor.

When you need to edit and change it, you use the quick fix to make it a multi-line URL and when you are done convert it back for portability.

**Comment by JimStearns206** [comment]
@vsch, thanks for the prompt and helpful reply, complete with examples. They work. A future release with syntactic sugar to hide the machinery would be great, but the current methods you describe do what I need now. Thanks again!

**Comment by vsch** [comment]
@JimStearns206, you are welcome. 

I will add the intention action to go from URL encoded image tag to multi-line URL and vice-versa to my To Do list.

**Comment by fathersson** [comment]
@vsch doesn't work for me =(
What am I doing wrong? 
Intellij Idea version = 15.0.2 Community Edition,
MMD version = 1.4.4
OS = Mac OS.

<img width="1011" alt="screen shot 2016-02-19 at 18 53 04" src="https://cloud.githubusercontent.com/assets/3673110/13180570/13ac809e-d73a-11e5-87cf-c31d648694ab.png">

**Comment by vsch** [comment]
@fathersson, can you please paste the markdown content you are using so I can try it out and see why it is not working. 

Please indent the text so it is treated as code or wrap the pasted text in:

    ```markdown

    ```

So it is not processed by GitHub

**Comment by vsch** [comment]
@fathersson, just realized you are not using idea-multimarkdown but Markdown Support plugin. You can have both installed but if 'Markdown Support' is enabled it will be used instead of idea-multimarkdown. You need to disable 'Markdown Support' in IDEA preferences (OS X)/settings (Windows/Linux) under plugins.

Here is what it looks like in idea-multimarkdown:

<img width="841" alt="screen shot 2016-02-19 at 11 05 36 am" src="https://cloud.githubusercontent.com/assets/10299086/13180973/be031cb6-d6f8-11e5-80c9-658a29835e60.png">

**Comment by fathersson** [comment]
@vsch man, you're genius! I have no idea how did you figure that out, but you're totally right!

I've tried several Idea plugins - thus I have three installed - Markdown, Markdown support and yours - the best - Multimarkdown. My understanding was that "Markdown support" is a must in order to support markdown in Intellij Idea. So I have turned on two - "... support" and MMD. 
Haven't though that's an additional plugin. As soon as I turned that off - everything works.

Thanks a lot! =)

**Comment by vsch** [comment]
@fathersson, you are welcome and thank you for the compliment. If I was a genius I would have noticed it right away, instead of after trying the sample. The toolbar over the markdown editor is different and the preview for Markdown Support does not have the  GitHub like document title and frame.

BTW, You don't need Markdown Support unless you want to use it as your Markdown plugin.

**Comment by vsch** [comment]
@JimStearns206, latest EAP 2.3.0.16 has intention actions to convert markdown to HTML for image links and vice-versa. Specifically, multi-line URL image links, tables and definitions are supported. So you can convert to Markdown multi-line URL, edit and validate then when you are done use the Markdown To HTML intention to covert it to URL encoded image tag that should work with all markdown parsers.

To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by Nanologisk** [comment]
I have installed Markdown Navigator Enhanced and disabled Markdown Bundled. However, the math equations do not work for me:

![image](https://user-images.githubusercontent.com/57987646/94994873-bc77c380-059a-11eb-89ea-fa29fbde204e.png)

Can you please help me? Thanks!
