### ISSUE TITLE
Out of memory errors

### ISSUE THREAD

**Issue by breandan** [vsch/idea-multimarkdown#149]
Started receiving lots of "Unable to Serialize" and "Out of Memory" errors recently (I believe after updating to 1.4+). Here is a [recent log](https://gist.github.com/breandan/103a66e2f79312646b09) containing some of these errors as of 1.4.2.

edit: Running IC-143.1184. After restarting, IDE was disabled.

**Comment by vsch** [comment]
@breandan, I looket at the log and there are some assertion errors in markdown parser. I am taking a look at the code now.

**Comment by vsch** [comment]
@breandan, I did find a bug in the parser. Mainly I assumed a condition that cannot happen but did an assertion to make sure. This can only happen under an illegal states which I have not been able to duplicate. I removed the assert and did a rollback to the starting marker, which I should have done in the first place. 

I don't know if the low memory condition caused the parser error and then the assertion in the middle of the parse made the condition worse or if something else caused the parser error and this led to the out of memory.

This pegdown parser that is used for markdown parsing is not the ideal choice for a parser to use in IntelliJ plugin for Psi building. I have to hand roll a PsiBuilder compatible parser and lexer from its AST which was only good originally for serializing to HTML. It is a pain to maintain and enhance. 

All that aside, there is a bug in the parser that will abort parsing, but pegdown has done this before through its timeout exceptions without bringing down the whole IDE. But I suspect if this happens during index building, as it does on restart, then the result could be anything. I had the IDE hang more than once, just because I resized its window during startup. I stopped doing that. Now I patiently wait for it to initialize before playing with its window size. So a parser assertion exception during rebuilding of indexes could be an issue.

I am running the original version on Windows 10 with IDEA CE 15.02, same version as you have. Trying to make crash. I don't think it is OS related, more likely file content related. The last operation you performed was EditorBackspace. So there was a text change that could have caused the parser to throw an assertion. Then on restarting, the same text is also re-parsed, causing the same problem, but now during startup.

I have the assertion removed and can make a build with that fix if you want to try it. I am running it on Windows IDEA but that does not help since I don't have your file content to try it on.

**Comment by vsch** [comment]
@breandan, fixed in <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.2.1.zip>

Tested on 
- Mac OS:
    - IDEA: CE 14.0 JDK 1.6, CE 14.1 JDK 1.8u51, CE 15.02, IU 15.02 Bundled JDK, IU 16 144.2925 Bundled, 
    - WS 10.0.4 Bundled, WS 12 EAP 144.2608.3  EAP Bundled
    - PC 5.0.3 Bundled
    - PS 10.0.3 Bundled

- Windows 10
     - IDEA CE 15.0.2
     - IDEA IU 15.0.2

Some setups are licensed, some not. No luck in getting it to crash.

Parser will not assert but you will be the final judge since I was not able to make it crash. If you ever have a markdown file that causes exceptions please keep me in mind. I collect these for the sanity tests.

**Comment by breandan** [comment]
Awesome, thanks for investigating.

**Comment by vsch** [comment]
@breandan thank you for reporting it. I should offer a bounty for supplying information that leads to successful elimination of crashes. ;)
