### ISSUE TITLE
could it support markdown  flow&sequence diagram syntax？

### ISSUE THREAD

**Issue by leion8310** [vsch/idea-multimarkdown#173]
as like follow syntax
    `sequence
    张三->李四: 嘿，小四儿, 写博客了没?
    Note right of 李四: 李四愣了一下，说：
    李四-->张三: 忙得吐血，哪有时间写。
`

``````
```flow
st=>start: 开始
e=>end: 结束
op=>operation: 我的操作
cond=>condition: 确认？

st->op->cond
cond(yes)->e
cond(no)->op
```
``````

**Comment by vsch** [comment]
The syntax highlighting of code fenced blocks is done by the IDE and will support only languages that are defined in the IDE. 

If you have a plugin that supports `flow` syntax installed then it will be supported. The plugin implements the IDE injected language API and the rest is up to the IDE.

**Comment by vsch** [comment]
@leion8310, if there is a web service that can convert the syntax to an image then you can use the multi-line image url similar to UML diagrams. See #103

**Comment by vsch** [comment]
@leion8310, I tried to figure out what diagram corresponds to the flow syntax you have given and convert it to start UML syntax.

Is the following diagram close?

<img src="http://g.gravizo.com/g?%0A%40startuml%3B%20%28*%29%20--%3E%20%5B%22%E5%BC%80%E5%A7%8B%22%5D%20if%20%22%E7%A1%AE%E8%AE%A4%EF%BC%9F%22%20then%3B%20--%3E%5B%E7%BB%93%E6%9D%9F%5D%20%28*%29%3B%20else%3B%20-%3E%5Bno%5D%20%22%E6%88%91%E7%9A%84%E6%93%8D%E4%BD%9C%22%3B%20%40enduml" alt="gravizo" />

The markdown version is:

```markdown
![graviso](http://g.gravizo.com/g?
@startuml;
(*) --> ["开始"] if "确认？" then;
  -->[结束](*);
else;  
->[no] "我的操作";

@enduml 
)
```

For github you will need to copy the generated HTML since it does not handle multi-line gravizo image URLs

```html
<img src="http://g.gravizo.com/g?%0A%40startuml%3B%20%28*%29%20--%3E%20%5B%22%E5%BC%80%E5%A7%8B%22%5D%20if%20%22%E7%A1%AE%E8%AE%A4%EF%BC%9F%22%20then%3B%20--%3E%5B%E7%BB%93%E6%9D%9F%5D%20%28*%29%3B%20else%3B%20-%3E%5Bno%5D%20%22%E6%88%91%E7%9A%84%E6%93%8D%E4%BD%9C%22%3B%20%40enduml" alt="gravizo" />
```
