### ISSUE TITLE
Fenced code blocks are unreadable in some dark color schemes

### ISSUE THREAD

**Issue by nazrhyn** [vsch/idea-multimarkdown#177]
In almost all of the dark code color schemes that ship with WebStorm, fenced code blocks are pretty unreadable. This is in the Twilight scheme:

![multimarkdownfenced](https://cloud.githubusercontent.com/assets/1672405/13880117/304edbbc-ecf1-11e5-8e0a-b55b5a356c79.gif)

Of the dark schemes, only in Darkula are they actually readable.

![image](https://cloud.githubusercontent.com/assets/1672405/13880065/eb7ddd4e-ecf0-11e5-9503-0e5c9290d629.png)

**Comment by vsch** [comment]
@nazrhyn, the plugin comes with colour schemes for `default` and `darcula`. Other schemes have to be customized.

I'll see if I can figure out why for Twilight the code fence appears to have background taken from a light scheme while the text is taken from a dark scheme.

Could also be a problem of default element mapping.

In the mean time you should customize the scheme under Editor > Colors & Fonts > MultiMarkdown

**Comment by vsch** [comment]
@nazrhyn, the problem is that Twilight scheme is defined as derived from `Default` but it is a dark scheme and should be defined as derived from `Darcula`.

The fix is simple. Select Twilight scheme and <kbd>Save As...<kbd> another scheme name. I used default value of `Twilight copy`

In settings directory under `colors` you will see a file with the new scheme name and `.icls` extension.

Open the file and change the first line from:

    <scheme name="Twilight copy" version="142" parent_scheme="Default">

to: 

    <scheme name="Twilight copy" version="142" parent_scheme="Darcula">

This will make the IDE pick the correct plugin custom color scheme from which to take default element colors. As you can see below the original scheme takes many of its element colors from the light scheme instead of the dark scheme.

Original Twilight:

<img width="922" alt="screen shot 2016-03-21 at 6 21 48 pm" src="https://cloud.githubusercontent.com/assets/10299086/13936114/cec1995e-ef91-11e5-95da-7c71350499ba.png">

Fixed copy of Twilight:

<img width="921" alt="screen shot 2016-03-21 at 6 22 23 pm" src="https://cloud.githubusercontent.com/assets/10299086/13936127/e1e735c0-ef91-11e5-8e78-685ff431a8a5.png">

**Comment by nazrhyn** [comment]
Awesome, thanks for checking that out. I'll give that a try!

**Comment by magneticflux-** [comment]
Unfortunately, changing the parent scheme breaks my "Monokai Sublime Text 3" scheme for other languages' colors. Are the default Darcula colors for Markdown Navigator available to paste into my  `.icls` file manually?

**Comment by vsch** [comment]
@magneticflux-, I added the current default colors. You can get the Darcula version https://github.com/vsch/idea-multimarkdown/blob/master/resources/com/vladsch/idea/multimarkdown/colorSchemes/MarkdownDarcula.xml
