### ISSUE TITLE
Smooth scroll issues with preview

### ISSUE THREAD

**Issue by yunti** [vsch/idea-multimarkdown#184]
I initially thought the rendering of the markdown preview was very slow, and fairly unusable, but it appears that it's the scrolling that is the issue.  When scrolling with a trackpad (on osx) the preview is very sticky and painful to use (the editor tab for the raw markup meanwhile is fine).

**Comment by vsch** [comment]
@yunti , I will try it. I have a trackpad that I don't use to see if there is something about it that messes up scrolling.

**Comment by vsch** [comment]
@yunti, the only thing I was able to find that occurs during scrolling is a callback from JavaScript to Java with the scroll position which is used to restore it after an update of the HTML content.

I added a timeout of 250ms so that this update occurs once scrolling is complete, after the delay. This reduces the number of callbacks to 1 most of the time. On my system the scrolling was already acceptable and with the fix seems to improve but it is hard to judge.

Can you please download and install plugin from disk: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.7.10.zip> and let me know if there is any improvement on your system with this fix.

**Comment by yunti** [comment]
Sorry for the delay in coming back to you.  I was wondering if the recent upgrade to the new rendering engine would fix the smooth scrolling , but alas the issue is still there and in use it's very janky compared to the normal very smooth intellij editor.   Is the above still relevant as a fix or is this now redundant? Thanks.

**Comment by vsch** [comment]
@yunti, the scrolling or smooth scrolling of the preview pane is not under direct plugin control. It is something handled by JavaFX and WebView.

Does the smooth scrolling issue go away in Markdown Support from JetBrains?

The two plugins are similar in the basic implementation of JavaFX based preview but since it is from JetBrains it is a good base case for comparison. If the scrolling issue is in both plugins it would point to a JavaFX issue and possibly native libraries and/or hardware related.

If it is only in Markdown Navigator then I will have to trace the code to see if there is something else that is triggered on scrolling that I can't see right now.

**Comment by vsch** [comment]
@yunti, you would not believe what was causing the issue. I have tired to figure this and typing delay out on half a dozen attempts. Gave up every time after killing 4 to 6 hours without success.

Today I decided enough is enough. I have to make it work. Finally after 5 hours on a hunch I disabled wrapping content in a div used to create the GitHub page wrapper and voila both problems solved.

The EAP releases have an option in HMTL Generation "Add page header", if you disable it then scrolling is smooth as butter, typing response is great with preview showing and "Print Preview" becomes lightening fast. 

Sorry it took so long to figure it out although it was not for lack of trying. I was suspecting my code instead of suspecting something in the browser implementation. 

![screenshot_html_pageheader](https://cloud.githubusercontent.com/assets/10299086/20634682/5b26f4e0-b321-11e6-8e21-9278ecb8bd58.png)

**Comment by vsch** [comment]
@yunti, the issue was even simpler to solve. It was caused by border radius. If it is not 0 then rendering is slow. Needless to say, I will have all border radii removed in the upcoming release. 

All you need to do in your version is add the following to custom CSS text:

```css
    #readme .markdown-body {
      border-radius: 0;
    }
```

<img width="1020" alt="screen shot 2016-11-25 at 5 09 42 pm" src="https://cloud.githubusercontent.com/assets/10299086/20635912/326009aa-b332-11e6-8054-4a714bc1d79e.png">

**Comment by yunti** [comment]
That is brilliant news well done! Thank you for taking the time to sort it out.  I apologise for not giving you better prompt feedback - I had held off properly adopting your plugin because of this bug made the user experience not great so I just stuck with current alternatives.  Really looking forward to ditching those and giving this a proper test later today.  

Thanks

**Comment by vsch** [comment]
@yunti, please let me know how it works out. I am curious because on my system it was the typing that was affected by this more than scrolling.

However, I am completely reworking the handling of web view requests which should make page updates and typing even more responsive. I will let you know when it is ready if you want to give it a try and let me know how it works on your system.

**Comment by vsch** [comment]
@yunti, preview version is available from the EAP update channel in plugin setup or from GitHub: https://github.com/vsch/idea-multimarkdown/blob/master/dist/idea-multimarkdown.2.1.1.42.zip let me know what you think of the scrolling. I love typing response. The lag has bothered me from the beginning.

**Comment by yunti** [comment]
Just did a quick test by changing the CSS stylesheet.  It's a lot better - not as smooth as the normal editor, but definitely a lots better. Thanks!

**Comment by vsch** [comment]
@yunti, get the EAP version. It has lot of bugs fixed and the preview is an order of magnitude faster than the release. Use the EAP update channel to get the latest or download https://github.com/vsch/idea-multimarkdown/blob/master/dist/idea-multimarkdown.2.1.1.48.zip which is the latest at the time of this comment.

**Comment by yunti** [comment]
Thanks will do - can't seem to find how to install via a download again....

hmmm I got a
`Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled.  Please re...`
error.

I unticked the old plugin, clicked on `install plugin from disk` choose lib-> idea-multimarkdown.jar

**Comment by vsch** [comment]
@yunti, not a problem,

1. download to your machine.
2. Go to plugins in settings (preferences on Mac)
3. Press the "Install plugin from disk..."
4. Select the file you downloaded and press ENTER
5. Restart the IDE

![downloadandinstallfromdisk](https://cloud.githubusercontent.com/assets/10299086/20715474/543a5e20-b61d-11e6-9bc9-d2c5d4c56830.png)

**Comment by yunti** [comment]
thanks.  I'm still getting the initialisation errors, when trying to 'install plugin from disk`
<img width="716" alt="screen shot 2016-11-29 at 15 36 16" src="https://cloud.githubusercontent.com/assets/1826271/20716287/99110e6e-b649-11e6-8b1e-0ae2af160737.png">
.  Note when I download the file, macOS seems to unzip it automatically so I picked `lib-> idea-multimarkdown.jar` file to load the plugin.


  However that didn't work.  Zipping the contents back up again gave me a failed to load plugin descriptor error.

<img width="393" alt="screen shot 2016-11-29 at 15 34 17" src="https://cloud.githubusercontent.com/assets/1826271/20716214/673a72d6-b649-11e6-9dd1-3239ddc9a7f7.png">

**Comment by vsch** [comment]
@yunti, you cannot unzip the file. You have to install the downloaded zip. It contains all the dependency libraries. The jar does not.

When you download the zip file, don't click on it in the browser which extracts it. No need to download it again, it should still be on the disk. Just select the zip when you install plugin from disk.

If it is no longer on the disk then download it again but don't click on the downloaded file in the browser.

**Comment by yunti** [comment]
Thanks thought you couldn't unzip.  Safari did something strange and automatically extracted it. Downloaded with chrome and that worked fine.

Works very well now. Thanks for the changes. 

(ps love the new click on preview and it goes purple and sync to the editor - great feature)

**Comment by vsch** [comment]
@yunti, told you it has improved tremendously over the last release. 

I can now state that it is not only the most feature full Markdown plugin for IntelliJ IDEs, it is also the fastest. The parser is faster than Markdown Support and now the preview is as fast.

On large file I use for testing (12,000 lines and 500k size) Markdown Support becomes unusable for editing, Markdown Navigator only has a small delay in typing response.

**Comment by yunti** [comment]
@vsch , very very impressed. It's very speedy well done.  Completely changes how I can use it now.

**Comment by vsch** [comment]
@yunti, thank you. I have had a beaming smile 😀 on my face ever since I found the problem and rewrote the JavaFX WebView integration.
