### ISSUE TITLE
Support front matter in Jekyll markdown pages

### ISSUE THREAD

**Issue by markwoon** [vsch/idea-multimarkdown#189]
I know this is a stretch, but it would be nice if MMD could support Jekyll's front matter in markdown pages.  And by "support", I'd be happy if it was just ignored.

**Comment by vsch** [comment]
@markwoon, do you have a good source for the syntax for Jekyll's front matter? If you can point me in a good direction I will see about adding it to pegdown for processing/ignoring.

**Comment by markwoon** [comment]
See https://jekyllrb.com/docs/frontmatter/

It's basically a YAML block.

If you want to keep it simple, you could let us mark a file or directory as a Jekyll markdown file to enable the support.  That way you don't have to autodetect/guess when to ignore that block.

**Comment by vsch** [comment]
@markwoon, thanks. BTW, see #61 for soft-wraps in plugin settings.

**Comment by vsch** [comment]
@markwoon, is having handling of front matter where from `---` on the first line to the next line that contains `---` sufficient?

I would probably handle it outside of pegdown since `---` can be a markdown horizontal rule and adding more parsing rules to pegdown would make an already fragile parser more fragile.

However, if it is as simple as text starting with `---` and contains another `---` would be treated as front matter, if the option is enabled, then I can filter it out from the pegdown stream.

**Comment by markwoon** [comment]
>  Is having handling of front matter where from --- on the first line to the next line that contains --- sufficient?

Yes, I believe so.

I don't have any projects that contain both normal .md files and Jekyll .md files, so having a project-wide option would work.

**Comment by vsch** [comment]
Even if you have a mix, it is rare for markdown to start with a horizontal line. In which case you can always add a blank line before or use `***` for the horizontal rule. For that reason I might as well add it as a parser option to make life simpler. Non jekyl projects will not have a problem with it.

However, I would add it as a YAML block and automatically handle it as injected YAML. That way you get the IDE YAML creature comforts to go with it.

**Comment by vsch** [comment]
@markwoon, I got the Jekyll front matter early build done.

Jekyll front matter:
1. must start at beginning of the file, no leading spaces and the markers `---` must be on a line by themselves followed by nothing but optional whitespace characters. 
2. The terminating `---` must also have only optional whitespace characters after the marker and before the end of line. 
3. A blank line must follow the closing `---` marker line.

A bit more strict that Jekyll but I don't think it will cause issues.

You have to enable Jekyll front matter parsing option in **Languages & Frameworks > MultiMarkdown > Parser**. It is disabled by default.

The front matter content is automatically treated as injected YAML if the language syntax is enabled in plugins.

I tested it with some samples but it may have a bug or two. Let me know what you think: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.8.3.zip>

**Comment by markwoon** [comment]
That's working well for me.  Thanks for the quick turnaround!

**Comment by neoaddix** [comment]
Hi just some additional thoughts on Jekyll 'support'. Please have look at the example code below. It includes some yaml frontmatter at the beginning and 2 references.

The references to page 1 and 2 can be easily refactored thanks your plugin! But when I would like to rename the index file to start.md the permalink will not be refactored. Is there any way to support the .md files in the Yaml?

`---
title: Index
permalink: index.md
summary: This is the first page, the index
---

[page 1]: pages/page-one.md
[page 2]: pages/page2.md`

(Please note that I use a Jekyll plugin that converts any .md links to .html links because otherwise the above example would not work with Jekyll, I'm fine with that because when I would use the HTML extensions the plugin would not work ;-)

**Comment by vsch** [comment]
@neoaddix, learning Jekyll is on my todo list. I would like to add full Jekyll syntax support and refactoring features.

I am going to see how to access PsiTree in an injected block so that I can use the YAML plugin in the IDE to provide references to `permalink:` value if it matches a file.

From what I see in the Jekyll docs only the name needs to match. Directory and extension should be ignored. When renaming the file, only the name part should be renamed.

Can you please confirm if this makes sense?

**Comment by neoaddix** [comment]
@vsch, I think that makes sense yes. As far as I know the Jekyll logic is
like this:


   - Any markdown file with the frontmatter yaml at the top will get
   converted
   - They will be converted to their permalink filename and path
   - Depending on how someone uses Jekyll you can choose to give everything
   an absolute permalink, so all files are generated in the root folder and
   you don't have to worry about file paths

There are some caveats though:

   - Jekyll will not convert .md references to html, so all linking in the
   md files needs to use the final .html extension (I'm using a plugin that
   converts .md references to .html before Jekyll starts converting to
   circumvent this
   - Using the plugin the references use paths/filename.md structure.
   Jekyll generated html cannot handle that well, unless the path is also in
   the permalink.

I'm planning the setup of a documentation theme with Jekyll for my company
this week, I can share it with you so I can show you some examples of how
things work?

Jeroen

**Comment by vsch** [comment]
@neoaddix, yes, I would appreciate a sample actual Jekyll use case.

I will probably add Jekyll or Text based refactoring configuration that will allow flexible reference/refactoring in markdown elements based on RegEx patterns. That way any additional front matter variables, or other text elements, could be refactored without me having to modify code. 

For example file ref pattern: `^permalink: (?:(?:.*/)*)([^\\]+)\.html$` to file name replacement: `$1.md` would extract the file name from the permalink and change the extension.

A map from file name to permalink would take care of replacing it during refactoring. Similar to how link mapping works.

BTW, the link mapping feature in the next release, already available on the EAP update channel, can be used to change all the links to .html during completions and to resolve .html link addresses to .md documents. It can also be used to change path. Along with scope based markdown rendering profiles this allows you a lot of flexibility in how each document will be processed and rendered. See: [Modifying Link Processing](https://github.com/vsch/idea-multimarkdown/wiki/Modifying-Link-Processing) and [Installation: Configuration Settings](https://github.com/vsch/idea-multimarkdown/wiki/Installation#configuration-settings)

![linkmap](https://cloud.githubusercontent.com/assets/10299086/20037613/ddc2b3ac-a3f0-11e6-91ca-8d443bdab296.gif)

<img width="1004" alt="screen shot 2016-11-06 at 7 13 55 am" src="https://cloud.githubusercontent.com/assets/10299086/20037589/a28007ea-a3f0-11e6-8c81-02885bc5297e.png">

**Comment by vsch** [comment]
I am going to open a new issue for the enhancements.
