### ISSUE TITLE
MultiMarkdown running for HTML files not just MD files

### ISSUE THREAD

**Issue by PAGG-ESkopal** [vsch/idea-multimarkdown#191]
I am using WebStorm 2016.1 and MultiMarkdown 1.4.9. When I open a .html file to edit -- MultiMarkdown appears on the right side.  It should only be appearing for .MD files.

I could not find any way to stop this behavior -- except to disable MultiMarkdown.

The "Markdown Language" entries in Settings->Editor->File Types are: *.markdown, *.md and *.mkd.

**Comment by PAGG-ESkopal** [comment]
I found the problem -- On the main MultiMarkdown settings page, uncheck "Split Preview for HTML documents".  I had no idea that any settings for MultiMarkdown would extend beyond MarkDown documents.  The description might be "Split Preview for all HTML documents *".

**Comment by vsch** [comment]
@PAGG-ESkopal, if you hover over the option there is a more detailed description.

<img width="794" alt="screen shot 2016-04-04 at 5 24 41 pm" src="https://cloud.githubusercontent.com/assets/10299086/14263729/3a874898-fa8a-11e5-899e-29c3fcddf9b3.png">

It is an experimental feature. Useful mostly in previewing using Swing preview which is used in the IDE for UI elements. Otherwise difficult to preview without writing explicit code.
