### ISSUE TITLE
Allow different syntax highlighting for Heading Marker and Heading Text

### ISSUE THREAD

**Issue by Morgul** [vsch/idea-multimarkdown#2]
This is just a feature request; a different markdown plugin I've tried has support for that and I found it nice (but that plugin has other major issues).

**Comment by vsch** [comment]
I considered doing it just for orthogonal flexibility, but it would require changing pegdown. Not a problem in itself, but if I was the only one interested, I could not justify to Methias of https://github.com/sirthias/pegdown to change the operation of the parser on a whim, even if I provide the PR with tests.

I could not argue why it would be a must have benefit because I lack the imagination to see where making the two highlight differently would be a visual benefit to the end user, like you and I. 

Do you have a link or a screenshot where the two different highlights are visible and it is a head slapping "wow, of course it is a must!"

**Comment by Morgul** [comment]
Unfortunately, it's really just a subtle thing. _I_ like it, and enough people do that someone else has implemented it, but unfortunately, I doubt a screenshot would win over anyone who doesn't already want it.

Still, if you want a screenshot, I can generate one, I believe.

TBH, though, this can totally wait till the Grammer-Kit rewrite mentioned in #1.

**Comment by vsch** [comment]
Yes a screenshot would help. The easiest way to get any developer to work on a feature is to get him to want it for his own use. :)

**Comment by vsch** [comment]
@Morgul, it is now available in version 1.0.15. Freshly minted. Defaults to inherit Atx Header 1 and Atx Header 2 color settings.
