### ISSUE TITLE
Correct the idea-version dependency or support older JDK

### ISSUE THREAD

**Issue by pschulz** [vsch/idea-multimarkdown#22]
Even if it is possible on MacOS to change the JDK IDEA (or IDEs based on it) is started with, there are tons of issues that require to use the legacy 1.6 that Apple provided.
Additionally, PHPStorm for instance is still not shipped with a bundled JDK, unless you download the special Yosemite version, and "[...] this non-default option may contain some issues."
https://intellij-support.jetbrains.com/hc/en-us/articles/206827627-IDE-doesn-t-start-after-updating-to-Mac-OS-Yosemite-or-Mavericks

So I believe the decision to require a higher Java version is a bad idea unless Jetbrains changes its opinion and minimum requirements.

To avoid any installation trouble and unhappy users I suggest to 
- Make the latest release to depend on an IDEA build version that requires JDK 1.8, so that all existing users get the releases < 1.1 ;-)
- or compile it by default with java 1.6
- or find out a way how to enable javafx in the bundled Java (https://youtrack.jetbrains.com/issue/MPS-22289, https://wiki.openjdk.java.net/display/OpenJFX/Building+OpenJFX)

**Comment by vsch** [comment]
@pschulz thank you for your feedback. The compilation for 1.8 is actually an error on my part. It does not need to be compiled for 1.8. I didn't realize that the last version was released, compiled for 1.8 until a user reported it. But with all the experimentation trying to get it to work with different versions and didn't notice that I changed the setting. I have 6 JDKs and 9 IntelliJ product/version combinations installed.

I just verified and in the next release version you it automatically turns on 'Use Old Preview' if the jdk is 1.6 and no load problems.

I will be releasing it shortly. You can continue to use the previous version which you can download from the [Official JetBrains plugin site Version 1.0.24](https://plugins.jetbrains.com/plugin/download?pr=&updateId=21191).

I opened a pandora's box with JavaFX but it has been a very steep learning curve. Brought me back to the old days of Java when I was maintaining a java front end in 2001, which I thought were gone but not yet, "Java: Write once. Debug everywhere!"

**Comment by pschulz** [comment]
:joy: :thumbsup:
I'm still on 1.0.24 as I have read the JDK comment. 
JavaFX is Java's default UI library (see http://www.oracle.com/technetwork/java/javafx/overview/faq-1446554.html#6). 
We should open a request @jetbrains, perhaps they offer a safe or at least a documented way how to develop Idea Plugins with JavaFX.

**Comment by vsch** [comment]
@pschulz, Good luck with getting JB to spend time on JavaFX. It is broken in so many ways. I can run on the Mac with 1.8u51 no issues, with 1.8u60 used to crash the IDEA. The issue: url(data: ) for woff font in CSS which 1.8u51 handles but not later versions. It is also slow, that is why I put in `Use Old Preview`. I can't stand lag but working with real CSS, HTML, JavaScript is a joy compared to the bastardized HTMLEditorKit which too brings old memories when I was developing a rich UI in IE3 and Netscape Navigator in 1998. It was pure hell. Jaded me to HTML and JavaScript for over a decade.

New version released. Will run with JDK 1.6. You should upgrade even if you don't use the new preview. I am still fixing bugs in the old preview.

**Comment by pschulz** [comment]
@vsch Thank you so much for the new release and this great plugin in general.

Now I also see, why JB does not support JavaFX in Plugins at the moment. But if you are interested in alternative ways of HTML rendering, you should give theses a try.
http://cssbox.sourceforge.net
https://github.com/flyingsaucerproject/flyingsaucer

May be I misunderstood what you are searching for, but ...

**Comment by vsch** [comment]
@pschulz, thank you for the pointers. I will look into flying saucer because it is one I have not tried. CssBox is too finicky in its HTML parsing. So much so that I could not figure out why it was failing to render a simple page, would just cut-off at some character. With markdown having a tendency to spit out unprocessed text if it gets confused that would mean truncated pages unless I handle all the cases.

I did not want to spend even more time "catching fleas" as I already do plenty of that with all the IDEA & JDK versions I am trying to support in the plugin. BTW, the reason last release was crashing with jdk 1.8.0u60 but working fine in u51 is that WebView in u60 no longer handles css @font-face with url(data: ) nor does it handle font/woff. Only ttf fonts in a file. Go figure. Never thought working features would be removed. I still don't think a meaningless crash is a good way to handle it.

I'll take a look at flyingsaucer, at least the name is intriguing.

**Comment by vsch** [comment]
Forgot to mention that the since-build is actually going down in the next release to 133.1711. I managed to make it work, of course only old style preview.

**Comment by vsch** [comment]
New release available 1.1.2:
- Fix Exception reporting for ScratchFileService not found on older versions. If the check fails then no others will be performed until build of IDE changes.
- Fix WebView Preview Tab not working for 1.8u60 and up. In 1.8u60+ it no longer handles fonts with uri(data:) nor font/woff only .ttf.
- Fix allowing capital X to mark closed tasks. Fix #24
- Fix lack of ComboBox for Build 133.1711, now for earlier builds using List for theme selection instead of ComboBox.
- Change since-build to 133.1711, earliest tested version IDEA 13.0 CE, new Preview is not available but old preview works.

Please let me know if it solves your issue and/or close the issue which will be taken as issue solved.

**Comment by pschulz** [comment]
(y) works for me. Thank you!

**Comment by vsch** [comment]
My pleasure and I figured it worked. When something doesn't there is a clamour of issues. Otherwise, its pretty quiet. :)
