### ISSUE TITLE
unable to open *.md files

### ISSUE THREAD

**Issue by hrtkolleh** [vsch/idea-multimarkdown#229]
> IntelliJ IDEA 2016.1.1
> Build #IU-145.597, built on March 29, 2016
> JRE: 1.8.0_60-b27 x86
> JVM: Java HotSpot(TM) Server VM by Oracle Corporation
> MultiMarkdown version 1.5.0

Plugin doesn't seem to recognize *.md files. The unknown file type icon is beside all .md file types. After changing the filetype to *.markdown the icon changes and the plugin recognizes it.

**Comment by vsch** [comment]
@hrtkolleh, you have `Markdown Support` plugin enabled. MultiMarkdown recognizes markdown files with extensions: `.md`, `.mkd`, `.markdown`. While Markdown Support only `.md` files, so these are taken over by that plugin.

You need to disable Markdown Support in order to use MultiMarkdown otherwise it will be used for .md files and it may cause other conflicts. You only need one markdown plugin enabled.

<img width="871" alt="screenshot_pluginconflict" src="https://cloud.githubusercontent.com/assets/10299086/14963955/24872270-1074-11e6-8827-526732915f32.png">

**Comment by stevesobol** [comment]
I uninstalled Markdown support, only Markdown Navigator is enabled, and I still had to add`*.md` as a Markdown Language extension. Once I did that, everything worked.

**Comment by vsch** [comment]
@stevesobol, what was associated with `*.md` before you changed it? 

The plugin does not change extension associations. It uses the API to define extensions recognized by the plugin: `.md`, `.mkd` and `.markdown`.

It is possible that this was done by Markdown Support.

**Comment by stevesobol** [comment]
Markdown Support was what I was using before switching.

I uninstalled it before installing Navigator.

My personal opinion is that the plugin should change the *.md association or add it if it doesn't exist; but I can also see valid arguments for _not_ doing that, and in any case, it wasn't a big deal to add the association, anyhow.

**Comment by 92389ynxzz8i3** [comment]
Here, I use Visual Studio code for programming. I downloaded an MD file (. MD) and opened it with this software, but it failed.
Do you have any way to show me?
