### ISSUE TITLE
Incorrect list generation

### ISSUE THREAD

**Issue by lolmaus** [vsch/idea-multimarkdown#240]
### Source markdown

``` md
* foo
  * bar
  * baz
    * quux
```
### Expected result

<ul>
  <li>foo
    <ul>
      <li>bar</li>
      <li>baz
        <ul>
          <li>quux</li>
        </ul>
      </li>
    </ul>
  </li>
</ul>

``` html
<ul>
  <li>foo
    <ul>
      <li>bar</li>
      <li>baz
        <ul>
          <li>quux</li>
        </ul>
      </li>
    </ul>
  </li>
</ul>
```
### Actual result

<ul>
  <li>foo</li>
  <li>bar</li>
  <li>baz
    <ul>
      <li>quux</li>
    </ul>
  </li>
</ul>

``` html
<ul>
  <li>foo</li>
  <li>bar</li>
  <li>baz
    <ul>
      <li>quux</li>
    </ul>
  </li>
</ul>
```
### Version used

Markdown Navigator 1.6.1

**Comment by vsch** [comment]
@lolmaus, GitHub flavoured markdown takes a few liberties with indentation size. Markdown requires 4 spaces or a tab for nested list indentations. GitHub allows 1 space for the first nested list and 2 spaces for subsequent lists.

This is one of those cases where the plugin makes no attempt to duplicate GFM's stretching of Markdown. You need to use 4 spaces for indentation then both the plugin and GitHub will display the correct result:

```md
* foo
    * bar
    * baz
        * quux
```

* foo
    * bar
    * baz
        * quux

<img width="641" alt="screen shot 2016-05-17 at 7 51 45 am" src="https://cloud.githubusercontent.com/assets/10299086/15321406/41394a92-1c04-11e6-9397-53ce7ee478aa.png">

**Comment by lolmaus** [comment]
You're the boss, feel free to close the issue, but I believe GitHub has the absolute majority of your product's use cases.

**Comment by vsch** [comment]
@lolmaus, the real issue with the indents is not that I don't want to but more like I cannot. The parser is currently pegdown and has a standardized indent handling for consistency. Being PEG based parser there is a lot of interdependencies between parsing elements. I am afraid that if I just go ahead and change it for lists this can cause side-effects in some markdown sources. Side-effects like infinite parsing loops or really long parse times.

These issues in pegdown have already caused me (and some users) more grief than I care to admit.

As for majority of users using it strictly for GitHub, I cannot tell without doing a survey. A few are using it for Jekyll and Django based projects. Changing it would also require adding a parser option so that someone using the plugin for Jekyll or other processor can turn it off and I already maxed out the pegdown extension flags mechanism and would need to add more changes.

I will leave it open as an enhancement for implementation when I replace pegdown with a common-mark based parser with GFM and other extensions for maximum compatibility.

**Comment by lolmaus** [comment]
> I am afraid that if I just go ahead and change it

Make it optional? :trollface: 


> someone using the plugin for Jekyll

That includes me. Default parser for Jekyll is Kramdown which handles two-space indentation in lists like GitHub.

**Comment by vsch** [comment]
@lolmaus, point taken.

**Comment by vsch** [comment]
@lolmaus, GitHub option added for list item interpretation to parser options, which is more like kramdown than GitHub which have differences.

<img width="829" alt="screen shot 2016-10-30 at 9 00 10 am" src="https://cloud.githubusercontent.com/assets/10299086/19836728/d60d1290-9e7f-11e6-9edb-e54c211d0c1c.png">

The indent is not 2 spaces but the column of the first list item text. For example:

```markdown
*  foo
  * bar
  * baz
    * quux
```

[kramdown](http://johnmacfarlane.net/babelmark2/?normalize=1&text=*++foo%0A++*+bar%0A++*+baz%0A++++*+quux) and Markdown Navigator:

<img width="124" alt="screen shot 2016-10-30 at 10 10 31 am" src="https://cloud.githubusercontent.com/assets/10299086/19837094/1c9358ce-9e89-11e6-98e5-389e733087cf.png">

while GitHub renders:

*  foo
  * bar
  * baz
    * quux

I am in the process of adding to the parser ability to emulate list indenting rules of other parser but this is the most difficult part of the emulation. Differences between parsers are major, especially when you start playing with leading spaces before the first list item, spaces between the marker and item text, list item paragraph indentation, etc.

I still have not been able to isolate all the variations. Just when I think I have it pinned down I find another case that does not fit into the model.

**Comment by lolmaus** [comment]
You ![image](https://cloud.githubusercontent.com/assets/200884/19854490/45bd7eb2-9f80-11e6-8736-60ca4c41b8a1.png)!
