### ISSUE TITLE
Markdown files lose focus/can't type when using "Recent Files" dialog

### ISSUE THREAD

**Issue by johnlindquist** [vsch/idea-multimarkdown#242]
I prefer to use the "Recent Files" dialog to navigate when I'm working.

But when I navigate to a markdown file, the cursor doesn't automatically insert back to the correct position. It's odd, because the line is highlighted correctly, but the cursor doesn't appear until I click.

![demo](https://s3.amazonaws.com/f.cl.ly/items/0p3A2P2I2J453A1L2n0Y/Screen%20Recording%202016-05-19%20at%2007.45.22%20AM.gif?v=52889c98)

Workaround: Using "Search Anywhere", the cursor focuses fine.

In case it's a platform issue (I know most popup-related/focus stuff usually is):
```
WebStorm 2016.2 EAP
Build #WS-162.74.17, built on May 13, 2016
WebStorm EAP User
Expiration date: June 12, 2016
JRE: 1.8.0_76-release-b49 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
```

**Comment by vsch** [comment]
@johnlindquist, I use recent files all the time but on OS X the focus is set correctly in both IDEA, WebStorm and PhpStorm. I think it is a platform issue because I am not doing anything special on file activation.

On Windows I downloaded WebStorm both the 2016.1.2 and 2016.2 EAP and both had the focus right running under parallels on OS X which could also affect focus.

The focus issues come and go, especially in EAP releases.

Can you try disabling Markdown Navigator and enabling Markdown Support plugin. These plugins both use the split editor, if Markdown Support does not have the focus issue I will compare the code and see if there is a fix for this.

If Markdown Support also has this issue then you should open an issue with JetBrains [WebStorm YouTrack Issues](https://youtrack.jetbrains.com/issues?q=project:%20%7BWebStorm%20_%20IntelliJ%20Web%7D) so it is fixed:

**Comment by johnlindquist** [comment]
Tried the default markdown plugin and the problem still exists, so I filed on bug on youtrack.

(I used to work at JetBrains a couple of years ago :) )
