### ISSUE TITLE
Auto scroll to source

### ISSUE THREAD

**Issue by kutenai** [vsch/idea-multimarkdown#246]
When I make a change to the source, the preview always scrolls back to the top. This is the most annoying behavior. Is there a way to have the preview always track the cursor position on the source?

**Comment by vsch** [comment]
@kutenai, this only happens with the Swing preview. I will check for a bug because if I remember right the Swing preview should also keep the scroll position unchanged from manually scrolled position like  the JavaFX preview.

Tracking the source to preview position is on the todo list and is partially implemented in Swing and JavaFX but not enabled. I will let you know as soon as I have it completed.

**Comment by vsch** [comment]
@kutenai, thank you for bringing this to my attention. It was indeed a bug that I introduced when I started implementing scroll to source position. I disabled the option of setting scrolling to source but not the code that uses the now always 0 position.

I completed the scroll to preview so that it works reasonably well to be used.

Patch release available in EAP stream and for download here: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.7.0.3.zip

I added an option in settings to enable scroll to source for Swing preview. When disabled the scroll position will remain to whatever position you manually scroll the preview.
