### ISSUE TITLE
OSX Version Hangs after install

### ISSUE THREAD

**Issue by gamename** [vsch/idea-multimarkdown#25]
See https://youtrack.jetbrains.com/issue/PY-16863

**Comment by vsch** [comment]
@gamename, sorry for the hang up. I had that during development of the plugin when running under JDK 1.8.0u60. Found that it was caused by JavaFX WebView no longer handling url(data: ) for CSS embedded fonts and showing it by crashing in the native library. However, in the latest version of the plugin the fonts are no longer embedded and are in a file.

What version of the plugin were you using and what version of the JDK is the PyCharm running under? You can see the JDK version in the about dialog.

I downloaded PyCharm Community Edition, 141.1899 and testing it now with the latest plugin.

**Comment by vsch** [comment]
@gamename, So far I was only able to have a hang followed by a crash with JRE 1.8.0u60 and only with the plugin version 1.1.0, this was the first release with JavaFX WebView for the preview tab and I lacked the battle field experience with JavaFX WebView problems. The saying "Fools rush in where angels fear to tread" is very appropriate in this scenario.

However, I tested plugin versions 1.1.0 through 1.1.3 with the bundled JDK in PyCharm and 1.8.0u60 downloaded from Oracle and the only crash was with 1.1.0 with 1.8.0u60.

For all other cases the plugin either worked with the new preview or used the old one that does not use JavaFX.

1. If you can give me a screen shot of the about box of your phycharm it has all the JRE/JVM info:

    ![screen shot 2015-09-11 at 10 41 37 am](https://cloud.githubusercontent.com/assets/10299086/9817708/9f6bd054-5872-11e5-8344-312dc7fe583e.png)

2. If you can give me the size of the plugin installation zip file, I will know which version it was. 

I very much would like to duplicate this just in case it still occurs under some rare configurations. 

Thank you for your feedback and my apologies for the hang.

**Comment by gamename** [comment]
Hi Guy,

No worries. I was able to work around it, but thanks. 

Here is the screenshot:

![image](https://cloud.githubusercontent.com/assets/42153/9822034/c352372c-5883-11e5-9e75-bd6f59874f7a.png)


I dunno the size of the zip file.  I responded to a prompt to install plugins for markdown support.  It was auto-magic.

Thanks,
-T

**Comment by vsch** [comment]
@gamename thanks. Your setup is fine for the plugin. It was only the first release that was problematic.

**Comment by gamename** [comment]
Good. Thanks for the quick response. :)

**Comment by vsch** [comment]
You are welcome. BTW, I know exactly what you went through. I was ready to explode when the IDE started hanging on me because of my own plugin. I had to clear it out more than once during debugging, so when I apologized for the hang it caused you, it was from the heart and with full sympathy of experience.

**Comment by gamename** [comment]
No worries.  I understand.  Also, your plugin is one of the best.  I really like how its simple and easy to use.  So keep up the good work.
