### ISSUE TITLE
Unexpected crashes?

### ISSUE THREAD

**Issue by johnlindquist** [vsch/idea-multimarkdown#255]
WebStorm is unexpectedly crashing/closing on me (not hanging, just completely exiting) every few minutes. I'm _only_ working on markdown files.

I've attached logs. Do you see anything? Maybe it's a platform bug? Thanks!
[log.zip](https://github.com/vsch/idea-multimarkdown/files/319324/log.zip)

**Comment by vsch** [comment]
@johnlindquist, nothing jump out. The last entries show git4idea plugin traces. 

If you can run the IDE from the command line. When a crash occurs in a native library Java exceptions don't work and you may only get a stdout or stderr last gasp out of the application.

When I was working on the early version of JavaFX WebView implementation, took me a while to figure out why it was crashing because nothing would show. For a while I launched the IDE from the command line to catch all output on the console.

**Comment by chrkv** [comment]
@vsch there are some similar reports: https://youtrack.jetbrains.com/issue/OC-13798

**Comment by vsch** [comment]
@chrkv, thank you very much for the update.  

@johnlindquist, It is a JavaFX WebView crash on a null pointer. I will try to dig up where exactly it crashes and if I can figure out what HTML input to WebView is causing it to crash, then I can mitigate it in the plugin.

**Comment by vsch** [comment]
@chrkv, @johnlindquist, a temporary work around is to switch to Swing Preview.

I am trying to duplicate this but it requires opening a file with specific content that causes the WebView exception in a native library. I will make a patch release with a tentative fix. Until I can isolate the specific content that causes the issue I can't be sure that it is fixed.

**Comment by vsch** [comment]
@johnlindquist, @chrkv, I added a test action that opens all markdown files in a project. It opens a file, waits for it to load in WebView, waits 250ms then opens the next file.

I am running it against a WebStorm project with 3,000+ markdown files now. If a problem file is in there  it should  trigger the bug. I'll keep you posted.

**Comment by vsch** [comment]
@johnlindquist, @chrkv, IDEA issue https://youtrack.jetbrains.com/issue/IDEA-157836 part of this issue.
