### ISSUE TITLE
Feature Request: Convert Jira to Markdown

### ISSUE THREAD

**Issue by bmsantos** [vsch/idea-multimarkdown#256]
It would be useful for many developers to have a Jira to Markdown notation converter and vice versa.

It could just integrate this lib: https://github.com/FokkeZB/J2M

**Comment by vsch** [comment]
@bmsantos, I took a quick look at the source of the converter and don't see an issue with implementing it  in Java so that the plugin does not have to rely on JS in processing. It will make it simpler.

How do you envision using it? 

Would `Copy Markdown as Jira` and `Paste Jira as Markdown` actions do the trick or do you see a better option?

**Comment by bmsantos** [comment]
Just a button in the markdown window that allows to convert the current document to JIRA format.
And, if possible, another button that will convert a selected group of lines from JIRA to markdown.

**Comment by vsch** [comment]
@bmsantos, I played with the J2M conversion from Jira to markdown and it is quite limited. I would have to implement conversion with more features. Otherwise, as soon as it is available there will demands to add more elements and correct bugs.

The buttons on the markdown editor toolbar will only work in a markdown file. What this will mean is that you will have to paste Jira into markdown then convert and in reverse: convert lines, copy, then undo to revert back to markdown.

Would it not be easier to have a button for Paste Jira as Markdown and Copy Markdown as Jira? That way Jira source can come from anywhere you can do a copy and does not have to be in a markdown document.

I have been wanting to add copy/paste handler for markdown for other things like copying link refs and having the plugin paste the corresponding definitions if they are missing from the destination file. So I might even add auto detection that the pasted text is Jira and offer auto conversion.

Here is what I am considering for conversion (two way conversion):

1. Headers (`h1.`, ... `h6.`)
2. Text effects: 
    - `*strong*` to `**strong**`
    - `_emphasis_` to `*emphasis*` or `_emphasis_`
    - `-deleted-` to `~~strikeout~~`
    - `{{monospaced}}` to <code>\`code\`</code>
    - `bq.` to `> block quote`
3. Elements
    - `{quote}` to `> block quote`
    - `----` to thematic break ie. HRule `---`
    - the `--` and `---` don't need conversion since `Smarts` extension does it automatically
    - Links `[url]` and `[label|url]` to `[]()`
    - anchors `{anchor:anchorName}` are a problem, not converted for now 
    - Images `!url!` and `!url|ignored!` to `![]()` 
4. Lists    
    - all nested bullet and numbered list
5. Tables
    - `||header||...||` to `|header|...|` and `|----|-...-|`
    - `|column|...|` as is
6. Other block elements
    - `{noformat}` to verbatim indented code
    - `{code:lang|ignored}...{code}` `{code:title=File.ext|ignored}...{code}` to code fence with language determined by the extension of the file used in the `title=` or just the lang part.
7. Special characters
    - escape special Jira characters: `{`, `}`
    - optionally convert graphical emoticons to Emoji shortcuts where possible. Left as is where no conversion exists.
    
        ![Jira emoticons](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/jira/Jira_emoticons.png) 
    
        | Jira | Emoji Icon           | Emoji Shortcut         | Jira      | Emoji Icon                | Emoji Shortcut              |
        |------|----------------------|------------------------|-----------|---------------------------|-----------------------------|
        | :)   | :smile:              | `:smile:`              | (+)       | :heavy_plus_sign:         | `:heavy_plus_sign:`         |
        | :(   | :frowning:           | `:frowning:`           | (-)       | :heavy_minus_sign:        | `:heavy_minus_sign:`        |
        | :P   | :stuck_out_tongue:   | `:stuck_out_tongue:`   | (?)       | :question:                | `:question:`                |
        | :D   | :grinning:           | `:grinning:`           | (on)      | :bulb:                    | `:bulb:`                    |
        | ;)   | :wink:               | `:wink:`               | (off)     | ::                        | `::`                        |
        | (y)  | :thumbsup:           | `:thumbsup:`           | (\*)      | :star:                    | `:star:`                    |
        | (n)  | :thumbsdown:         | `:thumbsdown:`         | (\*r)     | ::                        | `::`                        |
        | (i)  | :information_source: | `:information_source:` | (\*g)     | ::                        | `::`                        |
        | (/)  | :white_check_mark:   | `:white_check_mark:`   | (\*b)     | ::                        | `::`                        |
        | (x)  | :x:                  | `:x:`                  | (\*y)     | :star:                    | `:star:`                    |
        | (!)  | :warning:            | `:warning:`            | (flag)    | :triangular_flag_on_post: | `:triangular_flag_on_post:` |
        |      |                      |                        | (flagoff) | :crossed_flags:           | `:crossed_flags:`           |
        
If you have a better mapping for emoji or have other suggestions post them here so I can add them to the ToDo list.

**Comment by bmsantos** [comment]
@vsch This looks really good and will offer a much better integration. I like the functionality idea.

**Comment by vsch** [comment]
@bmsantos, just opened my first Jira issue, requesting to create a new project. I want to host flexmark-java parser artifacts on maven central. 

I can see why you want a markdown to Jira and back conversion.

**Comment by bmsantos** [comment]
Yes! Its a PITA! 😐

**Comment by vsch** [comment]
@bmsantos, got Markdown to JIRA toolbar button and action implemented in EAP update channel or download and install plugin from disk: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.1.0.14.zip

Selected text or whole document is re-parsed as markdown and then the AST rendered as JIRA formatted text. So any references defined outside the selection will render as plain text since they are not defined.

Basic Markdown plus tables, strikethrough, emoji are converted. 

❗ If you find discrepancies or errors please provide a sample Markdown, generated JIRA and correct JIRA.

On the to do list:
Not converted: anchors.
Not escaped { }.

Implementing JIRA to markdown will take a bit more work since I have to write a JIRA parser. There are a lot of caveats in handling blank lines in lists and other details.

❓ Is there a spec for the format? I don't relish having to reverse engineer all its idiosyncrasies.

**Comment by bmsantos** [comment]
Nice, will have a look in it soon. Thanks

**Comment by vsch** [comment]
@bmsantos, EAP update with HTML to Markdown conversion is available in EAP release. 

I implemented HTML to Markdown parser in the [flexmark-java](https://github.com/vsch/flexmark-java) project so this functionality is available in OSS if desired. 

Now you can just select the HTML in the browser preview of the Jira issue and paste it into Markdown to get automatic Markdown conversion. I think this is more powerful and generic than having to parse and convert Jira to Markdown.

From Jira Issue:

<img width="321" alt="screen shot 2017-01-22 at 8 09 05 pm" src="https://cloud.githubusercontent.com/assets/10299086/22188073/4bc9a786-e0df-11e6-8717-1ca09702c949.png">

To Markdown pasted:

<img width="978" alt="screen shot 2017-01-22 at 8 10 46 pm" src="https://cloud.githubusercontent.com/assets/10299086/22188076/4ef18398-e0df-11e6-96c0-20ab032713ff.png">

Not being able to find a comprehensive Jira syntax manual now is moot. Don't you agree?

To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by bmsantos** [comment]
@vsch, this is outstanding work!! :)
I'm not on an EAP version. In which official version will this be first released? I'm currently on Ultimate 2016.3.4.

**Comment by vsch** [comment]
@bmsantos, latest plugin release 2.3.1 has this feature. There is a bug in conversion of syntax highlighted `<pre>` wrapped HTML #376 conversion to fenced code which will be released in the next EAP version of the plugin or official release 2.3.2 scheduled for release by Feb 14.
