### ISSUE TITLE
Feature Request: Emoji Support

### ISSUE THREAD

**Issue by KyroChi** [vsch/idea-multimarkdown#257]
I typically use your plugin for writing GitHub READMEs and I like to include emojis. Having these emojis rendered in RubyMine/CLion/IntelliJ would be really neat as I could see exactly how the README would look before pushing it to GitHub.

If I have time this weekend or next weekend I will fork and see if I can figure out how to add support myself.

**Comment by KyroChi** [comment]
Apparently this is not the plugin I use 😮... This plugin looks way better than whatever I am using and it claims its installed on my RubyMine. Time to do some digging as to why its installed but not being used to edit my .md files

**Comment by vsch** [comment]
@KyroChi, you have Markdown Support or another markdown plugin enabled. Only one markdown plugin can be enabled at a time: see https://github.com/vsch/idea-multimarkdown/wiki/Installation#requirements

**Comment by KyroChi** [comment]
I was on 1.6 it looks like, I have updated to 1.7.1 so hopefully that fixes the issues I am experiencing. Sorry for wasting time in your issues section :grin:

**Comment by vsch** [comment]
@KyroChi, no trouble. I'm at the keyboard and screen 12 hours a day. 

I am replacing pegdown as the markdown parser with one derived from commonmark-java. Huge performance gains. With most extensions implemented the new parser is 20x faster than pegdown on average and on larger files 40x faster. Also the new parser is without pegdown's hanging or long parse times for some files.

It is also a easy to add new constructs or parsing options compared to pegdown. Something to look forward to, so don't forget to upgrade to a new version some time beginning of August..

**Comment by KyroChi** [comment]
Haha, I have starred this project and added it to my watching list so hopefully I don't miss it! You have done some awesome stuff here man, keep up the good work. I look forward to future improvements!

**Comment by vsch** [comment]
@KyroChi, if you don't have a license you should get the trial license and give the enhanced features a whirl. I don't know how people manage without all the completions, annotations, intention actions, and especially document formatting. All of the stuff you would expect in a JetBrains IDE. Emoji shortcuts get completions too.

If you use the enhanced features, get the latest patch release. A few bugs were fixed in the list toolbar buttons: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.7.1.4.zip

**Comment by KyroChi** [comment]
@vsch I have educational licenses for IntelliJ, CLion and PyCharm and a professional license for RubyMine (which I use at work). I will take a look at the advanced feature version on Monday, emoji completion would be cool.

**Comment by vsch** [comment]
@KyroChi, if you get your employer to buy a license then you can use it on all the JetBrains IDEs. At the current $10 sale price it should not make a dent in the budget. The emoji completions are sweet:

<img width="410" alt="screen shot 2016-06-17 at 10 28 17 pm" src="https://cloud.githubusercontent.com/assets/10299086/16168593/d0f5ab3c-34da-11e6-8143-57a92c3dde37.png">

You also get completions for link urls to project files, link labels, link refs to references defined in the file, link anchor ref completions to headers in files compatible with GitHub. If I don't have a completion it drives me nuts because I am so used to using them everywhere in the code.

Then you also get refactoring of all the referenced elements so that all references are updated, just like you would expect with refactoring and table auto-format as you type. I can't work with markdown tables without it.

Then there is document reformat with a ton of options. 

Let me know what you think of it.

**Comment by KyroChi** [comment]
@vsch At $10 I will probably just buy it. Getting HR to authorize a purchase is a pain, and not worth $10 to me. I will get it this weekend or next week and let you know how it goes! 👍 Thanks!
