### ISSUE TITLE
Nested lists not working

### ISSUE THREAD

**Issue by markwoon** [vsch/idea-multimarkdown#26]
This doesn't display correctly:

```
* a
  * sub a
* b
```

Unless there's a config variable that governs this behavior...?

**Comment by vsch** [comment]
@markwoon, you need 4 spaces for indentation for sub-lists. GitHub lets you use just one for the first sub-list but that is completely non-standard. In markdown 0-3 spaces are tolerated as not indents. I also don't know if it is a bug or a feature because the second sub-list needs 2 spaces.

```
* a
 * sub a
   * sub sub a
     * sub sub a 
* b
```

to make it more portable across other markdown implementations change it to:

```
* a
    * sub a
        * sub sub a
            * sub sub a 
* b
```

Thank you for pointing out the difference. I don't know if I will be able to duplicate every nuance of GFM markdown parsing especially when they go way off the 'standard' as described by the original [Markdown](http://daringfireball.net/projects/markdown)

I will consider how to show that the indentations are insufficient for a sub-item so that you get visual feedback in the source that it is not a sub-item but another item in the list.
