### ISSUE TITLE
Bitbucket stylesheet

### ISSUE THREAD

**Issue by catalinux** [vsch/idea-multimarkdown#30]
Is there a plan to include also a stylesheet for bitbucket flavor?

**Comment by vsch** [comment]
If you have access to some form of the bitbucket stylesheet it would make the job easier and faster. For every "style" I need to create 4 stylesheets: 2 schemes x 2 renderers. 

I don't have any objections to doing but at the moment I am swamped with implementing IntelliJ Psi based features: refactoring, completion, annotations, quick fixes, etc. I am running on 4-5 hours of sleep a day for the last 6 weeks. So I can't make any commitments for the near future, the next 30 days give or take.

You don't need to wait for me, you can go into settings and load the internal CSS for editing into the custom window. Select the `Use Custom CSS` to have the preview tab use it instead of the built in one. When you get it close enough to your taste you can share it or post it here and I will do whatever finishing touches are required: like making one for every scheme and for both renderers.

Load Internal CSS will load the CSS as selected by the current scheme combobox: Application UI, Default or Darcula. 

<img width="1164" alt="screen shot 2015-09-18 at 3 41 26 am" src="https://cloud.githubusercontent.com/assets/10299086/9954465/46fb7506-5db7-11e5-8024-820c94d41a50.png">

**Comment by catalinux** [comment]
Great answer! Tx. I'll try to get back if any success

**Comment by vsch** [comment]
The help would be much appreciated and would make you get the results much faster than if you wait for me.
