### ISSUE TITLE
Rename files

### ISSUE THREAD

**Issue by bstout** [vsch/idea-multimarkdown#329]
I don't think this is a bug or maybe it is...

I have a whatsnew.md and it exports to whatsnew.html just fine.  I renamed my whatsnew.md to changelog.md and noticed a new changelog.html was there - but I initially opened whatsnew.html because it was still there and I was confused.

Maybe?  We should rename/delete/create the exported files when we rename the source files to keep them better in sync?  I think git has some change for renamed/moved files and maybe the IDE has such an event to hook into also.

Probably not high priority - but just passing along comments.....

**Comment by vsch** [comment]
@bstout, sounds like a bug. I will also see about adding a mechanism to handle removing exported HTML files. The reason I did not make it automatic was to avoid removing files in error.

I will add a dialog box to prompt for removing files the plugin thinks are exported and give the user the opportunity to exclude some files from the operation. It is a chunk of UI work that I left until later.

**Comment by vsch** [comment]
@bstout, Available from the plugin EAP update channel.

I added two actions to the tools menu to do clean up. One will remove all previously generated files and the other will only remove ones which are not part of the current HTML export configuration.

This means that if you manually export a markdown file via the toolbar, which lets you export any file with a valid export config but without the "Export on Save" enabled, then clean up invalid files will delete this file because it is not part of the current export list.

I will add automatic cleanup of invalid files later.

Unfortunately, you will need to export all files so they are added to the list and clean up old ones manually since previous versions did not keep track of files that they generated. After that you will be able to use the clean up invalid files to remove anything that is no longer part of the current export. This includes renamed markdown files or deleted ones.

<img width="322" alt="screen shot 2016-11-04 at 12 32 14 am" src="https://cloud.githubusercontent.com/assets/10299086/19994610/4ac5ae54-a226-11e6-9831-387fda063895.png">

**Comment by vsch** [comment]
@bstout, latest EAP implements exporting files on settings change, including cleanup of invalidated ones. Detects when export config has conflicts that cause file overwrites and has options to re-export all files on project open.
