### ISSUE TITLE
Markdown Navigator breaks the line end whitespace trimming feature of EditorConfig

### ISSUE THREAD

**Issue by lolmaus** [vsch/idea-multimarkdown#335]
Hey @vsch, how are you?

I've started a new project and discovered that line end whitespace is no longer removed on save. This feature from the EditorConfig plugin is tiny, but when I was deprived of it, it turned out to be extremely important.

I get endless lint errors, and removing whitespace manually is super tedious. IDEA tends to produce tons of it!

JetBrains support suggested to disable custom plugins, and by using the artillery fork method I ended up with Markdown Navigator. I. e. disabling any other plugin does not resolve the issue, but disabling Markdown Navigator does.

I've got files named `_markdown.js` in my project, maybe that's interfering somehow.

Now working without a plugin I paid for. Please look into this.

**Comment by vsch** [comment]
@lolmaus, some people at JetBrains like to blame third party plugins for everything without explanation. 

When you name a file with _ext1.ext2 the IDE treats it as a template file with template language being ext2 but the file being of ext1 type.

The plugin does not recognize .js files on its own, the IDE tells it that it is a Markdown File. 

In markdown stripping trailing spaces needs to be done according to markdown rules otherwise the markdown rendering will be messed up, seriously if hard-breaks (two or more spaces at the end of the line) are used. Therefore the plugin overrides the general trailing spaces settings with a Markdown specific one. Next version has a "Use Default" setting which will follow the global IDE one.

In the plugin you can set Trim All Trailing Spaces for markdown files. This should resolve the problem for you with _markdown.js files.

❓ Can you please give me a YouTrack issue for this so I can pipe in on the subject?

![screen shot 2016-11-18 at 1 10 38 pm](https://cloud.githubusercontent.com/assets/10299086/20441084/e933a2e2-ad90-11e6-97c6-d634a10b3326.png)

**Comment by lolmaus** [comment]
It was a support ticket, not a YouTrack issue. :(

Is this a bug or a feature? Sounds like something unwanted.

**Comment by vsch** [comment]
This is what I want to address. It is a feature of the IDE to support template languages. It is a feature of the plugin to not treat trailing space trimming according to the general IDE setting but have a markdown specific one.

It is a feature of the IDE to let custom language plugins to handle their language specifics.

This is something that the users must become aware of. I will contact someone at JetBrains and see if we can mark this type of issue to either them handling it with understanding or just simply to direct the users to me if it is a markdown language template issue so I can address this.

Forcing users to do a binary search, artillery fork or any other effort for a known issue is not acceptable from my point of view.

**Comment by vsch** [comment]
BTW, I forgot to mention that in the next release the trim trailing spaces is a per project setting in Editor > Code Style > Markdown. So you will be able to control it on a per project basis.

**Comment by lolmaus** [comment]
I've just tried reenabling Markdown Navigator, and the issue persists in all JS files, even the ones that don't start with an underscore and don't contain the word `markdown`.

**Comment by vsch** [comment]
@lolmaus, I am going to have to debug this with EditorConfig installed. i don't see why .js are affected when they are not markdown but stranger things have happened in plugin interactions.

To confirm, you are using the release version of the plugin: 2.1.1?

**Comment by vsch** [comment]
@lolmaus, can you try the EAP version of the plugin? You can Download and install plugin from disk: https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.1.1.34.zip

The handling of trailing spaces has been changed to remove the original idea-markdown implementation, which JetBrains is phasing out, to the trailing space filter extension. Maybe that will resolve the issue faster. There a lots of changes from that version because it would not compile in the new version of the IDEs due to removal of some library files in the distribution. 

In the mean time I have the release version of the plugin code compiled and will start testing it with EditorConfig.

**Comment by vsch** [comment]
@lolmaus, can you please send me a copy of your .editorconfig file.

**Comment by lolmaus** [comment]
@vsch https://github.com/lolmaus/lolma.us/blob/master/.editorconfig

Will try the EAP version later (PS I'm on IDEA RC3).

**Comment by vsch** [comment]
@lolmaus, so much more reason to use the EAP. I am developing on RC3, but a custom build with a few bug fixes that are not yet in the official release. I also submitted an enhancement patch for an extension to the trailing spaces mechanism that will allow specifying how many trailing spaces to keep. The current extension API for the filter can only say remove all trailing spaces or keep all. For markdown some lines are remove all, others are keep 2, and due to differences in parsers keep 1 is also needed.

However, without the extension adopted you will only get remove all or keep all in markdown. should not affect other files, unless there is an issue in interaction with editor config.

If you don't mind and get the chance can I still get a copy of the editorconfig file so I can figure out what is causing the issue.

**Comment by lolmaus** [comment]
I've just tried latest EAP (`idea-multimarkdown.2.1.1.40.zip`) and the issue persists. Have to fall back to the default Markdown plugin. :sob:

**Comment by vsch** [comment]
@lolmaus, can you send me a copy of your .editorconfig file and a small sample of the .js file that has the problem so I can debug it. I don't have an editor config file plus it is some setting in the file that could be causing this.

I am working on the next release and want to get this addressed too. BTW, I rewrote the JavaFX browser integration. AWESOME typing response. I can roll my head on the keyboard and get zero delay with the preview on and my IDE window set to full length (iMac Retina screen). 

You would never guess what was causing the problem with JavaFX performance. I instrumented my whole code for the browser. Nothing. Finally tried on a hunch and removed the frame around the page (like on GitHub) and right  away performance jumped. Then more playing I found that it was border-radius of 3px for two bottom corners of that border frame. It appears that as soon as you have radii in a border JavaFX renders the content to a bitmap. I noticed that with the frame it was printing to PDF all pixelated but it did not click at that time. I removed the two radii at the bottom which no one even sees and now scrolling and rendering is oodles faster. I also rewrote the interface so it is interruptible. If you type really fast then page rendering is interrupted to favour typing performance.

I expected this performance from the new parser that I rewrote, I get 1.5ms parse times for a 1000 line file, but the browser was getting in the way. Now with the rewrite of the JavaFX WebView integration you really get plain text performance with markdown syntax highlighting. It would be a shame not to be able to use it now that it is not only better looking with more features than Markdown Support, but also faster. :(

**Comment by lolmaus** [comment]
@vsch Great job figuring out performance! Causes of such issues can hide really deep.

I had linked to my `.editorconfig` file above. Here it is again: https://github.com/lolmaus/lolma.us/blob/master/.editorconfig

The issue happens in all JS files for me (and maybe in other filetypes too). This is the one I tried the last: https://github.com/lolmaus/lolma.us/blob/master/app/locales/en/translations.js

If you still fail to reproduce, I can share my `.idea` folder, then `~/.IntelliJIdea2016.3`.

**Comment by vsch** [comment]
@lolmaus, thanks for reposting the links. I will take a look at it.

I've been running on 4-5 hours of sleep for the past two weeks and haven't slept since yesterday morning. Been up for 27hrs. Got excited when I figured out what was causing the performance disaster. Then decided to rewrite the implementation. It really rocks. Its like typing in a plain text file, unless your file is 5000 lines. Even at 12,000 lines and 500k file it is almost usable even with preview.

**Comment by vsch** [comment]
@, fixed. It was a small typo with big consequences. Thank you for the sample files and editor config file.

EAP 2.1.1.46 has the fix. Available on the plugin EAP update channel.

**Comment by vsch** [comment]
@lolmaus, fixed. It was a small typo with big consequences. Thank you for the sample files and editor config file.

EAP 2.1.1.46 has the fix. Available on the plugin EAP update channel.

**Comment by lolmaus** [comment]
My pleasure! Thank you for your hard effort. :bow:
