### ISSUE TITLE
2.1.1.40 Fail to re-gen HTML files when HTML already exists

### ISSUE THREAD

**Issue by bstout** [vsch/idea-multimarkdown#340]
I regenerated all HTML from .md and saw a proper tree of html files.  I then edited a .md file and saved it, but a new HTML wasn't then generated.  I then again went to regenerate all HTML files from .md and still no new html file.  I think deleted the html file, regenerated all, and now the HTML file was created with my new edits.

**Comment by vsch** [comment]
@bstout, sorry I did not catch this one. There were two bugs in one here.

The on save export was not forcing the export but relying on the file modification time stamp and due to a bug I was comparing the wrong "modification  timestamp". Deleting the HTML file was the only way of getting an HTML file generated.

Both now fixed. On save export will overwrite the html file regardless of timestamps. I'll be making another EAP today and will put the fix in it. 

BTW, the last EAP 2.1.1.42 has awesome typing response even with the preview on. I found the "undocumented feature" in JavaFX WebView that was causing huge rendering delays, affected scrolling of the preview and slowed down typing response. You will feel the difference when you get the fix for this bug.

**Comment by vsch** [comment]
@bstout, EAP 2.1.1.44 out with the fix for this issue and a whole bunch of others.

**Comment by vsch** [comment]
@bstout, sorry for the trouble but don't use 2.1.1.44 it has broken export through over-optimization.

I will post a fix shortly.

**Comment by vsch** [comment]
@bstout, fixed and improved. Added a Re-Export action that will export ignoring modification time stamp. EAP 2.1.1.46
