### ISSUE TITLE
Drag and drop image support

### ISSUE THREAD

**Issue by yunti** [vsch/idea-multimarkdown#342]
This doesn't seem to be currently supported from a quick test and I'm not sure if this is possible within the confines of intellij platform, but having drag and drop support for images as can be done in github would be a big improvement to help speeding up a workflow where images are needed in markdown.
  
Perhaps it can be implemented via: drag file from project folder in intellij file explorer tree to markdown file to automatically link etc...  
Or if that's not possible, added to the context menu of a file with a 'add to markdown' option, which inserts image at current cursor location.

**Comment by vsch** [comment]
@yunti, it has been on my to do list for a while. I haven't gotten around to figuring out the drag drop handling but will soon. I will also add similar feature to what [Paste Images into Markdown](https://plugins.jetbrains.com/plugin/8446?pr=idea) plugin does. With a bit more configuration flexibility based on the plugin rendering profiles to allow intelligent placement based on scope of which document it is dropped into.

Another feature for after the next release but very soon.

**Comment by yunti** [comment]
From the clipboard with a configurable folder is probably even better, than having to prepare the files.   

Anyway that’s the last of my big requests.  Thanks for your work.

**Comment by vsch** [comment]
@yunti, please don't stop the requests big, small and in between.

It is users like you who let me know of what gets in their way or what would make their life easier that make the plugin better for everyone, including me.

A request that is difficult or I don't know how to implement will wait for more favourable conditions, but in the end most get implemented. 

So please don't stop the requests or pointing out any issue you experience with the plugin.

**Comment by yunti** [comment]
@vsch  :)

**Comment by vsch** [comment]
@yunti, Drag/Drop file from project tree to insert link is implemented in EAP 2.3.3.4.

* Add: File drag and drop into markdown document to create links, image files create image links
  the rest create inline links. Each file link will be added as a separately undoable command.

  If copy dragging images (Ctrl on Linux/Windows, ⌥ on OS X) then for image files the `Copy
  Image` dialog will open (like paste image) that will allow you to modify the image and choose
  the location where to store the copy. Copy drag mode has no effect on other files and is
  ignored.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by yunti** [comment]
thansk I'll take a look,  will copy and paste image from clipboard work too? I often use the screenshot tool on osx.  Would this use the same dialogue for as for copy image to specify where to save the file?
