### ISSUE TITLE
Stops rendering on PHPStorm

### ISSUE THREAD

**Issue by jimlongo56** [vsch/idea-multimarkdown#347]
All of a sudden stopped rendering HTML view.  
HTML tab is not present. Split pane or HTML View button (top right of toolbar) render a white page.
Happens on all markdown documents.

#PS-163.7743.50 on Mac OS 10.12.1 

Note icon in plugin list doesn't look like the rest.
![screen shot 2016-12-06 at 12 39 36 pm](https://cloud.githubusercontent.com/assets/6787988/20936585/1d90de6e-bbb1-11e6-96a0-97fee3c16a6b.png)

Have uninstalled, invalidated cache, reinstalled from disk.  No luck.
Thank you.

**Comment by vsch** [comment]
@jimlongo56, 

1. the tab views were removed  in the last release. 

2. The plugin Icon does not look like the reset because it is a third party plugin the rest are JetBrains plugins so they are marked with the JetBrains logo.

3. Probably settings issue from upgrading, Go into Languages & Frameworks > Markdown > Preview, select the preview browser other than what is there. Ok. Go back and switch the preview browser back to what you had before.

    This will reset the settings for the new version. I suspect there is something missing from settings that is not addressed after an upgrade.

Please let me know if the issue was resolved.

**Comment by jimlongo56** [comment]
Thanks for the prompt response.
It took a few toggles back and forth, and toggle Default editor layout and preview type, but it is rendering as usual now.

**Comment by vsch** [comment]
@jimlongo56, then the toggling of the Default editor layout did it. I have to check the code, I suspect that with some combination of settings of default layout and saved editor state the pane is blank.

I'll reopen this issue to help remind me that there is a bug.
