### ISSUE TITLE
Support Gitbook Header IDs

### ISSUE THREAD

**Issue by bkimminich** [vsch/idea-multimarkdown#351]
Gitbook markdown allows a special syntax for Header IDs to link easily between chapters of a book split into different files:

> GitBook supports a nice way for explicitly setting the header ID. If you follow the header text with an opening curly bracket (separated from the text with a least one space), a hash, the ID and a closing curly bracket, the ID is set on the header. If you use the trailing hash feature of atx style headers, the header ID has to go after the trailing hashes. For example:
```
Hello {#id}
-----

# Hello {#id}

# Hello # {#id}
```

---

There are two issues with this:

#### Markdown Navigator renders the ID in the preview

![image](https://cloud.githubusercontent.com/assets/3531020/21233526/bdd67146-c2ef-11e6-806a-c32ba94faf9e.png)

#### Even with the GitBook parser profile the anchors do not work

![image](https://cloud.githubusercontent.com/assets/3531020/21233553/d4da0e66-c2ef-11e6-898c-7fd91eb3b3fb.png)

---

If you need live code examples to test this:

* Preview issue: https://github.com/bkimminich/pwning-juice-shop/blob/master/part2/score-board.md#find-the-carefully-hidden-score-board-page-scoreboardchallenge
* Anchor issue: https://github.com/bkimminich/pwning-juice-shop/blob/master/part2/README.md

**Comment by vsch** [comment]
Hi Björn,

In the current release, Markdown Navigator only uses the GitBook profile to change the encoding of URLs to be GitBook compatible.

Adding of GitBook attribute processing directive is on the parser’s to do list. I should have it implemented for next major release scheduled for Jan 2017. It is needed for proper Jekyll support and for non-github processing when an attribute of the generated HTML needs to be specified. I can see a lot of uses for this.

I agree that having an id independent of the heading text is much easier to work with and I will add it ASAP, but until it is implemented, Markdown Navigator’s id generation for headers is compatible with GitBook’s id generation without the directive. You can use auto-completions when the caret is after the # in a link to get a list of all headers in the file.

The only real discomfort is that you should not just edit the text of the heading but Refactor Rename it so that all links with anchor refs to the header will also be renamed in the process. I have a short animation of using Table of Contents and Links with Ref Anchors to Headings, in case you are not familiar with this functionality of the plugin: https://raw.githubusercontent.com/vsch/idea-multimarkdown/master/assets/images/noload/TOCDemo.gif <https://raw.githubusercontent.com/vsch/idea-multimarkdown/master/assets/images/noload/TOCDemo.gif>
I am also looking into automatically offering to rename the ref anchors if the heading text is edited to make it more convenient. I myself forget to use rename and have to undo the text changes so I can rename. It is a PITA and I will be addressing this too.

Once the id attribute parsing is implemented I will add a quick fix to headings that will offer to add the “fixed id” and rename all existing anchor refs to this new id. So if you use the automatically generated id for now, you will have a quick way of changing to the fixed {#id} syntax once it is implemented.

If you have any other suggestions or annoyances with using the plugin for GitBook please let me know. I want the plugin to be as comfortable for GitBook as it can possibly be and would like you to let me know of anything big, small or in between, that gets in the way of achieving this.

Best regards,



Vladimir.

**Comment by bkimminich** [comment]
I switched to heading-based anchors in my GitBook for now. Works like a charm thanks to the plugin's code-completion!

**Comment by vsch** [comment]
@bkimminich, you might find the new feature in the latest EAP useful. It is state persistence for GitHub Collapse Markdown script in Languages & Frameworks > Markdown > Stylesheet. This script converts all headings in preview into collapsible sections.

The latest EAP allows you to collapse/expand headings and persists the collapsed state across preview refreshes on document edit and file open/close actions.

Holding the SHIFT key when clicking on a heading in preview will collapse/expand all heading of the same level, without the shift key only toggle the state for the heading that you click on.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by vsch** [comment]
@bkimminich, latest EAP has attributes extension in parser settings. Enabling it will add attributes element parsing which includes the `{#id}` type. You need to enable this option in Languages & Frameworks > Markdown > Parser

Also added add/remove explicit id from headings intentions. Removing a custom id will first rename the explicit id to the default id then remove it. That way if you have any anchors referencing the custom id they will be renamed to the heading's default id.

To create a custom id first use the intention to create an explicit id then rename it to one you want.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
