### ISSUE TITLE
First open of existing markdown document causes crash

### ISSUE THREAD

**Issue by dave-irvine** [vsch/idea-multimarkdown#357]
I've tried this a couple of times to be sure, but here are the replication steps:

1. In a Project, add a new Markdown file and edit it (this works fine).
2. Add content to the Markdown file and save.
3. Close the Markdown file and quit the IDE.
4. Re-open the IDE and try to open the Markdown file: crash.

Workaround:

1. After opening the IDE for the first time, create a new Markdown file and edit it.
2. You can now open any existing Markdown file.

Platform: OSX. IDE: WebStorm. Plugin: v2.3.0 Enhanced.

**Comment by vsch** [comment]
@dave-irvine, can you please attach the exception stack trace or even better if you could make the log file available. You can get the log file under the Help menu > Show Log in Finder. You can send me a dropbox link to my e-mail address given in my profile https://github.com/vsch

I tried to duplicate the crash using your steps and not able to do it so I suspect there are some other conditions needed for this. The stack trace or the log will give me more information to duplicate and debug the issue.

**Comment by dave-irvine** [comment]
@vsch Hi! Once the IDE crashes it makes a new threadDump every second or so.

https://gist.github.com/dave-irvine/29bf156be334028988a99f5525dfb7ad

Hope this helps!

**Comment by vsch** [comment]
@dave-irvine, thank you. I will take care of it ASAP.

**Comment by vsch** [comment]
@dave-irvine, it appears to be having a problem initializing JavaFX but I cannot tell from the thread dump, I think the log file would have the actual stack trace of the crash which would show where it is failing. If you could make the exception stack trace available it would help.

As a workaround can you try disabling the JavaFX WebView browser by setting preview broswser to default - Swing?

![screenshot_settings_previewbrowser](https://cloud.githubusercontent.com/assets/10299086/21810497/135c6876-d71a-11e6-8017-74647b3db215.png)

**Comment by dave-irvine** [comment]
@vsch Changing to Swing prevents the issue, so that's a good workaround for now :)

As for the log file, I've deleted all files, started the IDE. This creates idea.log, but once the crash occurs nothing goes into it.

If I Force Quit WebStorm I can get you the stack trace from the Apple error reporting tool if that would help?

**Comment by dave-irvine** [comment]
@vsch Got it :) It only crashes when I have [Flexiglass](https://www.nulana.com/flexiglass/) open. I'm not sure if there is anything you are going to be able to do about the crash.

I'll have to see if I can find another tool to do window arranging on my Mac :)

**Comment by vsch** [comment]
@dave-irvine, what I find interesting is that if you create a new file then open an existing file it works without a problem. If you don't do this step and try to open an existing file it plants. This could be timing issue but it is hard to say without knowing where it hangs, because the repeated thread dumps point to a deadlock issue. It also could be the reason that nothing is added to the log once this occurs.

When you said crash, do you mean a Java Exception in the IDE or an IDE crash in OS X? The former I can address, the latter points to a JavaFX issue that could be related to: [IDE hanged after I've opened markdown file](https://youtrack.jetbrains.com/issue/RUBY-18230) which is not limited to RUBY but applies to all IDEs with specific hardware/OS X version/JDK combinations. It happens in the native libraries for JavaFX.

**Comment by dave-irvine** [comment]
Done, BetterTouchTool supports what I need, and now that Flexiglass isn't running, Multimarkdown runs *way* faster!

Thanks for your help @vsch :)

**Comment by vsch** [comment]
@dave-irvine, make sense since Flexiglass affects rendering which JavaFX is sensitive to. Glad your issue is resolved.
