### ISSUE TITLE
"Unresolved link reference" errors

### ISSUE THREAD

**Issue by bkimminich** [vsch/idea-multimarkdown#358]
I get several `Unresolved link reference` errors in my markdown which seem strange, because they all are existing links.

Examples that do not work:
* :red_circle: `![Juice Shop Architecture](https://github.com/bkimminich/juice-shop/blob/gh-pages/assets/Architektur_JuiceShop.png?raw=true)`
* :red_circle: `![Juice Shop Architecture](https://raw.githubusercontent.com/bkimminich/juice-shop/gh-pages/assets/Architektur_JuiceShop.png)`
* :red_circle: `[GitHub release](https://github.com/bkimminich/juice-shop/releases/latest)`

but

* :green_heart: `![Juice Shop Logo](https://raw.githubusercontent.com/bkimminich/juice-shop/master/app/public/images/JuiceShop_Logo.png)`

**Comment by vsch** [comment]
@bkimminich, the plugin does not check the actual http: or https: link but uses the github.com prefix and the user/project to see if the link is part of one of the project's GitHub VCS roots. Here it gets confused by the `gh-pages` and `releases` part because it expects a branch name.

I will add `gh-pages` and `releases` to built-in "branch" equivalents that are ignored so that no unresolved highlighting will appear on these.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
