### ISSUE TITLE
Performance problems when MultiMarkdown enabled

### ISSUE THREAD

**Issue by VladRassokhin** [vsch/idea-multimarkdown#36]
Even when .md file is not open, IDEA 15 EAP sometimes hangs on my Mac.
See profiler screenshot at the 'moment' of hang: https://yadi.sk/i/3JBCHCe_jPPYs

**Comment by VladRassokhin** [comment]
Also link to YourKit snapshot: https://yadi.sk/d/C5j8RVN8jPPbL
Looks like something is quite non-optimal around:
```
Executors.java:439 com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$MainFileList$1.run() 47159 74
  MultiMarkdownProjectComponent.java:208 com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(Runnable) 47159 74
    ApplicationImpl.java:937 com.vladsch.idea.multimarkdown.MultiMarkdownProjectComponent$MainFileList$1$1.run() 47159 74

**Comment by vsch** [comment]
@VladRassokhin, thank you for the bug report. I too noticed that under some conditions it goes into a runaway resource and CPU hog. It happens in the project component of the plugin, so no files need to be opened for this. Since the IDEA parses files in the background to update references and indexes.

I am reworking this section of code at this moment. This code has 3 issues related to it so it is on the critical priority list. The new version which should be out in a day or so and will not have these issues.

**Comment by VladRassokhin** [comment]
Ok, thanks for quick response.

**Comment by vsch** [comment]
@VladRassokhin, New build available in this repo under dist or from the JetBrains Plugin Page or Repository.
