### ISSUE TITLE
Auto-formatting creates list by accident

### ISSUE THREAD

**Issue by bkimminich** [vsch/idea-multimarkdown#360]
Another one for the gallery of unlucky coincidents... 🖼 

## Before auto-formatting
![image](https://cloud.githubusercontent.com/assets/3531020/21829542/e5d81558-d796-11e6-9170-d502b1985c3e.png)

## After auto-formatting
![image](https://cloud.githubusercontent.com/assets/3531020/21829546/f2d1ab02-d796-11e6-9473-7d8aaeef8c68.png)

### Another auto-format later...
![image](https://cloud.githubusercontent.com/assets/3531020/21829591/503a1716-d797-11e6-84e5-034b4437fe65.png)

**Comment by bkimminich** [comment]
## Workaround

![image](https://cloud.githubusercontent.com/assets/3531020/21829631/91536b80-d797-11e6-9809-34a3a2bfbb6c.png)

**Comment by vsch** [comment]
@bkimminich, it is an issue that I will address soon. In the case of numbered lists it is a plugin issue. I need to disable auto-list formatting when a numbered item needs a blank line before to be recognized by the processor. Bullet lists are actually recognized by GitHub and GitBook. 

What I have on the todo list is to escape the marker when it reflows to start of line and remove it when it migrates away from start of line.

A workaround is to escape with `\` the `.` after number and before `*`, `+` or `-`.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

* Fix: #360, Auto-formatting creates list by accident, added two code style settings for text  wrapping options for `Special Characters` which are `*+-:~` and digits followed by `.` (or `)`  for CommonMark), enabled by default:
  * `Escape when wrapped to start of line`
  * `Unescape when wrapped away from start of line`


![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by vsch** [comment]
@bkimminich, I forgot to add `>` to the special characters to prevent accidental block quotes. I will add it to the next release.
