### ISSUE TITLE
Feature request: image url offsets

### ISSUE THREAD

**Issue by spyhunter99** [vsch/idea-multimarkdown#364]
I'm on a maven project editing site documentation in markdown.

The markdown is located here:
`src/site/markdown`

Images are located here:
`src/site/resources/images/`

And they are referenced like this in the markdown
`<img src=images/something.png>`

When maven does it's magic, it renders the site markdown into html and puts it all in the right locations so that the images resolve fine. The magic part take forever and a day to run so the Markdown plugin is great! The problem is that the images aren't resolving because it's pointing to the wrong folder. Would it be possible to add some kind of configuration or a non-renderable tag or something to state an alternate path or a prefix to add to image tags for rendering the preview in intellj/android studio?

**Comment by vsch** [comment]
@spyhunter99, do you mean that you are using HTML img tags in markdown to reference images in Markdown, not the Markdown image element `![]()`?

Because if you are using Markdown image elements you can use Link Map configuration to do the mapping which would resolve the images in preview, annotate missing images and make completions resolve to the right link.

In Markdown HTML is passed through as is and it is the preview browser that would resolve the image links.

I can take a look and see if an option in preview to use Link Map configuration to map img tag src when the HTML is prepared for preview would give a workable solution. It would not give you completions or annotations for these but would allow any img src attribute that starts with `image/` to be changed to any other prefix so that it would resolve by the preview browser. You would need to map it to a URI prefix like `file://` followed by an absolute path to the image directory.

Since the Link Map configuration is a project level, this would mean that everyone who works on the project in IDEA would need to have their own unique mapping based on their project location and Markdown Navigator project settings in .idea/markdown-navigator.xml cannot be shared.

**Comment by spyhunter99** [comment]
@vsch yes i'm using html img tag, but i can convert to the markdown syntax. I found the "Link Map" and I just found the wiki article on it. I'll read on and ping you if i have further questions, thanks!

**Comment by spyhunter99** [comment]
@vsch ok so here's what i have. This is a "Link Ref Element"

File reference pattern, prefix is "images/"
To Element text, i've tried the following
 - file:///projects/xyz/src/site/resources/images
 - /src/site/resources/images
 - file://c:/projects/xyz/src/site/resources/images

In all 3 cases isn't not working. The generated html for the preview window still shows `images/something.png`

In the markdown file, it's listed as 
![something](images/something.png]

**Comment by vsch** [comment]
@spyhunter99, here is what I used on a sample project. The caveat is that the project needs to be under Git VCS. The plugin uses Git for repo relative link resolution. Also for completions you need to invoke the completion twice to switch completions to repo relative `/src/...` link format. That way completion will be changed to `images/...`

![sampleimagemap](https://cloud.githubusercontent.com/assets/10299086/21967451/8ee76970-db55-11e6-9325-d6fefd7d1cdb.gif)

<img width="1090" alt="screen shot 2017-01-15 at 6 55 11 pm" src="https://cloud.githubusercontent.com/assets/10299086/21967413/8601c946-db54-11e6-97a0-a2a25efd4f47.png">

<img width="909" alt="screen shot 2017-01-15 at 6 55 51 pm" src="https://cloud.githubusercontent.com/assets/10299086/21967414/8891a5f0-db54-11e6-8094-d9c79be50212.png">

**Comment by spyhunter99** [comment]
interesting, autocomplete isn't working in this context for me. I do get the popup but it just says "No suggestions". windows 10 with 16.3.2 community.

i can get realtive links in the markdown (../resources/images/something.png) to render, but even after applying your screen shots, it's still not working. Could it perhaps be a version difference?

**Comment by vsch** [comment]
@spyhunter99, I tried it on Windows XP but with a latest plugin. Are you using version 2.3.0? I can release an EAP of the latest that I used for the test to see maybe it is some fix affecting it. I will post a link here.

For Autocomplete you need invoke it twice (hit the auto complete key twice) to switch to repo relative format '/...' and for images it has to be image links `![]()` to make it look for image files.

Is the project under git VCS? because the plugin uses this to resolve repository relative link addresses. It will not work without git, even if the git vcs is just an empty just initialized repository.

I don't have Windows 10 but the main difference is path separator and the device prefix on the path so Window XP and Windows 10 are the same in this respect.

**Comment by vsch** [comment]
@spyhunter99, new EAP released. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by spyhunter99** [comment]
It is a git repo. 2.3.0.10 is now installed same deal :(

**Comment by vsch** [comment]
@spyhunter99, can you post screenshot of your link map config so I can double check it. Maybe something is missing. 

1. Is it a single VCS root project or multi-root project? Each VCS root resolves repo relative links relative to its root.

I will try to think of what else could be affecting it in the project configuration.

**Comment by spyhunter99** [comment]
single git repo, no sub modules or any other VCS in place. screener coming

**Comment by spyhunter99** [comment]
![markdown3](https://cloud.githubusercontent.com/assets/1975321/21968253/a5907ed6-db60-11e6-8978-64bf7cf4ec01.PNG)
![markdown issue1](https://cloud.githubusercontent.com/assets/1975321/21968251/a58d664c-db60-11e6-86b0-19b1fcf4f3f6.PNG)
![markdown2](https://cloud.githubusercontent.com/assets/1975321/21968252/a58f69d8-db60-11e6-93cc-e64bc5fad315.PNG)

**Comment by vsch** [comment]
@spyhunter99, I see nothing wrong. I uploaded my test project. Can you download it and unzip it then open it and see if it is working. It will at least allow us to see if it is system related or project config.

https://github.com/vsch/idea-multimarkdown/raw/master/assets/site-sample.zip

**Comment by spyhunter99** [comment]
it's different. 
![image](https://cloud.githubusercontent.com/assets/1975321/21968357/dc773d9e-db61-11e6-9384-304372210636.png)

**Comment by spyhunter99** [comment]
oh hang on

**Comment by vsch** [comment]
@spyhunter99, just realized that you have the basic version and this functionality requires enhanced features because it needs the AST tree parsing for the full markdown: Get a trial license https://vladsch.com/product/markdown-navigator/try and it should work.

**Comment by vsch** [comment]
@spyhunter99, I am curious if the solution worked for you?

**Comment by spyhunter99** [comment]
yup that did it. thanks
