### ISSUE TITLE
Leading space on second-level headings not supported on nth heading.

### ISSUE THREAD

**Issue by dotancohen** [vsch/idea-multimarkdown#375]
When using line-style headings, all but the first second level heading are not recognized with leading spaces.

```
First level heading
==========

 Second level heading
----------
Foo for:

* bar
* baz

 Another second level heading
-----------------

The foo has barred.
```

Note that the last heading is _not_ properly parsed as a heading in Markdown Navigator.

**Comment by dotancohen** [comment]
First level heading
==========

 Second level heading
----------
Foo for:

* bar
* baz

 Another second level heading
-----------------

The foo has barred.

**Comment by vsch** [comment]
@dotancohen, thank you for for the catch. I am assuming that you have the parser set for "GitHub" document compatibility since this is the only setting that exhibits this behaviour.

I will address it in [flexmark-java](https://github.com/vsch/flexmark-java#-flexmark-java) the parser used for the plugin.

The issue is the indent on the heading text that makes the heading a child element of the `baz` list item but the heading marker line is not indented so it is treated as a thematic break in the document. The idiosyncrasies of GitHub parsing are many and numerous.

**Comment by dotancohen** [comment]
Note that the Github issue tracker does in fact parse the code correctly:

First level heading
==========

 Second level heading
----------
Foo for:

* bar
* baz

 Another second level heading
-----------------

The foo has barred.

**Comment by vsch** [comment]
@dotancohen, GitHub comments in issues and pull requests are CommonMark, GitHub Documents are GFM which is a bastardized version of original Markdown. CommonMark has no issues with the input and if you set the parser to CommonMark it will work.

The problem with GitHub doc emulation is that it is awkward to accomplish with CommonMark based parser architecture which is geared towards standard processing rules.

GitHub Doc parses your markdown as:

```html
<ul>
    <li>
        <p>baz</p>
        <h2 id="second-level-heading">Second level heading</h2>
    </li>
</ul>
```

<ul>
    <li>
        <p>baz</p>
        <h2 id="second-level-heading">Second level heading</h2>
    </li>
</ul>

while commonmark parses it as:

```html
<ul>
    <li>
        <p>baz</p>
    </li>
</ul>
<h2 id="second-level-heading">Second level heading</h2>
```

<ul>
    <li>
        <p>baz</p>
    </li>
</ul>
<h2 id="second-level-heading">Second level heading</h2>


It is very difficult to make the parser handle this idiosyncrasy without chewing it up and introducing performance impact. In the end the markdown you are using is not giving you what you are expecting, which is the heading in the document instead of a heading in a list item.

The workaround is to switch to CommonMark profile or to add a space in front of the Setext heading marker so that it is considered as part of the list item and not a thematic break.

```markdown
* baz

 Second level heading
 ---------------------
```

To change parser profile to CommonMark and you will get GitHub comment mode:

![screenshot_parser_lists](https://cloud.githubusercontent.com/assets/10299086/22426836/de397e9e-e6ce-11e6-9389-500233a107a1.png)

**Comment by dotancohen** [comment]
Thank you, I can work around the bug using CommonMark.

On which upstream library should I file the bug? I've looked through the `lib` directory but don't see anything relevant. Thanks.

**Comment by vsch** [comment]
@dotancohen, I already opened a bug but it will not be fixed because it is idiosyncratic of the GitHub processor that affects de-normalized markdown formatting. https://github.com/vsch/flexmark-java/issues/51

**Comment by vsch** [comment]
@dotancohen, to see how different markdown processors handle this input go to http://johnmacfarlane.net/babelmark2/?normalize=1&text=*+baz%0A%0A+Second+level+heading%0A---------------------

Only one, Black Friday, processes it like GitHub. The rest either handle it like commonmark or like flexmark-java handles it when set to GitHub.

**Comment by vsch** [comment]
@dotancohen, GitHub recently changed its document processing to CommonMark so this is no longer an issue.

**Comment by dotancohen** [comment]
Terrific, thanks for keeping up. I need to build the latest Markdown Navigator and I'll mark this as closed as soon as I've built and tested.

Thank you.
