### ISSUE TITLE
Poor alignment between source and preview when using "Sync source to preview"

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#398]
It a perfect world they would be vertically aligned, but in our world it's _just_ ;-) :
![image](https://cloud.githubusercontent.com/assets/200952/23454163/b6380a64-fe6b-11e6-9799-bb6c907d79ce.png)

So still a lot of manual by-eye preview scanning is needed to find the caret position in the preview.

**Comment by vsch** [comment]
@holgerbrandl, thank you for stimulating me to make improvements. I love it.

I will add an option, enabled by default, to align (as much as possible) the editor caret vertical position and the highlight in preview. I think it is a great idea.

**Comment by vsch** [comment]
Now there is an option to vertically align synchronized position in Preview Settings, selected by  default.

![verticalalignscroll](https://cloud.githubusercontent.com/assets/10299086/23477725/eae6dd3c-fe8c-11e6-9099-9853e55f1362.gif)

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by holgerbrandl** [comment]
It's a great addition to the plugin and works pretty well already.

A minor improvement (actually it's a bug imho) would be to also sync the position if a user clicks in the preview to jump back to the editor (aka "Synchronize source to preview on click"). Currently the caret to preview synchronicity is lost when doing so.

**Comment by vsch** [comment]
@holgerbrandl, clicking in preview moves the caret in source to the line and then aligns the preview to position in source. Here is the preview to source sync by clicking in preview:

![verticalalignscroll2](https://cloud.githubusercontent.com/assets/10299086/23506989/f7ce7fe6-ff18-11e6-8ec2-adc9f4d3d9fc.gif)

What are you seeing when clicking in preview?

**Comment by holgerbrandl** [comment]
1. Clicking in the preview scrolls the preview, which feels odd (why would/should it?). If possible the preview should keep its scroll position when being clicked.
2. content seems always properly aligned on preview clicks when "highlight preview element" is set to "line" but fails to align correctly in 1 of 20 clicks when using "block" or "line". That's at least how I perceive it.

I'd think that (1) has a much greater impact on usability than (2).

**Comment by vsch** [comment]
@holgerbrandl, clicking in preview moves the caret in the document. Because the option to vertically align source and preview caret position is set this in turn causes the preview to scroll.

If I can figure out how to handle it without creating a state machine hell in the code I will prevent the preview scroll right after a preview click caret move but all these things happen asynchronously on both sides, the source editor and the preview. So just adding a few flags won't do it without introducing a bunch of potential bugs.

If the vertical alignment option is turned off then the preview will not be scrolled.

**Comment by holgerbrandl** [comment]
Indeed it's a state machine problem for which there is no easy solution I guess. Even so, the improved preview alignment is a great improvement, I was just getting picky. :-)

**Comment by vsch** [comment]
@holgerbrandl, the state machine I could handle. Here there is the async issues and the fact that you think you are looking at a preview page but every doc change and now selection or search change loads a new page as far as JavaFX is concerned. I have to try and make it display after load as exact as I can the way it was displayed last so you don't notice the reload.

To add to the problems, not everything is available when the page loads since I can only set the bridge class that lets JS access Java after the page loads. By that time it is already displayed. I go through hoops embedding minimal JS data in the HTML so the page can display as it did the last update.

Finding where the glitches come from is a PITA, all async and I have to dig through piles of logs.
