### ISSUE TITLE
Reformat Document margin

### ISSUE THREAD

**Issue by bstout** [vsch/idea-multimarkdown#405]
Perhaps I'm missing the setting - the nice feature I just discovered to reformat the .md doc looks to wrap the text at column 73.  I see in IJ for code style the margin I have set to 120 so it must be pulling this value of 73 from somewhere else.

I'd like to reformat the doc, but not have the lines chopped too narrow.

**Comment by vsch** [comment]
@bstout, Format documentation is found in
[Document-Format-Options](https://github.com/vsch/idea-multimarkdown/wiki/Document-Format-Options)

Markdown has its own margin by default since it is highly likely that you do not want the same
margin setting for documentation as code. If you want the IDE right margin to apply to Markdown
documents select `default` under `Right margin`:

Another thing to consider is what wrap on typing and text wrap should do when soft wraps are
enabled in the document. For that you have `disabled if soft wraps` for `Wrap on typing` and the
selection under `Text` for `When soft wrap is enabled`.

![Screenshot_CodeStyle](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_CodeStyle.png)

You also have the option of `Soft wraps` wrapping at the right margin instead of the right edge
of the editor window by selecting `Soft wrap at right margin`:

![Screenshot_Main_licensed](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Main_licensed.png)
