### ISSUE TITLE
2.3.4 Breaks drag and drop of text

### ISSUE THREAD

**Issue by larvanitis** [vsch/idea-multimarkdown#406]
Since updating to the latest version of Markdown Navigator, when I drag and drop some text:

1. The selection disappears, as expected
2. The text does not appear where I drop it, like it should

This leads to lost text.

See https://youtrack.jetbrains.com/issue/IDEA-168934 for the original report.

PS. Disabling this plugin fixes it.

**Comment by vsch** [comment]
@larvanitis, thank you for the report. I will make a fix and post an EAP plugin release with the fix.

**Comment by SmedbergM** [comment]
+1

**Comment by vsch** [comment]
The issue turned out to be an assumption in the IDE editor implementation about what other interfaces are implemented by the PasteHandler. Oops. Extra interface implemented and bug fixed.

This release also has file drag/drop from project tree to markdown document to create links. Copy drop action (Ctrl or Mac Alt) only available when `Replace Editor Drag and Drop Handler` (disabled by default) is enabled but will disable text drag and drop in markdown. No API to have extensions for drop handling with information about the drop action so you can only have extra action on "Copy" drop or text drag/drop for now.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
