### ISSUE TITLE
New lines inside code fence breaks formatting

### ISSUE THREAD

**Issue by cloakedninjas** [vsch/idea-multimarkdown#41]
This works:

```
var bar = 1;
var foo = 2;
```

This fails:

```
var bar = 1;

var foo = 2;
```

HTML preview looks like this:
![screen shot 2015-10-05 at 14 44 51](https://cloud.githubusercontent.com/assets/1395013/10281931/bfa63fe8-6b6f-11e5-9a39-13689e6c7973.png)

**Comment by vsch** [comment]
Code fence must be on a line by itself. Even though you use triple back ticks it is still just an inline code marker. When you insert a blank line you end the block and get just triple ticks which are treated as text because they are not matched within the same block.

**Comment by cloakedninjas** [comment]
I see, well good to know.

But there's probably a case for making the preview appear as it does on Bitbucket or GitHub, which does support line breaks inside code fences - no?

**Comment by vsch** [comment]
You misunderstood what I said. Your example is not code fence but inline code. 

To make it code fence put the triple back ticks on a line by itself. You put your text right after the opening back ticks, which makes them not code fence but inline code. Code fence:

     ```
     var abc


     var def
     ```

**Comment by cloakedninjas** [comment]
Erm, I am doing. Here's a screenshot from the Text panel

![screen shot 2015-10-06 at 10 48 57](https://cloud.githubusercontent.com/assets/1395013/10305428/f77ca008-6c17-11e5-820d-256e88921329.png)

Am I missing something?

**Comment by vsch** [comment]
Sorry, I misunderstood because I looked at the HTML preview  and it had the back ticks followed by code.

I can't duplicate this. Is there something that comes before the first code fence? What version of the plugin are you using? (The parser code hasn't changed in ages, but I want to duplicate this and every  little bit helps).

Here is what I get when I type it the segment you have in your screenshot:

Text:
<img width="247" alt="screen shot 2015-10-06 at 6 34 29 am" src="https://cloud.githubusercontent.com/assets/10299086/10306348/69ba5dbe-6bf4-11e5-8ac1-314cdfd04381.png">

HTML Preview (JavaFX WebView):
<img width="627" alt="screen shot 2015-10-06 at 6 34 42 am" src="https://cloud.githubusercontent.com/assets/10299086/10306350/73c988fc-6bf4-11e5-93de-802621b15a71.png">

HTML Preview (Swing HTMLEditorKit):
<img width="354" alt="screen shot 2015-10-06 at 6 37 30 am" src="https://cloud.githubusercontent.com/assets/10299086/10306405/cff0f624-6bf4-11e5-96ec-69f581b928e1.png">

**Comment by cloakedninjas** [comment]
I'm using v1.1.11 on WebStorm 10.0.4 on a Mac.

It's happening for existing .md files as well as test files with just that code block. I've tried reinstalling the plugin and ensured there weren't any other Markdown plugins installed. No joy.

If I figure out what's causing it, I'll update this issue.

**Comment by vsch** [comment]
I think I figured it out. Go into <kbd>Settings > Other Settings > MultiMarkdown > Markdown Extensions</kbd> and make sure `Fenced Code Blocks` is selected. Fenced code blocks is an extension to the original markdown which you can turn off in settings.

<img width="1169" alt="screen shot 2015-10-06 at 7 02 50 am" src="https://cloud.githubusercontent.com/assets/10299086/10306916/51b6755a-6bf8-11e5-923a-5319c0040a9a.png">

**Comment by cloakedninjas** [comment]
:+1: Nice - that sorted it
