### ISSUE TITLE
Scrolling Issue after swtiching from split view to preview

### ISSUE THREAD

**Issue by Javaru** [vsch/idea-multimarkdown#429]
(v2.3.5.6 on v2017.1.2 EAP build #IU-171.3780.107)
I was editing a document in split view. After Switching to "Show Preview Only", the screen did switch to the preview, but when I scrolled, the document preview view was split down the middle with only the left side scrolling.  I'm using the JavaFX WebView with a "Default preview type of "HTML Preview"

![image](https://cloud.githubusercontent.com/assets/2196944/25058043/97da5752-2143-11e7-96f1-5ed5512f4d1d.png)

**Comment by Javaru** [comment]
Note that the issue went away after a restart of IDEA. So its hard to know what sequence of events lead to the issue. Intermittent bugs are so much "fun" :(  If I find any way to reliably reproduce it, I'll let you know.

**Comment by vsch** [comment]
@Javaru, it appears to be some timing issue in JavaFX WebView. I have encountered it a few times and it would go away after turning off preview and turning it on again and modifying the file so the preview is refreshed. I think it happens if the preview size is modified while an update is in progress.
