### ISSUE TITLE
HTML Preview cannot preview correct

### ISSUE THREAD

**Issue by vitojeng** [vsch/idea-multimarkdown#43]
There are something wrong when HTML preview.

Reproduce step:
* Open any markdown file(ex: README.md), and preview result of tab 'HTML Preview' is correct first time.
<img width="877" alt="screenshot 2015-10-07 at 13 49 26" src="https://cloud.githubusercontent.com/assets/475186/10329994/86110164-6cfa-11e5-9251-48ec9a311123.png">

* Switch to 'Text' tab and then click 'HTML Preview' again, the result have something wrong.
<img width="876" alt="screenshot 2015-10-07 at 13 49 54" src="https://cloud.githubusercontent.com/assets/475186/10329993/860fd5d2-6cfa-11e5-9297-b9f11169e1d4.png">

Version:
Intellij IDEA 14, community edition
MultiMarkdown 1.1.12

**Comment by vsch** [comment]
@vitojeng thanks for letting me know. This looks like a WebView issue. 

What JRE are you running the IDEA on?

Can you give me a link to the README.md file that is causing this or is it for all markdown files on your system?

If it is for all markdown files then you should disable the JavaFX WebView preview by selecting the 'Use Old Preview' check box in <kbd>Settings > Other Settings > MultiMarkdown > General</kbd> so that the old and trusty swing HTMLEditorKit based preview is used, at least until I can duplicate this so I can debug it.

**Comment by vitojeng** [comment]
Thanks for quickly response.

* IDEA run on JRE 1.8.0_25
* You can get README.md file from here
  * Apache Spark's download page: https://spark.apache.org/downloads.html
  * Spark release: 1.4.0
  * package type: Pre-build for Hadoop 2.4
* Not only this one. Many project's markdown files have the same issue.

**Comment by vsch** [comment]
I tried it and no problems with the spark readme.md file. 

It is a JavaFX issue. WebView is very finicky. Before giving up on JavaFX disable highlight.js option in settings to minimize what WebView can fail to process. Other than that if you can try a JRE 1.8.0u_51 or later. I found that WebView on 51 is most compatible, at least on OS X  but it is a trial and error ordeal.

Otherwise, the only solution I know of is to disable the JavaFX preview and use the swing one by selecting 'Use Old Preview' in settings. It is not as pretty but much faster and does not have all the JRE dependencies. Will run on 1.6 and work with IDEA builds as far back as 133.1711, which is IDEA 13.

**Comment by vitojeng** [comment]
Great. After upgrade to Java SE 8u65, everything work well.
Thank you !

**Comment by vsch** [comment]
My pleasure.
