### ISSUE TITLE
Support external links for the Link Map (eg. JIRA link)

### ISSUE THREAD

**Issue by TobseF** [vsch/idea-multimarkdown#433]
I want to recognize our JIRA links which are in the format: `[ITS-123]`.
So when I click on such an link, the browser should open the corresponding link (http://jira.somedomain.com/browse/ITS-123).
Is it possible to handle a link to a external website with the link map feature?

I already tired it in the style of (Link Ref element): 
_Element Text Pattern_: `\[ITS-(\d){1,5}\]`
_To File Reference_: `http://jira.somedomain.com/browse/ITS-$1`

Is such a link generation supported? For now the `[ITS-123]` fields are marked as error with the info `Unresolved reference`.

**Comment by vsch** [comment]
@TobseF, the link map is only applied to explicit link addresses. The syntax you are using requires automatic creation of link ref definitions. At the moment this is not supported. I will take a look at how this can be added and let you know when it is implemented.

**Comment by vsch** [comment]
@TobseF, latest EAP has this functionality added to Link Map via "Reference" element type. You can create it by pressing + on the tree view then select "Reference" link type and "Jira Reference" for initial content:

![image](https://cloud.githubusercontent.com/assets/10299086/25641866/6e210b48-2f64-11e7-9712-8d6bbbb29676.png)

Change "jira.somedomain.com" to your specific location:

![image](https://cloud.githubusercontent.com/assets/10299086/25641906/ab4be880-2f64-11e7-8936-ed98314895ad.png)

This applies to Preview and Exported HTML/PDF. GitHub will treat it as an unresolved link reference.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by TobseF** [comment]
Thank you for the fast reply with the update. It works and its the feature I needed.
A little improvement would be to also support link opening with ctrl + click in the editing window.

**Comment by vsch** [comment]
@TobseF, external links can now be opened with the Goto Declaration action with caret on the link URL or through the line marker for external links.

Is this the functionality you mentioned above or did you also want to navigate to JIRA references?

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
