### ISSUE TITLE
Table formatting broken

### ISSUE THREAD

**Issue by HappyHamster** [vsch/idea-multimarkdown#435]
Can't get tables to format properly for the love of me.

![image](https://cloud.githubusercontent.com/assets/7311675/25455195/93de629a-2ad7-11e7-9b59-c837165fb62a.png)

Expected result is obviously different, but I can't even scheenshot the expected because there's no way I can make it to format property even if I turn auto-formatting off. In syntax colors preview formatting is also consistently broken.

I use font with ligature support, specifically "Fira Code Retina" with increased size.
![image](https://cloud.githubusercontent.com/assets/7311675/25455559/ed8cb3f4-2ad8-11e7-90c1-dcf1d6087756.png)

I am on KDE with 4k monitor with some font scaling going on system wide:

![image](https://cloud.githubusercontent.com/assets/7311675/25455289/f2d543c2-2ad7-11e7-9e4f-d7819ea49854.png)

Configured as follows:
![image](https://cloud.githubusercontent.com/assets/7311675/25455540/da848318-2ad8-11e7-9b89-a5b6101253c9.png)

I tried changing various settings to no avail. Filing this as an issue, however if this is not, it would be much appreciated if someone cold tell me which combination of buttons do I need to push to get this working. Annoying as hell :). Paid user here (not that it should matter).

**Comment by vsch** [comment]
@HappyHamster, This could be an issue with the font character width handling. I tried this without it and with it on a OS X and in both cases there was proper alignment.

There is another setting that can affect formatting in general and table layout specifically:

![image](https://cloud.githubusercontent.com/assets/10299086/25460371/1e07a6b0-2ab1-11e7-9cc4-21708e816a35.png)

Can you please try this setting, both on and off and let me know if it makes a difference. Turning it off will ignore font metrics and treat all characters as equal width which should be fine for a fixed font.

Another thing to verify if the same thing happens when you use another editor font with the setting on, which will help figure out if it is a glitch in the font metrics.

**Comment by HappyHamster** [comment]
Yup, these were the first things I've tried :)

Setting the setting of OFF without changing font makes zero difference to the point I'm not even sure it re-renders/re-parses the content when I apply settings, so I re-open file and type something in the table with auto formatting ON to force it reformat.

I've tried using Droid Sans Mono with both setting OFF and ON, setting makes no effect, I do see font changes as expected:

![image](https://cloud.githubusercontent.com/assets/7311675/25461228/5f58da0a-2af0-11e7-987e-ecc3414c9672.png)

One thing that crossed my mind, I do use IDEA with this setting:

`-Dsun.java2d.renderer=sun.java2d.marlin.MarlinRenderingEngine`

which I don't remember if standard or not.

One more thing, that seems weird

![image](https://cloud.githubusercontent.com/assets/7311675/25461276/b6a39e9e-2af0-11e7-87fc-42204c51c58d.png)

The cursor here is at 26:11, if I press down key once on my keyboard, the cursor goes to 27:10 while expected is 27:11:

![image](https://cloud.githubusercontent.com/assets/7311675/25461363/48f5a8c8-2af1-11e7-9e57-4f5c81ccb5b2.png)

and you can also see that the cursor if not directly under where it was, it's like half-char to the left. So cursor visual fofset indeed looks like rendering issue, but why does it jump to one char less I don't know -- logical would be that is jumps to 27:11 and renders half-char to the righ, that would mean isolated rendering issue.

These 3 screenshots all made with Droid Sans Mono, "Use character font width" set to ON and ligatures to OFF. When I refer to cursor position I mean the value I see in status bar (not scattershotted for sanity reasons).

Also, as a side note, I'm not 100% sure "Droid Sans Mono" is technically monospace. Maybe try some other font?

**Comment by HappyHamster** [comment]
Ok I pinned-down the issue. In my style settings the ---- splitter between header and table is set to BOLD, if I set it to regular I don't have an issue:

![image](https://cloud.githubusercontent.com/assets/7311675/25461601/8bbe2224-2af2-11e7-985f-a44fb5c23fdf.png)

Also the caret behaves as expected while navigating vertically between lines. Could you however still check if this is me-specific issue or not? Or is it intended that you can't mix bold splitters with regular text in headings? If so, maybe prohibit setting splitters to bold altogether.

**Comment by vsch** [comment]
@HappyHamster, yes that would make a difference since the formatting code does not use font style. I will add it to the documentation and keep it in mind. From the screenshots it is not visible that the bold style is used.

**Comment by HappyHamster** [comment]
I would advice to prohibit the setting altogether

![image](https://cloud.githubusercontent.com/assets/7311675/25461727/49672690-2af3-11e7-93d7-0bcde5a12c89.png)

It would not have ever crossed my mind to seek for the solution in documentation because it's does look like a bug and behaviour is difficult to describe in some google'able terms.

**Comment by vsch** [comment]
@HappyHamster, disabling the setting might be more difficult than it appears. This part of the UI is provided by the IDE.

I will take a look to see if some solution is possible.

**Comment by HappyHamster** [comment]
Thank you.

Also would be much appreciated if there was a button/shortcut to "add column to the left of current". I know now (after reading the docs) that you can just start typing at the end of line to add column, but it's not intuitive. The mind is looking for a button/shortcut because there IS in fact a button to add to column the left.

I totally understand why it's designed that way (you NEED a button to add to the left, and text editing is sufficient to add on the right), but it's not easy to grasp from UX point of view :) 

Just a suggestion though.

I guess feel free to close this one and thanks for the support.

**Comment by vsch** [comment]
@HappyHamster, I can add the buttons/actions for additional functionality. The show stopper has been toolbar space. It is already quite big. I need to add ability to hide/show button configuration that would allow each user to customize the toolbar.

Do you mean add a column to the right of the current column? Since adding to the left already exists. Inserting a column is only needed to insert one between columns, even adding a column before the first does not need a button. You just type some text before the first column and a column will be added. It is less intuitive at first but is much faster once you know how it works.

I will look into adding toolbar button editing to reduce the size of the toolbar.

**Comment by HappyHamster** [comment]
@vsch toolbar space didn't cross my mind cause I'm on a 4k monitor lol :) But it's a good point I guess. Built-in top-level IDEA toolbars are customazible, but not sure you can get this functionality for free for a non-top-level bar.

Personally I would drop bolt/italic etc from the toolbar if they were mapped to defaults instead of Meta+B (which doesn't work on my system at all, probably due to razer keyboard drivers) because these are so common 99% of users already know them. If not possible, I would drop "export to" buttons as this is rarely used functionality I guess, also there is a logical place to look for it --- File menu, or file context menu in Project overview.

Than again it's just me. For sure ability to customize would kill two [insert creature] with one [insert object] :)

**Comment by HappyHamster** [comment]
@vsch Yes I meant when I start a table, I click "insert table" which gives me a template, then i start filling up headers and first thing i want to do is to insert another column the same way i just created a table, as in my mind it's a part of table design process sort of. Then when I will be filling the rows, I am obviously not expecting to be editing content via a popup or button, I expect that content can be typed-in.

So from UX point of view, I seek for ALL "table layout" related features amongst the buttons because there are SOME buttons for that already, and I don't expect "fill the table content" related features to be on buttons because it's content -- so there IS a line, I'm not saying everything should have a button...

This is basically the rationale behind the suggestion :)

**Comment by vsch** [comment]
@HappyHamster, the insert table is really needed because it takes 2 lines of text before the table is recognized. Thereafter, auto-formatting handles the other stuff other than insert column between existing columns, that was the reason why the other functionality was not added.

Another option would be a table editor that will let you edit a table in a spreadsheet type editor. 

I will add all of these options to the todo list.

**Comment by HappyHamster** [comment]
@vsch Yup I totally understand the logic behind, your decision making is vastly driven by technical necessity of having a button because not everything can be easily (or at all) inferred from pure text input.

But, the last point to I want to add to this wall of text is that I am a markdown-retard :)

Meaning I do NOT know markdown that well, so I use your plugin to EXPLORE what markdown has to offer as a markup "language". So for a user like me ANY markdown-related feature should be more accessible than any NON-markdown feature (like Ctrl+B is general editing knowledge I already have).

It would be great if UI generally followed this idea of "not everybody knows markdown get over it" (c)southpark in a sense of prioritizing feature visibility/accessibility in UI. The functionality of the plugin is already great, but if as a feature your product would implicitly sell a "lower entry to (advanced) markdown" amongst other features, it would sell even better i think!

**Comment by vsch** [comment]
@HappyHamster, it is a good point to address. I will look into adding features to help users not fluent in markdown syntax.

**Comment by vsch** [comment]
@HappyHamster, I added a "Insert Table Column on Right" action and toolbar button and changed the previous insert column action to show that it adds a column on the left.

![image](https://cloud.githubusercontent.com/assets/10299086/25686451/52eb5652-303c-11e7-8e6e-cdbc9524c3db.png)

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
