### ISSUE TITLE
Header link results in bad Table of Contents entry formatting

### ISSUE THREAD

**Issue by ogradyjd** [vsch/idea-multimarkdown#436]
A few versions ago, if I had a header like this:
`## [ChangeLog](doc/changelog/ChangeLog.md)`

It would result in a Table of Contents entry `3. ChangeLog` that linked to the target instead of the header.

In the GFM preview, the Table of Contents entry looks fine, but the generated TOC markdown code is wrong:
`3. [[ChangeLog](doc/changelog/ChangeLog.md)](#changelog)`
and looks like this on Github:
`3. [ChangeLog](#changelog)`
The generated TOC markdown should just take the link instead of nesting the link string in another link.

**Comment by vsch** [comment]
@ogradyjd, thank you for reporting this. It appears to be a bug. The table of contents entry should not render embedded links. I will fix it and make an EAP release.

**Comment by vsch** [comment]
@ogradyjd, issue fixed but it also requires that TOC is generated without formatting information:

![image](https://cloud.githubusercontent.com/assets/10299086/25501799/f78270d6-2b61-11e7-8dd8-2ec2cc7da7b8.png)


EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by ogradyjd** [comment]
Awesome.  Love the plugin.  I'm trying to get the entire team at Comcast using it.
