### ISSUE TITLE
GitHub Switched Document Processing to CommonMark

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#437]
![image](https://cloud.githubusercontent.com/assets/200952/25532863/0cd3fe96-2c2f-11e7-8ad6-3d99a1cb3b31.png)
It should show a bullet list for the last 2 items.

**Comment by vsch** [comment]
@holgerbrandl, you need to select CommonMark list item processing in parser options.

![Screenshot_Parser_Lists](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Parser_Lists.png)

I just checked and it appears that GitHub has switched their document processing to CommonMark from what it used to be, the preview you are seeing was the correct rendering for GitHub Docs until it was changed. Can't say when since last I checked was about a month or two ago.

**Comment by vsch** [comment]
@holgerbrandl, btw if you had documents formatted for old GitHub Doc and want to change over to CommonMark you need to switch the parser option to CommonMark then go to tools menu and select the change from GitHub Doc format:

![image](https://cloud.githubusercontent.com/assets/10299086/25545172/a318d4ca-2c2b-11e7-97e3-0b9f4e8308bf.png)

**Comment by holgerbrandl** [comment]
Oh, not a bug then. :-) Indeed changing the mode "fixes" the rendering. Thanks!

**Comment by vsch** [comment]
Not a bug but I have a feeling I will need to address it to save a lot of user confusion and bug reports.
