### ISSUE TITLE
Markdown Navigator 2.3.7 breaks paste of github checkout url

### ISSUE THREAD

**Issue by HaasJona** [vsch/idea-multimarkdown#444]
I'm unable to paste (ctrl+v) an url into the url box in the "VCS->Checkout from version control->Github" dialog in IDEA 2017.1.2. But only when Markdown Navigator 2.3.7 is installed.

For details see here: https://youtrack.jetbrains.com/issue/IDEA-172916

**Comment by vsch** [comment]
@HaasJona, thank you for reporting this bug. It is caused by the plugin paste handler erroneously skipping paste if the project passed in the data context is null.

It has been fixed for next release. EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
