### ISSUE TITLE
Strikethrough not rendered in preview

### ISSUE THREAD

**Issue by bkimminich** [vsch/idea-multimarkdown#449]
Using the strikethrough syntax of GFM will show in the editor but not the rendered preview:
![image](https://cloud.githubusercontent.com/assets/3531020/26241183/0ffbb34c-3c84-11e7-8670-2dff6664085e.png)

**Comment by vsch** [comment]
@bkimminich, this is caused by source line highlighting in preview which wraps each source line in `<span>` tag. When the inline tag is split across lines this messes up the preview HTML parsing.

You should set the highlight preview element to BLOCK to prevent this from happening.

![Screenshot_Settings_PreviewSourceSynchronization](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Settings_PreviewSourceSynchronization.png)

**Comment by bkimminich** [comment]
Thanks, I'll change that setting!
