### ISSUE TITLE
task item (done) not checked?

### ISSUE THREAD

**Issue by nheeren** [vsch/idea-multimarkdown#45]
Hello. I just tried MultiMarkdown for pycharm (141.2569 on OS X 10.10.5) and it looks pretty cool. However, I wonder why the former checkbox in this example is not shown as checked?

    * [x] done 
    * [ ] not done

![screen shot 2015-10-07 at 11 29 42](https://cloud.githubusercontent.com/assets/5136954/10333832/befebd9a-6ce6-11e5-976b-b688d55b6173.png)

**Comment by vsch** [comment]
@nheeren, the task lists only show checked if the JavaFX WebView based preview is used. However, JavaFX WebView is very finicky, to say the least, and does not work on all systems. It needs to run under JRE 1.8, preferably 1.8.0u_51 or later from Oracle. The embedded 1.8 in IDEA products does not have JavaFX so it can't work with it. 

Even then it fails to work on some systems. It is noticeably slower than the swing based preview but does have better rendering due to its HTML, CSS and JavaScript support that the swing preview is lacking.

If you are not averse to running your IDEA on an Oracle JDK then you can try it. First see if the 'Use Old Preview' check box is enabled in <kbd>Settings > Other Settings > MultiMarkdown > General</kbd>. If it is enabled then select it. Setting takes effect when a file is opened. Open a file that is not yet open or close and re-open a file and see if the preview changes. The JavaFX based preview look more like GitHub than the old. If you get a little book icon and the file name in a header like this:

<img width="641" alt="screen shot 2015-10-07 at 9 41 16 am" src="https://cloud.githubusercontent.com/assets/10299086/10339096/a47df90e-6cd7-11e5-8572-5f753ca51b81.png">

then you have the new preview. If not, then check settings and you should see the 'Use Old Preview' check box disabled. It means that either JavaFX was not found in the JRE you are using or there was an exception during initialization of JavaFX or WebView. You will need to use another JDK version. For instructions see <https://github.com/vsch/idea-multimarkdown/wiki/Changing-Boot-JDK>

**Comment by nheeren** [comment]
OMG - thank you for the great answer! It seems like it could take some time to make this work. Time I don't have right now. I will give it a try soon though.
