### ISSUE TITLE
Too much gray gutter space when multiple links are present in paragraph

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#464]
In general I like gutter icons, but since recently (EAP channel) the gutter column started to eat a lot of space  when some of the paragraphs contain multiple links:
![image](https://user-images.githubusercontent.com/200952/28287329-86475bba-6b3b-11e7-9cd5-03b4e9bf4a35.png)

And since the gutter width is fixed for an editor instance, this creates weired empty spaces even if no link is present at all:
![image](https://user-images.githubusercontent.com/200952/28287421-e9f9e858-6b3b-11e7-8921-fb138df7f409.png)

**Comment by vsch** [comment]
@holgerbrandl, the IDE puts all gutter icons on the line where they occur.

You have soft-wraps enabled which means that the text is not wrapped to multiple lines causing paragraphs to be on a single line. If the paragraph has multiple links then all of these will go on one line.

Since the IDE collects the line markers (gutter icons) by going through elements in the file the knowledge of how many gutter icons will show on one line is outside the plugin control.

I can add gutter icon enable/disable configuration but that would turn them all on or off.

**Comment by vsch** [comment]
@holgerbrandl, I am running dev version built from idea-community/master and it seems that now the IDE will combine elements with the same icon into a drop down. In your case it will save one icon space.

However, wrapping the text to margins to reduce the line length will do a much better job. Turn off soft-wrap and reformat document, or enable text wrapping with soft-wraps:

![image](https://user-images.githubusercontent.com/10299086/28287975-a4f9e044-6b0b-11e7-80ed-a1a535ebc3f9.png)

**Comment by holgerbrandl** [comment]
Thanks for the info. I'll think I'll wait for 2017.2 and keep my softwraps. :-)
