### ISSUE TITLE
Pressing tab in a empty list item should indent the list

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#469]
```
Foo
- <press-tab>
```

Expected:

```
Foo
  - |
```

Actual:

```
Foo
-   |
```

**Comment by vsch** [comment]
@vjpr, I will add smart tab behaviour for markdown documents.

**Comment by vjpr** [comment]
Hey @vsch any updates on this feature. I really want to move from Atom to IntelliJ for Markdown editing, and this is the only thing holding me back (i know its small - but i use a lot of bullets!).

Can I assist?

**Comment by vsch** [comment]
@vjpr, I could not make it for the last release but will be adding this functionality over the weekend. It is not the feature but dealing with side-effects and tweaking for comfortable use that will take the most time.

Helping on this would be difficult since the open source version has diverged and I have been making very slow progress in merging changes from my source base back to this repo. I really need to create an API for the plugin which will allow the open source version to be extended with licensed features. That way there will be no merging of code, only inclusion of another plugin in the distribution. 

Right now the two source bases are separate and it has gotten to a point where merging changes is almost impossible.

**Comment by vjpr** [comment]
Hey, just wondering if this feature could be another quick fix? It really makes it difficult to work with lists. 

Feels like something as simple as:

```
If caret is in front of `<whitespace>-<space>`, call `markdown navigator indent list` command.
```

**Comment by vjpr** [comment]
@vsch Just checking in on this feature.

I've tried using different shortcuts such as `ctrl+shift+right` but its still not as easy to press as tab, and is still a daily frustration for me.

Is there any quick hack to get this function?

**Comment by vjpr** [comment]
@vsch Saw you closed a bunch of issues I posted recently. Thanks for that!

Just wanted to check if there is any progress on this feature? I really miss it the most.

**Comment by vsch** [comment]
@vjpr, I haven't psyched myself up for rewriting that part of the code. It will definitely be part of the next release. I have no choice. I am tired of tweaking the code every time the IDE changes some implementation or timing which affects the code. I will rewrite it to use my own library instead of the IDE provided element tree.

**Comment by vjpr** [comment]
Has any progress been made on this? Is there a quick and dirty way to implement it?

**Comment by vsch** [comment]
@vjpr,  got this working for both tables and lists. Main settings for plugin has tab override options, enabled by default.

For lists tab/backtab (shift+tab) will indent/unindent if caret is on list item or its item paragraph

<img width="1036" alt="screen shot 2018-08-29 at 6 53 31 pm" src="https://user-images.githubusercontent.com/10299086/44819976-ee005280-abbc-11e8-89b5-5c4bbaeb4b5a.png">

EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by vjpr** [comment]
Just installed this. Not working for me.

**Comment by vsch** [comment]
@vjpr, can you please provide more details on the specifics of the markdown and caret position when you hit tab.

Make sure you have the option for tab/backtab for list indentation enabled.

**Comment by vjpr** [comment]
Exactly as the original issue says...except not even a tab is added. Nothing happens.

**Comment by vsch** [comment]
@vjpr, the list item indent will indent or absorb the key if no indent is possible.

The indent is only possible if there is a sibling list item before the current item. This is the reason I asked for the markdown and caret position of your use case so I can see if this is working as intended or a bug in the code.

"It is not working" does not give me much information to work with because the use cases that I use for my testing and debugging, obviously work. 

Markdown has a lot of quirks, especially when trying to figure out the context from the AST. So having an actual use case makes it possible to see the exact circumstances and figure out what is going on.

There a lot of quirks that need to be addressed and was the reason I was hesitant to add this feature. I knew that a lot of edge cases would be need to be addressed as they arise.

**Comment by vsch** [comment]
@vjpr, I tried it and it works. In the animation below I am using tab/shift+tab to indent/unindent the list item.

![indentlistitem](https://user-images.githubusercontent.com/10299086/45839544-a1eb8e00-bce2-11e8-9408-3e3be7800a19.gif)

**Comment by vsch** [comment]
@vjpr, since the AST is affected by parser settings, it is possible that some setting messes up the logic.

Can you post a screenshot of the main settings pane and the parser pane so I can try it with your settings.

BTW, if you are using the EAP version you should update it to the latest released version 2.6.0, there were some bug fixes which may affect the relevant code.

**Comment by vsch** [comment]
@vjpr, did you resolve the issue or is it still not working for you?

**Comment by vjpr** [comment]
![screen shot 2018-09-29 at 3 14 49 pm](https://user-images.githubusercontent.com/281413/46246216-6e9fb200-c3fa-11e8-898f-d0adb011f76d.png)
![screen shot 2018-09-29 at 3 15 06 pm](https://user-images.githubusercontent.com/281413/46246219-77908380-c3fa-11e8-92f0-a9db25e73168.png)

**Comment by vsch** [comment]
@vjpr, thank you. I tried and still cannot duplicate the problem. On my system they work. Good too since I got used to the comfort of using them.

I am grasping for straws since I cannot duplicate it and you cannot use it. There must be a difference in our setups that needs to be isolated.

What IDE and OS are you using? 

Can you try if the back-tab will unindent? The way the shortcuts are defined for these, back-tab uses IDE defined shortcut set while tab is hand-rolled. 

Just indent a list item manually and then use back-tab to unindent. If it works but tab does not then it is the way the shortcut is defined.

**Comment by vjpr** [comment]
![screen shot 2018-09-29 at 9 05 06 pm](https://user-images.githubusercontent.com/281413/46249553-5bf1a100-c42b-11e8-8899-1b48ccdde8d5.png)

IntelliJ

```
IntelliJ IDEA 2018.3 EAP (Ultimate Edition)
Build #IU-183.2940.10, built on September 25, 2018
IntelliJ IDEA EAP User
Expiration date: October 25, 2018
JRE: 1.8.0_152-release-1293-b14 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
```

macOS.

**Comment by vsch** [comment]
@vjpr, another list indent/unindent improvement, inspired by your original request.

I got completely used to working with tab/back-tab adjusting new list items, but got tired of having to back-tab for to unindent a new item when it is either created indented or I accidentally over indent it with tab.

Added an option to allow tab/back-tab to cycle indentations so tab on deepest indent level will completely un-indent the item and always only affects the empty item not any items which may look like its sub-items. #807
