### ISSUE TITLE
Will not allow me to crop beyond 200px

### ISSUE THREAD

**Issue by acrodrig** [vsch/idea-multimarkdown#481]
The current cropping controls will not allow me to go beyond 200px. This seems arbitrary and does not work for the large images I work with.

![screen shot 2017-08-08 at 12 40 12](https://user-images.githubusercontent.com/959336/29086042-d8127504-7c36-11e7-8fab-697456214cfe.png)

**Comment by vsch** [comment]
@acrodrig, you are right. I will set the limit at 4096, which should take care of most cases. It was not really intended to do large image cropping. I figured it would be used for cleaning up cropping on a screen captured image.

I'll make an EAP release with the fix so you can use it.

**Comment by vsch** [comment]
@acrodrig, now limits are derived from the image dimensions and image operations.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by vsch** [comment]
@acrodrig, I remembered you were doing some heavy cropping of images. A new EAP release has option to use mouse selection in the preview area of paste image dialog, instead of messing with the crop buttons. The buttons are designed to shave a few pixels off not to do serious cut outs. Just make sure the Use mouse selection only for highlight is turned off. 

![screenshot_pasteimagecrop](https://user-images.githubusercontent.com/10299086/49201389-bac19100-f36e-11e8-9b31-db06015689d6.png)

Also added ability to add a highlight box (with inner/outer fill colors and transparency) to allow for quick instructional snapshots with attention highlighting (the above image is with 30% black outer fill)

![imagepaste](https://user-images.githubusercontent.com/10299086/49201595-86020980-f36f-11e8-87f8-7ddef55db587.gif)


A bit more docs: [Enhanced-Features: copypaste](https://github.com/vsch/idea-multimarkdown/wiki/Enhanced-Features#copypaste)

**Comment by acrodrig** [comment]
Nice! Thanks for the heads up.
