### ISSUE TITLE
Intellij Hangs on opening project with Markdown window open

### ISSUE THREAD

**Issue by neilellis** [vsch/idea-multimarkdown#483]
Intellij hangs with spinning beach ball of doom on project open. 

https://www.dropbox.com/s/jtvl1woce4vmeqm/Screenshot%202017-08-14%2013.19.56.png?dl=0

VM settings:

-Xms128m
-Xmx4g
-XX:ReservedCodeCacheSize=240m
-XX:+UseCompressedOops

I can email over logs from Intellij

**Comment by vsch** [comment]
@neilellis, yes please e-mail me the logs so I can check where it hung.

**Comment by vsch** [comment]
@neilellis, can you also include the thread dumps if they are time stamped when the hang occurred. IntelliJ IDEs create these when the EDT thread hangs for longer than normal and are created in subdirectories where the idea.log file is located.

**Comment by neilellis** [comment]
Yep I'll go and reproduce the problem now and email the logs over.

**Comment by neilellis** [comment]
OK emailed to you now

**Comment by vsch** [comment]
@neilellis, thank you. I will investigate the cause.

**Comment by vsch** [comment]
@neilellis, it hangs in JavaFX WebView initialization. This is JRE related and has cropped up before in the JetBrains Open JRE but I thought it was fixed. The only workaround is to switch to Default Swing preview.

What exact build of the IDE are you running? Specifically the JRE build number.

**Comment by neilellis** [comment]
Version details: https://www.dropbox.com/s/j8ix2gnw9famctm/Screenshot%202017-08-23%2000.12.27.png?dl=0

Thanks, I will give that a try.

**Comment by neilellis** [comment]
I have tried both, still hangs. Will do a clean install of Intellij

**Comment by neilellis** [comment]
Okay, tried with a fresh install, still hangs

**Comment by neilellis** [comment]
Yep I am
```bash
NeilMacBookPro:~ neil$ java -version
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by vsch** [comment]
@neochief, JavaFX in the bundled JRE has issues under OS X High Sierra on a few systems. Disabling JavaFX preview on these systems or using an Oracle JDK instead of the bundled on seems to solve the issue.

**Comment by vsch** [comment]
I have a trial build which should fix this but I cannot run High Sierra on my system and waiting for feedback to know if the issue is fixed for the hang and/or crash.

You can try this build by downloading the zip file and installing plugin from disk. Do not extract the zip. Simply select it from the IDE Plugins settings pane by clicking the install plugin from disk.

https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.5.2.22.zip

The fix is not polished and initial display of the preview can be missed if initialization of JavaFX takes longer. Switching off preview and turning it on restores preview. I will fix this in the next build but I am curious to know if the fix does address JavaFX preview hangs.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)
