### ISSUE TITLE
Open links in preview, not browser

### ISSUE THREAD

**Issue by ianfp** [vsch/idea-multimarkdown#484]
I just started a trial license, and suddenly internal links in the preview pane are opening in my browser rather than in the preview pane. How do I get to other .md files to open in the preview pane? They did when I was using the free version.

Also, this is not a bug report. Where do I go for help?

**Comment by ianfp** [comment]
Update: I just added a new local link, and it appeared yellow with the warning: "Target file is not on GitHub. Link will only resolve locally." That's the behaviour I want all the time! When did GitHub get involved here?

**Comment by vsch** [comment]
@ianfp, the plugin's initial intention was to work with GitHub markdown nuances. Since then users have used it in a lot of ways not related to GitHub documents.

You can ask for help here or by e-mailing me directly.

As for opening MD files in preview, I will need to add a setting to open markdown documents instead of using the GitHub link for the document. Navigation to documents from preview is made to files on GitHub but I can see if you are working only locally then you want the navigation to be to the markdown file.

Navigating to markdown files can be done in the enhanced version using the link in the source. Use standard `Go To Declaration` on a link URL and if it is a file in the project it will open that file in the editor.

You can also navigate to headings in files by navigating from anchor ref of a link. Similarly for other reference elements like Reference Links and Reference Images to References, Footnote references to footnote declarations.

**Comment by ianfp** [comment]
@vsch Thanks for your thorough answer! I'll try your suggestions when I have time and follow up here if I have any further questions.

I'll let you decide whether close this issue or leave it open for the proposed new setting.

**Comment by vsch** [comment]
An option was added to preview that allows opening corresponding GitHub files or local files for page relative or repo relative links.

![Screenshot_Settings_PreviewBrowser](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Settings_PreviewBrowser.png)

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
