### ISSUE TITLE
Multi-line links do not preview correctly

### ISSUE THREAD

**Issue by lihaoyi** [vsch/idea-multimarkdown#486]
This:

```md
[hello
world](#test)
```

previews as

```html
<a href="#test">hello</a>
world
```

Whereas it really should preview as 

```html
<a href="#test">hello
world</a>
```

**Comment by vsch** [comment]
@lihaoyi, thank you for catching this. I will have a fix out shortly and make an EAP release.

**Comment by vsch** [comment]
@lihaoyi, this is caused by a bug in source line highlighting in preview and as a workaround you can change the mode to `Block` which does not split blocks into individual lines.

[Screenshot_Settings_PreviewSourceSynchronization](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Settings_PreviewSourceSynchronization.png)

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
