### ISSUE TITLE
Wrong character's encoding in exported PDF

### ISSUE THREAD

**Issue by jabocrack1** [vsch/idea-multimarkdown#504]
Wrong character's encoding in exported PDF (see screenshot). PhpStorm 2017.2.4, installed plugin 2.3.8
on left - acrobat reader with rendered PDF, on right - preview zone with same document.
![screenshot_2](https://user-images.githubusercontent.com/14205678/31311838-7317a190-abbd-11e7-9968-1f2a581e1680.png)

**Comment by vsch** [comment]
@jabocrack1, thank you for the report. I will take a look at PDF conversion to see what encoding should be used.

**Comment by cwt9562** [comment]
I meet this bug too, any update?

**Comment by Terminator637** [comment]
Me too, when it will be fixed?

**Comment by vsch** [comment]
@Terminator637, @cwt9562  as soon as I can figure out how to tell the OpenHtmlToPDF to use a different font for the PDF.

The issue is with the font. It does not contain the Unicode characters. Which means that if there is a mix of languages, each one may need to use a different font or have a single font that supports all of them.

**Comment by vsch** [comment]
Please see #533 and #642 for a solution to this issue.
