### ISSUE TITLE
Export HTML

### ISSUE THREAD

**Issue by spotter** [vsch/idea-multimarkdown#51]
Is it possible to export the HTML as it is shown in the "HTML Preview" pane? If not, is it a feature that you envision to develop?

**Comment by vsch** [comment]
@spotter, you can copy/paste the HTML right now. The HTML text preview is a regular text editor but in read only mode. So all non modifying actions such as search, select and copy work. 

By export do you mean automatically save the HTML to a file every time the markdown document is edited? That would require some thought to the configuration or on the fly "learning" which files to save and where. 

I thought about it but decided that the proper way would be to integrate it into the build process and decided that it was not something I could devote time to until full psi parser and related functionality was complete. 

I will add it to the wish list. If you have some ideas of how you see it done for your needs please let me know. I don't have a use case in mind. On my website I opted out for a PHP markdown compiler instead of using my plugin for generating HTML since it was easier and results in half the files since I only need to keep the markdown source.

**Comment by spotter** [comment]
Thank you @vsch for the fast answer.

> @spotter, you can copy/paste the HTML right now. The HTML text preview is a regular text editor but in read only mode. So all non modifying actions such as search, select and copy work.

This is what I do for the moment. However, this doesn't provide the "GitHub" look and feel I'd like (especially, syntax highlighting).

> By export do you mean automatically save the HTML to a file every time the markdown document is edited? That would require some thought to the configuration or on the fly "learning" which files to save and where.

What I meant was more simply to enable the user to "right-click" on the HTML Preview tab and choose save as HTML.

My use case is probably simpler than what you are referring to in your last paragraph: I wrote a program for some collegues (i.e., with very limited distribution) and I wanted to write (in markdown) a standalone "Readme" that they could use as a user guide. As a workaround, I would be equally happy with the ability to specify the output location of the generated HTML rendered in the HTML Preview pane.

**Comment by vsch** [comment]
@spotter in multimarkdown settings you have a choice for the HTML Text tab whether it shows raw HTML as generated by the pegdown parser or "modified" for use in the preview tab. It sounds like you have the "modified" option turned off.

<img width="1189" alt="screen shot 2015-10-27 at 9 18 03 am" src="https://cloud.githubusercontent.com/assets/10299086/10759237/a03b1b50-7c8c-11e5-96c4-d1bf50e132ca.png">

If you turn it on then all the CSS and other modifications done to the HTML for preview will be in the HTML tab. If you use the old preview then you will still need to manually add the CSS references since the old preview uses in memory css. The new preview copies all the files needed for rendering: CSS, font and highlight.js into temporary files so you can copy those temp files somewhere accessible and modify the references to these in the generated HTML. However these mods are mechanical and can be done with a simple script.

The CSS files used by old preview need to be copied from the jar or you can get a copy of all these files right from the repo from <https://github.com/vsch/idea-multimarkdown/tree/master/src/main/resources/com/vladsch/idea/multimarkdown> the css files ending in -fx.css are used for the new preview.

**Comment by vsch** [comment]
@spotter, just thought of an easier way to get all the CSS for new preview. In CSS Options select custom css with all the fixings:

<img width="1190" alt="screen shot 2015-10-27 at 9 37 14 am" src="https://cloud.githubusercontent.com/assets/10299086/10759558/5a23773c-7c8e-11e5-8589-f3f25eb2caa2.png">

Click "Load Internal CSS" and then you can enable the "Use Custom CSS". Then the HTML Text will have a single CSS reference and it will be a temp file containing the custom css which is a concatenation of all CSS files.

You can copy the temp file or copy/paste the Custom CSS text from the settings dialog to a file that you will use as the stylesheet for your users.

**Comment by vsch** [comment]
@spotter, oops, just discovered there is a bug that fails to include the custom css in the preview and html text. My bad. I'll have it fixed in the next release.

**Comment by vsch** [comment]
@spotter if you want to use the Custom CSS route then you can download a fixed plugin zip from here <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.1.13.2.zip>

**Comment by vsch** [comment]
See #314

**Comment by vsch** [comment]
Implementation in 2.1.1.8 or later, update available in EAP plugin channel.
