### ISSUE TITLE
Add keyboard shortcut to `Cycle between Preview only and Editor only`

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#512]
There is `Toggle Editor Layout` and `Cycle split layout`. But often I want to replicate the Github editor behaviour by cycling between editor and preview - because I use small editor panes which don't look good split.

**Comment by vjpr** [comment]
Will also depend on https://github.com/vsch/idea-multimarkdown/issues/511 being resolved.

**Comment by vsch** [comment]
Added application setting to select text/split or text/preview toggle for the toggle editor layout action.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.
