### ISSUE TITLE
Reduce color scheme footprint?

### ISSUE THREAD

**Issue by mallowigi** [vsch/idea-multimarkdown#519]
I'm a plugin developer and I wanted to update my color scheme to include Markdown Navigator colors inside it. However after seeing the icls generated by my configuration, I've seen that the icls grew up to more than 65000 lines!!! and 62000 lines of it are Markdown Navigator!!!!!

It looks like you're registering every combination possible of bold-italic-subscript-abbr-etc. It kind of make sense when you give the ability to customize whether bold (e.g. double asterisks) are indeed bold, and thus bold+(every other status) must be registered. Same for italic, subscript...

Don't you have a better way to reduce the footprint? For instance by removing all these combinations? The IntelliJ plugin does that just fine, no?

As a side note why is the plugin not importing default values from the Markdown plugin? What was my surprise when I had to reconfigure everything...

**Comment by vsch** [comment]
@mallowigi, the combination attributes are generated from base attributes when the plugin initializes or the scheme is switched.

I did not find a way of intercepting saving of the color scheme so that all the combinations could be removed when saving the color scheme. I will take another look at the API to see if this could be achieved. The plugin does not need the combinations to be saved, only the bare original attributes.

This was implemented as a workaround for lack of ability to create combined attributes by lexer.

Without this duplication highlighting nested constructs would not work. For example table rows and columns are colored differently for odd/even instances. Without creating a combination of bold and row/column combinations bold in a table would not display the row/column background. The same applies for things like inline code, typographic quotes and many other attributes that can be combined.

**Comment by mallowigi** [comment]
Maybe one improvement would be to set two type of color scheme settings? For instance, I don't separate between even and odd rows, so they mostly take some space for nothing.

In any case I've removed the combination attributes from the color schemes, so that solves it; but unfortunately every time the user would select the color scheme, IntelliJ would mark the scheme as a copy as a result of the combination attributes being added to the color scheme, which is not ideal. I can add a section in the readme pointing to this issue, but it's too bad.

Maybe you can use two sets of color settings? One for the basic (bold, header, code) and one for the advanced (even, odd rows, abbr etc). I don't know

**Comment by vsch** [comment]
@mallowigi, I did not see any way of controlling this in the API. The plugin provides the attributes and the color management is done by the IDE. I will ask JetBrains if there is a way to filter out attributes during color scheme saving so that only original attributes are saved.

Another option is to add configuration settings that will allow disabling creating some or all combinations so that the ones not used can be disabled. I will look into both options.

**Comment by mallowigi** [comment]
Thanks a lot! Great plugin by the way :)

**Comment by arteniioleg** [comment]
I maintain my color-scheme in git and use it in all JetBrains IDEs (CLion, PhpStorm, WebStorm).
60000+ lines is not fun.
https://github.com/arteniioleg/color-scheme/commit/d82138f5c2e9272ca7e1c89eceea634ad2b088f7

**Comment by vsch** [comment]
@mallowigi, @arteniioleg, I have only been able to find a way to reduce size of a saved color scheme if manual export is used on the scheme (using gear icon drop down next to the schemes combo box).

However, color schemes saved in the IDE colors subdirectory are not affected and I did not find a way to affect automatically saved color schemes.

The export action is named: `Intellij IDEA color scheme, reduced markdown (.icls)`

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
