### ISSUE TITLE
Not working: As you type automation: Double of bold/emphasis markers and remove inserted ones if a space is typed

### ISSUE THREAD

**Issue by psicho2000** [vsch/idea-multimarkdown#520]
When I enter **, *, __ or _ I would expect to have it doubled with the caret in the middle of it. This is currently not working.

**Comment by vsch** [comment]
@psicho2000, this feature was disabled because many users complained about the behavior. I can enable it as an option that is turned off by default.

**Comment by vsch** [comment]
@psicho2000, option re-enabled in Editor > Code Style > Markdown, under smart edit.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by psicho2000** [comment]
Thanks, I tested it and it is working great (better than Sublime with MarkdownEditing plugin). I wonder why others did not like it :) Good way to make it configurable, though.

**Comment by vsch** [comment]
@psicho2000, you also have the shortcuts for toggling bold, italic or inline code. 

1. When there is a selection:
   1. if the selection selects all or portion of the inline formatted text then the formatting is removed
   2. Otherwise wrap the selection in the inline formatting markers
2. When there is no selection:
   1. When the caret is inside the inline element the attribute is removed. 
   2. When the caret is at the beginning or end of a word, the word is wrapped in the attribute. In other cases the open/close element marker characters are inserted at the caret and the caret moved between them.

This makes it easier to apply inline formatting pre or post typing a word.
