### ISSUE TITLE
`Header level up` should create H1 when there is no heading

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#528]
```
Foo<press header up shortcut>
```

```
# Foo
```

**Comment by vsch** [comment]
@vjpr, you will probably also ask for header down removing the leading `# ` on a heading? :)

I will add both to the to do list.

**Comment by vsch** [comment]
@vjpr, heading actions updated. Now heading up adds # to plain text lines, heading down converts headings to plain text. Also heading up on Setext heading level 2 will convert to ATX heading level 3. 

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
