### ISSUE TITLE
Copy-paste behavior with images

### ISSUE THREAD

**Issue by neochief** [vsch/idea-multimarkdown#529]
Suppose I have following file:

a.md:
```
![imgA](/images/test.png)
```

When I copy and paste this line into another file, it is being pasted like this:

b.md:
```
![imgA](https://github.com/neochief/rg/raw/master/public/images/test.png)
```

How do I avoid this change in the image URL?

BTW, this might be related to https://github.com/vsch/idea-multimarkdown/issues/499, since when I disable link mapping, this thing does not happen (but images become unrecognized, which is not desired).

**Comment by vsch** [comment]
@neochief, when the specific URL format does not resolve to the file, the plugin automatically changes the format to absolute http: format so the image resolves. Otherwise, you would be pasting a link that does not resolve. On the other hand if the link resolves but the format is wrong then you can always use the intentions to change the format.

If you fix the image becoming unrecognized when using the site relative format, it should paste the link in the same format.
