### ISSUE TITLE
How to debug the project

### ISSUE THREAD

**Issue by haifang12** [vsch/idea-multimarkdown#534]
Hi, I want to use this project to study how to add new file types to Android studio, and how to edit the new file type's file.
   I'm using IntelliJ IDEA 2017.1.5 on Mac OS X 10.12.3. But when I debug the project in the new project. The new project can not recognize the file type "mkd" or "md". So my study is blocked.
Could you please tell me how to debug the idea-multimarkdown project in IntelliJ IDEA. I will really appreciate it

**Comment by vsch** [comment]
The IDE when running under debug creates a new instance of IDE configuration and stores plugins under debug in that location.

I found that in order to debug the plugin it is necessary to install the plugin in the debug instance of the IDE. I am not sure if the idea-markdown requires it because it was not required before. 

However, you should install the zip file for the plugin that you generate in the project by using the install plugin from disk button under Plugins in settings/preferences.
