### ISSUE TITLE
auto completion for files on .link template

### ISSUE THREAD

**Issue by Urs-Meili-CLX** [vsch/idea-multimarkdown#553]
I'm using markdown navigator on Rider 2017.3. Is there supposed to be auto completion available for the .link template? If I press Ctrl+Space after a #, I get auto completion for all headers in the document:
![image](https://user-images.githubusercontent.com/29592407/35389238-3d270290-01d7-11e8-8490-d1a6195a5b39.png)

However, I would expect to get all files in the current directory in the auto completion list in this situation - but the list is empty: 
![image](https://user-images.githubusercontent.com/29592407/35389282-5d2654ce-01d7-11e8-962f-7b69d0ff9b1c.png)

Am I missing something obvious? Or is this simply not working?

**Comment by vsch** [comment]
@Urs-Meili-CLX, auto completion for files will show all files in the project. By default only Markdown files will be shown. If the link address part has an extension then all files with that extension will be shown.

The plugin uses file name index to get a list of files. I have never tried using this feature with Rider and will have to try it to see if there are differences with other IDEs in how this is handled. Specifically, I do not know how indexing is done by the IDE.

One caveat is that the files are supposed to be part of the project for the IDE to index them. Again, not being familiar with Rider, I do not know if there is a manual method for adding directories to the project. In Java directories can be added as Sources Root, Test Root, Resources Root or Test Resources Root. Any of these will add the directory to be included in the indexing process.

Do you nave several markdown documents in the project?

As a test add an extension to the link before starting completion which you know will show multiple files as options. You will need to type the extension and then move the caret before the extension, otherwise the IDE will try to use the extension as part of the completion and may not show any options.

I will install and try Rider to see how it interacts with the plugin.

**Comment by Urs-Meili-CLX** [comment]
Yes I have multiple *.md files in the project. None of them show up. Note that I tried with both a *.sln (project) as well as opening the folder with the *.md files directly in Rider.
It seems to me that this could indeed be a Rider issue.

**Comment by vsch** [comment]
@Urs-Meili-CLX, I will have to install Rider and try to figure out what is going on. Could be some difference in the IDE that the plugin should take into account. 

I forgot to mention that the plugin uses Git roots to figure out link resolution and without having the project under Git completions do not work.

On CLion, I found that completions did not work until the project was under Git VCS. Just creating an empty Git repository under the project directory was enough to have completions working.

**Comment by vsch** [comment]
@Urs-Meili-CLX, I can confirm that you need a Git root defined in order for completions to work. 

Currently all link resolution is done using GitHub rules with some "kludges" for files outside a Git root.

A full rework of link resolution to allow different VCS and cloud providers, including non-vcs projects is on the todo list. Some discussion of this topic is discussed in #545.

In my test I installed Rider and created a command line app project. Adding two markdown files: `Readme.md` and `Version.md`

No completions showed until I ran `git init` in the solution directory. The IDE added the git root automatically to the configuration. After that the completions worked.

I will take a look and see if I the git root requirement is a side-effect of the code that can be eliminated to allow the non-vcs file directory kludges to work until I can address this with a rewrite of the link resolution logic (which includes completions).

**Comment by Urs-Meili-CLX** [comment]
Indeed this project is not a git project. In the .NET world (which is the target audience for Rider), there are still many projects which use TFS as source control system, so I guess it would be a good idea if this would work without git.

**Comment by vsch** [comment]
@Urs-Meili-CLX, in this case it was a bug. If either of the target file or the source file was not under Git root then no relative addressing completions would be generated. Pressing ctrl+space 4 times to get `file://` style completions, then completions would work.

Now if both files are not under Git or both are under the same Git root then relative addressing is allowed.

EAP update with a fix for the issue is available. To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by Urs-Meili-CLX** [comment]
I can confirm that the issue is fixed with the newest EAP build. Thanks a lot!
