### ISSUE TITLE
Default editor layout > Use last selected layout

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#556]
Sometimes I will have 1 markdown tab open. Other times I will want to put 2 next to each other. When 2 are open, there is not enough space to show the preview.

I suggest a new default editor layout.

When you change the editor layout in the toolbar, it uses this layout for the next opened markdown tab.

**Comment by vsch** [comment]
@vjpr, cannot be a layout setting because then what is the starting layout?

I will look into adding a checkbox in preview to enable this option.

 This is more difficult than you think because there are scoped profiles. Cannot just change the "default" profile based on a change in an editor. Will only apply to editors on files using default rendering profile. The others will take their settings from the profile as now.

**Comment by vsch** [comment]
@vjpr, EAP update with a fix for the issue is available.

Set Last layout actions sets default layout checkbox.

![Screenshot_Settings_Preview.png](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/Screenshot_Settings_Preview.png)

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)
