### ISSUE TITLE
Bug: Checkboxes not showing

### ISSUE THREAD

**Issue by sebolio** [vsch/idea-multimarkdown#557]
Hi, when I use checkboxes, whether they're checked or not, they show like an unknown character in the preview. I hace macOS 10.3.3 with WebStorm 2017.3.4

<img width="564" alt="captura de pantalla 2018-02-14 a la s 17 54 32" src="https://user-images.githubusercontent.com/197329/36227556-23af5770-11b0-11e8-87ce-18aabf12cb52.png">

**Comment by vsch** [comment]
@sebfindling, to see the checkboxes properly you need to switch to JavaFX WebView browser. I could not get Swing to handle displaying the right images properly and gave up.

See: #45

**Comment by sebfindling** [comment]
But what about just using HTML with proper CSS? or a PNG image?
```html
<input type="checkbox" checked="checked"> item
```

**Comment by vsch** [comment]
@sebfindling, if you can find a way for swing to disable the checkbox and have it line up with the text then I will add it to the Swing browser.

Swing has a lot of limitations and I don't waste my time on making it better because JavaFX does a much better job of rendering the page and with a log more features and less effort.

**Comment by sebfindling** [comment]
if you tell me how yo run a swing browser on my computer, i will happily work on it in exchange for a free license 😃

**Comment by vsch** [comment]
@sebfindling, you are running it now in the plugin. There is no stand-alone version. 

You can just put the HTML into markdown since Markdown handles HTML, just don't put blank lines which by default end an HTML block in [CommonMark (spec 0.28)].

To play with CSS you can use either a file as a custom URI or CSS text. I recommend just adding custom CSS text. (in the same settings pane as the highlight scripts for JavaFX)

Just switch your preview browser to Swing, or you will be doing all the work in JavaFX thinking how easy it is. Swing browser is Java based and has many limitations in handling CSS and HTML attributes. You will discover this as you go. 

Good luck.

[CommonMark (spec 0.28)]: http://spec.commonmark.org/0.28/

**Comment by vsch** [comment]
@sebfindling, I forgot to mention that you should set your plugin update channel to EAP. Lots of bug fixes and some new features are already implemented.

To enable EAP update channel:

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

Then make the IDE check for updates.

**Comment by vsch** [comment]
@sebfindling, how are your doing with Swing browser? 

I just wanted to let you know that Swing is a PITA to use and JavaFX WebView just got a ton easier for me. To make a long story short, I had a few long standing bugs between Java and JavaScript in WebView. Got so pissed at not having a debugger and wasting hours adding print statements on every other line so I can figure out what is going on.

Spent a few hours and found some basic Chrome to WebView connectivity, did not know it was possible. I looked. Spent another 40 hours and made it into a full fledged Chrome Dev Tools supported browser.

Now I can work in WebView almost as if it was Goggle Chrome. [Javafx WebView Debugger](https://github.com/vsch/Javafx-WebView-Debugger)

With this upgrade, my motivation to work in the Swing browser just took a hit. If you can find a solution to this I will gladly implement it.

P.S. Here is what my JavaFX WebView script, html and css debugging looks like now:

![devtools](https://user-images.githubusercontent.com/10299086/36626546-acb95d28-1902-11e8-83b4-f50e1b906b49.png)

**Comment by sebfindling** [comment]
hi @vsch , sorry for not answering before but i recently got a contract for a project that has kept me really busy, what you did looks just awesome, i'll try to make some time to play with it, have you made any more progress?

**Comment by vsch** [comment]
@sebfindling, no need to apologize. I am in the same boat. Consulting to earn a living and trading sleep for work on the plugin and other projects.

The debugger makes a world of difference. It like working by feel and suddenly the lights come on. Actually makes it a pleasure to work with JavaFX, like it was Chrome's little brother.
