### ISSUE TITLE
Preview does not respect hidpi scaling on Ubuntu

### ISSUE THREAD

**Issue by mmagyar** [vsch/idea-multimarkdown#56]
The preview is show without scaling, rendering it very hard to read on a high dpi screen.
The screenshot shows this behavior in PhpStorm9
![screenshot from 2015-10-31 11-22-53](https://cloud.githubusercontent.com/assets/2776781/10863066/ca7418a8-7fc1-11e5-8cac-438e67621d35.png)

**Comment by vsch** [comment]
@mmagyar this is a known JavaFX WebView issue. The workaround is to set the Zoom level in <kbd>Settings > Other Settings > MultiMarkdown > General</kbd> so that the display is enlarged.

<img width="1011" alt="screen shot 2015-10-31 at 8 02 55 am" src="https://cloud.githubusercontent.com/assets/10299086/10863490/d4889cae-7fa5-11e5-9ed0-1942d0e85093.png">

The Zoom setting was originally added specifically to address this issue. #27

**Comment by mmagyar** [comment]
@vsch Sorry, i did not notice that issue.
could the plugin notice the DPI scaling automatically?
I know that on OS X this is not a problem, but on other operating systems it's still is.

**Comment by vsch** [comment]
@mmagyar I can try to set the default value for Zoom based on the DPI scaling used by the IDE, but that would only affect new installations of the plugin since the setting for this is already set to 1.0 by default. 

I also do not have any reliable way of testing if this code will work correctly on all systems and ensure that cure will not be worse than the disease. On windows system in issue #27 the comfortable zoom level was set to 5, which I thought would be an unusable upper bound for the setting. I was wrong. 

I think it is much safer to let the user set this value to their liking. It only has to be set once per installation.

The issue is really in WebView component not handling hidpi displays. I can only hope that it gets fixed along with other bugs in the implementation.

**Comment by mmagyar** [comment]
@vsch As a read in #27 5 is just a number for presentation maybe. But for normal use it's the same as on Linux. 
But It's just an idea, i can see that it's impractical since JetBrains' IDEs are still have some problems with HiDPi resolutions.

There is a switch in the .vmoptions files to run it in "hidpi" mode (2x scaling). It would be nice if you could query if that option is set, and set the plugin accordingly. 
I read somewhere that it's being deprecated. But it's still required in Ubuntu.

**Comment by vsch** [comment]
@mmagyar I will put it on the back burner until more pressing issues and features are addressed.
