### ISSUE TITLE
Support for Admonition in Preview

### ISSUE THREAD

**Issue by Urs-Meili-CLX** [vsch/idea-multimarkdown#562]
Hi,
is there any way to show Admonition in the preview window? See
https://squidfunk.github.io/mkdocs-material/extensions/admonition/

**Comment by vsch** [comment]
@Urs-Meili-CLX, thank you for bringing this extension to my attention. I could not take by eyes off the eye candy implementation. I think it is an amazing extension to add.

I have been wanting to add an extension for doing exactly that but did not have the imagination to come up such an orthogonal, flexible syntax with an excellent implementation.

I will have to first add this extension to [flexmark-java] markdown parser that the plugin uses. I added it to its to do list, vsch/flexmark-java#208.

I will see if I can add it into the next release.

[flexmark-java]: https://github.com/vsch/flexmark-java

**Comment by Urs-Meili-CLX** [comment]
that sounds great, looking forward to it!

**Comment by vsch** [comment]
@Urs-Meili-CLX, you had to go and make me see this extension. I got the CSS and images done so that now I can move on to parser implementation. That is the easy part. Afterwards I need to add completions, formatting, options, syntax highlighting, a Darkula version of the stylesheet, etc. It is ton of small details to make it fully work in the IDE, but I will make it into one of the first EAP releases after 2.5.0 is out in a week or so.

Here is the look so far:

<img width="470" alt="screen shot 2018-02-23 at 11 24 54 pm" src="https://user-images.githubusercontent.com/10299086/36626240-64d302fc-18fd-11e8-80e1-3904578b50a8.png">

**Comment by Urs-Meili-CLX** [comment]
oh I didn't want to cause you so much work, sorry :-)

**Comment by vsch** [comment]
@Urs-Meili-CLX, I was being sarcastic. I am thankful that you brought this extension to my attention. It has been two years that I wanted something that would give me this functionality for documentation and communications.It makes it easier to include block-content.

Too bad GitHub does not support this. It would be great if it was available at least for the wiki.

**Comment by Urs-Meili-CLX** [comment]
I was being sacrastic, too ;-)

Get Outlook for Android<https://aka.ms/ghei36>




On Sat, Feb 24, 2018 at 3:10 PM +0100, "Vladimir Schneider" <notifications@github.com<mailto:notifications@github.com>> wrote:


@Urs-Meili-CLX<https://github.com/urs-meili-clx>, I was being sarcastic. I am thankful that you brought this extension to my attention. It has been two years that I wanted something that would give me this functionality for documentation and communications.It makes it easier to include block-content.

Too bad GitHub does not support this. It would be great if it was available at least for the wiki.

**Comment by vsch** [comment]
@Urs-Meili-CLX, could not wait for next release to get this done so I can use it with my e-mail communications and HTML generated docs. Thank you for bringing it to my attention.

EAP update with a fix for the issue is available.

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by Urs-Meili-CLX** [comment]
I downloaded the EAP, but the "Admontion" checkbox is grayed out. Do you have an idea, why?

![image](https://user-images.githubusercontent.com/29592407/37023320-ccbf954e-2125-11e8-9f25-8d9d468606d2.png)

**Comment by vsch** [comment]
@Urs-Meili-CLX, cut and paste issue. Enable  the Attributes extension and Admonition will be enabled.

I fixed this for next EAP.
