### ISSUE TITLE
Refresh preview

### ISSUE THREAD

**Issue by Urs-Meili-CLX** [vsch/idea-multimarkdown#563]
Hi Vladimir,
I have included several .png files in my markdown. I updated one of the .png files outside the IDE. After that, I didn't find a way to update the preview pane to show the updated content of the .png file.  Not even after closing and reopening the .md file in the IDE (Rider). The only way I found is to close and reopen the IDE itself, but this is not very handy... Could you perhaps include a simple "Refresh preview" button or so? Or did I miss something obvious?

Thanks & keep up the good work!
Urs

**Comment by vsch** [comment]
@Urs-Meili-CLX, WebView caching hell. 

I don't know who thought it was a good idea to implement the cache without checking for content change or exposing an API to flush it or even customize it but this is a PITA problem.

Turn on the query suffix. It will change the URL as it appears to WebView so it will think it is a different file. It will cause WebView to slowly, or not so slowly to hog memory since it will cache each new version of the file.

<img width="1063" alt="screen shot 2018-02-24 at 3 14 10 pm" src="https://user-images.githubusercontent.com/10299086/36634637-82b3570e-1975-11e8-9c08-14108894484a.png">

**Comment by Urs-Meili-CLX** [comment]
that was a quick response :-) thanks, I was looking for a similar option in the "preview" pane, but not in "HTML generation".

**Comment by vsch** [comment]
@Urs-Meili-CLX, all these real life kludges are starting to take their toll on my productivity. Getting to a point where the number of details to keep in mind is overloading my capacity. Probably time to refactor the code after this release or maybe find real solutions some workarounds.
