### ISSUE TITLE
Some problems with "Copy / Drop Image" dialog

### ISSUE THREAD

**Issue by Urs-Meili-CLX** [vsch/idea-multimarkdown#564]
Hi Vladimir,
when I have a .png in the clipboard and press Ctrl+V, the  fabulous "copy / drop image" dialog pops up. Love this one! But there are two problems:
- the directory is set to some arbitrary temp dir (in Rider IDE at least). I can change it to some directory within the project, but when I use the dialog once again, it is set back to that useless temp dir.
- It would be nice if the default file name would be something like "current-header-text_1" or so (instead of just "snapshot_1"), since the chances are there I would name it similarly to the current header (where the focus is). 
- BTW the "generate" button seems to do nothing.

Best regards,
Urs

**Comment by vsch** [comment]
@Urs-Meili-CLX, I will check the algorithm for determining the default directory. I don't remember how it determines it but think it looks for directories which contain images. I think it should look for images in the current file and take directories from that, add to it directories of images in other files in the same directory as the current file. Failing to find a default it should do what it is doing now.

There are a few annoyances with this dialog. I did not get a chance to polish some of its rough spots. It still annoys me when I use it, which is a good indicator it isn't done.

**Comment by Urs-Meili-CLX** [comment]
well I guess the best solution for the directory would be to save the directory the user has set as default directory, abandoning all sophisticated algorithms from that point on.

**Comment by vsch** [comment]
That would have to be done by file's parent directory or even by file. On a larger project you could be jumping all over the place and groups of files will have their own. I did not take a loot at this since I implemented it. So it is most likely not well thought through or even has minor bugs causing it to give the wrong directory.

**Comment by vsch** [comment]
@Urs-Meili-CLX, had to check what the generate button does. It checks for the file name already existing in the selected directory and appends _# where # is the smallest integer that will produce a unique file name. This is usually invoked automatically so the name that is there has already been generated. It will strip off the _# suffix before trying to generate a file. So if there is no _# suffix then there is no conflict.

It is intended, if I remember right, to generate a unique name if you edit the default file name.

As for the default file name and directory I will have to think this through a bit and maybe add options or give you the ability to specify how you want these defaults determined.

I can see where naming it based on the closest previous header text is a good idea for some applications. In other cases a default name template should be an option.

I originally added ability to paste images because I do a lot of screenshots in documentation and communications and got tired of copy, go into paint app, change resolution, save. Go back to the IDE and try to find where I saved it so I can link to it. 

You are the first user to give me feedback on your use case. If I don't get feedback I think that either no one is using it or they are OK with the way it is.

**Comment by vsch** [comment]
@Urs-Meili-CLX, EAP with fixed released.

* Fix: #564, Some problems with "Copy / Drop Image" dialog. Modify image directory history drop
  down to include, in order of priority:
  * last used image directory of the current file
  * image directories of images in the current file, ordered by count of occurrence
  * image directories in the current project, ordered by count of occurrence

I think this will give the best ordering of history drop down and default directory since the default directory is now the last used directory in the current file.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by Urs-Meili-CLX** [comment]
thanks @vsch, I'll look into it as soon as I get to edit a markdown file the next time :-)
