### ISSUE TITLE
IDE freezes when opening any markdown file

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#565]
With latest version of IJ and the plugin on macos 10.13.3, the IDE is freezing more or less always (8 out of 10) when opening a markdown file while using the javafx preview mode. From the logs this might be relevant:
```
"AWT-EventQueue-0" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: WAITING
 on java.util.concurrent.CountDownLatch$Sync@2a4dee35
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at com.sun.javafx.application.PlatformImpl.runAndWait(PlatformImpl.java:337)
	at com.sun.javafx.application.PlatformImpl.runAndWait(PlatformImpl.java:307)
	at com.vladsch.idea.multimarkdown.editor.javafx.JavaFxHtmlPanel.<init>(JavaFxHtmlPanel.kt:155)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.vladsch.idea.multimarkdown.editor.javafx.JavaFxHtmlPanelProvider.createHtmlPanel(JavaFxHtmlPanelProvider.kt:87)
	at com.vladsch.idea.multimarkdown.editor.PreviewFileEditorBase$setUpPanel$1.run(PreviewFileEditorBase.kt:444)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:246)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:417)
	at com.intellij.util.Alarm$Request.access$700(Alarm.java:344)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:384)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.j(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

When using the JB provided markdown plugin with the fx preview.

**Comment by vsch** [comment]
@holgerbrandl, could you post the stack trace for the JavaFX Application thread. The AWT-Thread is waiting for the JavaFX initialization to complete and it seems that the JavaFX initialization is blocked.

I will try running it on High Sierra to see if I get the same issue.

**Comment by holgerbrandl** [comment]
Thanks for looking into it:

```
"JavaFX Application Thread" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
	at sun.lwawt.macosx.LWCToolkit.$$YJP$$doAWTRunLoopImpl(Native Method)
	at sun.lwawt.macosx.LWCToolkit.doAWTRunLoopImpl(LWCToolkit.java)
	at sun.lwawt.macosx.LWCToolkit.doAWTRunLoop(LWCToolkit.java:1022)
	at sun.lwawt.macosx.LWCToolkit.invokeAndWait(LWCToolkit.java:837)
	at sun.lwawt.macosx.LWCToolkit.invokeAndWait(LWCToolkit.java:790)
	at sun.lwawt.macosx.LWCToolkit.invokeAndWait(LWCToolkit.java:585)
	at sun.lwawt.macosx.CAccessibility.invokeAndWait(CAccessibility.java:90)
	at sun.lwawt.macosx.CAccessibility.getAccessibleIndexInParent(CAccessibility.java:298)
```
But since I'm not sure if I picked the right one, I've zipped one of the freeze folders from the log directory and deposited it under  https://cloud.mpi-cbg.de/index.php/s/IsWRolSKntmiDGe

**Comment by vsch** [comment]
@holgerbrandl, having all the thread dumps is perfect. Thank you.

**Comment by vsch** [comment]
@holgerbrandl, finally got JavaFX WebView preview not crashing the IDE under parallels running OS X 10.13.3. It was crashing consistently as soon as JavaFX WebView creation was attempted. With Markdown Support from JetBrains too. Had to switch JDK to Oracle 8u161 before it worked. Seems there is something in the bundled Open JDK with JavaFX for my setup for high sierra, at least under parallels.

I think I figured it out. I changed the code a while back to wait for the JavaFX initialization to complete to avoid occasional webview engine not yet initialized errors. This works well except if accessibility is enabled because then the JavaFX thread waits on AWT thread, resulting in dead lock.

I will change the code to what it was before and live with occasional initialization lag errors instead of deadlocking when accessibility is enabled. Too bad, it works very well otherwise. :)

I was able to duplicate this by turning on voice over. With voice over turned off, everything works without deadlock.

**Comment by holgerbrandl** [comment]
Thanks for tracing down the problem. Looking forward to the fix in the dev channel.

**Comment by vsch** [comment]
@holgerbrandl, EAP updated. Previous fix reversed.So it should work as before. Thank you for reporting it.

**Comment by holgerbrandl** [comment]
Great, thanks! I've installed the EAP build and it's back to 'normal'.

**Comment by vsch** [comment]
@holgerbrandl, thank you for the feedback. Much appreciated.

**Comment by holgerbrandl** [comment]
Not sure if it's related to this ticket but the IDE is crashing again 100% of the time (since yesterday on EAP channel) when opening a md file when the javafx preview mode is selected.

IntelliJ IDEA 2017.3.5 (Ultimate Edition)
Build #IU-173.4674.33, built on March 5, 2018
JRE: 1.8.0_152-release-1024-b15 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.3

plugin version: 2.5.2.6

logs:
[threadDump-20180327-100922.txt](https://github.com/vsch/idea-multimarkdown/files/1850993/threadDump-20180327-100922.txt)

**Comment by vsch** [comment]
@holgerbrandl, on High Sierra JavaFX WebView crashes for 2018 EAP when the bundled JDK is used. Switching the IDE boot JDK to Oracle JDK solves the issue.

Something in the bundled JDK JavaFX WebView is broken on High Sierra for 2018 releases.

The crash occurs in the native libraries and there is nothing the plugin can do except try to detect if it is a problem version and not try to use JavaFX WebView.

**Comment by vsch** [comment]
@holgerbrandl, I only have high sierra on Parallels desktop. My dev machine is still sierra. So I can't say if the issue on my system is a Parallels problem or also affects main installation.

Can you try disabling Markdown Navigator and enabling Markdown Support and see if the same issue exists. When I did that Markdown Support also crashed the IDE.

If you have the crash with Markdown Support then I suggest opening an issue on YouTrack. 

I would open an issue but since I can only duplicate the issue under parallels, it is not indicative of main installation and I am not sure it will get the priority if it is reported for the main installation.

**Comment by holgerbrandl** [comment]
As pointed out in the version info, I'm still on the 2017.3.5. 

Markdown Support  seems fine with javafx preview being enabled.

Nots sure if it helps the MD plugin worked until very recently (yesterday), and I have not installed any platform update since then.

**Comment by vsch** [comment]
@holgerbrandl, sorry I missed the IDE version.

The thread dump does not show much. The JavaFX WebView initialization is waiting on condition in a native method waiting for JavaFX initialization.

Did the crash start after you installed 2.5.2.6 yesterday or has anything else changed on your system? 

I want to understand where to start looking. I have not made changes to JavaFX since the previous fix. The fixes were made to spell checking for basic version.

**Comment by holgerbrandl** [comment]
I'm not aware of any changes since yesterday. Except for plugin updates, which are constantly coming in.

Is there a way for me to roll back the MD EAP to the previous version? Just to narrow down the suspect list.

**Comment by vsch** [comment]
@holgerbrandl, the dist directory in this repo has all versions: https://github.com/vsch/idea-multimarkdown/tree/master/dist, you will need to download and install from disk. However, if you did not update MN yesterday it may not help.

I looked through the change list and 2.5.2.4 had a fix for JavaFX download files for Android Studio, it does not affect JetBrains IDEs since JavaFX is part of the bundled JDK and no download of JavaFX support files is attempted.

I will try 2017.3.5 on High Sierra to see if it has an issue on my system.

**Comment by vsch** [comment]
@holgerbrandl, I tried 2017.3.5 on High Sierra under parallels. I also get IDE crash with bundled JDK with JavaFX WebView.

When Markdown Support JavaFX WebView rendering is enabled and the IDE restarted, it also crashes if the bundled JDK is used.

The crash does not occur when the JavaFX WebView is enabled until the IDE is restarted. 

Switching the boot JDK to Oracle 1.8.0u161 solves the problem for 2017.4.5 also. 

Do you get a crash or just freezing?

**Comment by holgerbrandl** [comment]
I think "just" freezing, that is spinning wheel until eternity.

I've tried to run it with 1.8.0u162 but then it keeps freezing without any markdown by simply editing some kotlin source code. So I guess I'm tied to the bundled JDK.

**Comment by vsch** [comment]
@holgerbrandl, I am really curios to find out what changed to cause this issue. I cannot test High Sierra because parallels has issues with it and I am not ready to upgrade without being sure I won't be dealing with a bunch of compatibility issues with my system.

**Comment by holgerbrandl** [comment]
I think I'll report it to jetbrains if I can narrrow it down a bit further. Working with the oracle jdk is supposed to work.

**Comment by vsch** [comment]
@holgerbrandl, one last check to try before you file an issue. In my experience IDE's that were patched for several version sometimes get corrupted. This applies to IDEs that are not managed by JetBrains Toolbox. I had an IDE that was patched by several upgrades and I was getting all kinds of mysterious exceptions and failures. I uninstalled and re-installed the final version to get rid off all the patched files and it solved my problems.

If you are using an IDE managed by JetBrains Toolbox this does not apply because it downloads and installs the full version every time.

**Comment by holgerbrandl** [comment]
Maybe this was the problem.

I've updated to v2018.1 this morning by doing a fresh installation. And luckily MN plugin is working again with javafx preview being enabled.

So all good for now on my end. :-)

Thank you very much for your kind support.

**Comment by vsch** [comment]
@holgerbrandl, I am sure if you install 2017.3.5 from scratch it will work too. I use 2017.3.5 and 2018.1 EAP all the time. It was 2017.3.5 which was patched over several months from 2017.1 that was causing my problems.

2018.1 EAP has an issue of not properly saving rendering profiles (other than the project profile). If you are using scoped profiles with customized CSS text or customized HTML text then this text will be reset to empty every time you open the project: https://youtrack.jetbrains.com/issue/IDEA-184506

**Comment by holgerbrandl** [comment]
Since it is working now, I hope you understand that I will just proceed without testing old releases.

I've never used a rendering profile, and I don't want to miss partial git commits which are such a wonderful  feature in 2018.1, so I guess I'll stick with it.

I voted for your ticket nevertheless. :-)

**Comment by vsch** [comment]
@holgerbrandl, thank you for the vote.

I use profiles all the time to convert markdown to HTML included in the plugin and documentation in other projects. For me this bug caused me not to use 2018 for a long time. I finally filed the bug, spent a lot of time trying to isolate the conditions and finally debugged and posted a patch.

Since then 3 EAP releases have been released and I suspect that the final release will also not have the bug fixed. Not an issue for me because I wrote bash patch scripts for all the products I use. Others will loose their customization profiles.

I don't know why it takes so long to incorporate the fix but it is the reason why I don't bother reporting bugs unless they are show stoppers for me. It takes too long, the boiler plate response is denial of the problem, especially when it comes from a "third party plugin". Finally it takes forever to get the fix into the product.

I love the IDEs and can't work without them. Support quality and attitude varies on the contact person. Some are a pleasure to deal with. Amazing professionals with guru level knowledge. Others act like government bureaucrats and trigger my Tourette's. :)

**Comment by holgerbrandl** [comment]
Yeah sometimes it takes an eternity... My "favorite" eternal ticket filed back in 2016 is https://youtrack.jetbrains.com/issue/KT-15019
:-)

**Comment by KartaviK** [comment]
Have same problem with Markdown support plugin.
OS: Ubuntu 19
Phpstorm: 2019.1.3

After switching to Markdown navigation all works fine

**Comment by vishal786btc** [comment]
Same Issue as above. I switched from markdown support to markdown navigator from Vladimir. It worked.
OS: Windows10
Pycharm: 2019.1.3

**Comment by vsch** [comment]
Thank you for the encouraging feedback.

Wait till you try the next version. It is ultra fast compared to previous releases and has a ton of bug fixes, including some intermittent ones that I could not reproduce for two years.

I cannot wait to have an EAP release so others can enjoy the speed gain and performance, while I take a short break to catch up on sleep. 😄
