### ISSUE TITLE
Enhancement: support for restructured text

### ISSUE THREAD

**Issue by neoaddix** [vsch/idea-multimarkdown#568]
Hi @vsch ,

Some time ago I bugged you about adding a support for Jekyll and you picked that up very nicely. It seems that there are people enjoying this support.

Meanwhile, the company I work for switched from using Jekyll to using Sphinx docs (http://www.sphinx-doc.org/) for creating our software documentation. Sphinx is based on restructured text. It is possible to use markdown, but the possibilities are much better when using restructured text. 

Now, since I was already using your plugin, I tricked IntelliJ and the plugin by saying that *.rst files are of the format markdown. This gives me some limited advantages in combination with your plugin. Both restructured text and markdown are pretty close in terms of syntax.

Because of that, I began to wonder if it would be feasible to add restructured text support to your plugin? A lot of formatting is more or less the same, restructured uses directives that are not used in markdown, hopefully parsing them is doable. I don't know, your thoughts on this are much appreciated.

And of course, I'm silently hoping that restructured text users might read this and maybe support my wish!

Keep up the great work

Jeroen

**Comment by vsch** [comment]
@neoaddix, I took a look at restructured text. The differences in syntax and elements are fairly major. The overlap is only in inline markup and a partially on lists. The rest is quite different.

If I were to work on it, it would need to be its own plugin, with its own parser and integration with the IDE since the current plugin is aimed at CommonMark and Markdown and the plugin is already complex enough with all the markdown options. Adding a completely new language would make it unmaintainable.

The effort would be less than creating the Markdown Navigator plugin from scratch since I already have a working implementation and don't need to figure out how to get things done in JetBrains Open API. However, it would be a reimplementation of most of the functionality specific to restructured text elements and idiosyncrasies. Including figuring out all the nuances of restructured text itself.

The Markdown Navigator plugin is 100k source lines of plugin plus another 75k source lines of parser and extensions. I would guess that restructured text would be on the same order of complexity and size. BTW, these are source code, comment and blank lines excluded.

To be honest, I don't have the time in the near future to work on this. I still have at least one major refactoring job in Markdown Navigator before I would even consider working on a major new plugin.

I do see that there could be a substantial demand for restructured text, especially for PyCharm and other python users. I will weigh the effort vs potential payoff as a longer term project consideration.

**Comment by neoaddix** [comment]
Thanks for the extensive answer and for looking into this. For me as a user things looked pretty related, but the devil is in the details of course. If you ever consider to start the project, let me know if I can help!

**Comment by vsch** [comment]
@neoaddix, yes the elements are pretty similar but the implementation in the IDE is really language syntax and semantics specific. It is not a trivial effort to make it all work. Kludges abound especially for loose text formats. 

To be frank, if I knew what I was signing up for when I embarked on this journey, I probably would not have done it. The saying: "Fools rush in where angels fear to tread." fully applies to me in this case.
