### ISSUE TITLE
Broken Spell Checker

### ISSUE THREAD

**Issue by marekoti** [vsch/idea-multimarkdown#575]
The built-in IntelliJ spell checker is not working inside md files. Interestingly it's working but just in header's text. It's working just fine in any other files, including newly created plain .txt files. Version used (the most recent one as of today): 2.5.2.

**Comment by marekoti** [comment]
After switching off the Markdown Navigator plug-in spell checking works a treat. Likewise when using IntelliJ's plug-in for markdown.

**Comment by vsch** [comment]
@marekoti, can you please give more information on the IDE and version that you are using and the operating system. I tested it with IDEA 2016.3.8, 2017.3, 2018 EAP, Php 2018 EAP, WebStorm 2018 and all work.

**Comment by marekoti** [comment]
Oh good point, sorry forgot to mention that. I'm on the latest stable version of Android Studio, i.e. 3.0.1, which is based on IntelliJ IDEA 2017.1.2.

**Comment by vsch** [comment]
@marekoti, thank you for the feedback. I will have to try it on Android studio. Although it is based on IDEA 2017.1.2, it could have made changes to some internals that affect plugin implementations.

I encounter such changes from version to version of JetBrains IDE releases so would not be surprised if the same applies to Android studio.

Looks like I will need to add Android Studio to my testing platform list.

**Comment by marekoti** [comment]
Technically Android Studio is just a plugin for IntelliJ, not a fork, at least that's how it was described at its launch: https://blog.jetbrains.com/idea/2013/05/intellij-idea-and-android-studio-faq/
I also don't think it provides any specific support/behaviour for md files. Hence I wouldn't expect it to be Android Studio specific.

**Comment by vsch** [comment]
@marekoti, often in software the marketing glossy differs from implementation reality. 

I installed Android Studio 3.0 and can already see that JavaFX support in the plugin has issues. On my system it tries to download JavaFX support (implemented for very early JetBrains bundled JDKs) which should not happen for Android studio. This causes JavaFX to fail.

I will debug the plugin under Android studio to check for differences.

Spell checking, however is working on my system.

**Comment by marekoti** [comment]
Can that JavaFX issue be anyhow related to the spellchecker issue I'm experiencing? Could any more information like logs etc assist with investigation? Please see the screenshot below showcasing the problem:
![markdownnavigatorspellcheckerbug](https://user-images.githubusercontent.com/37408245/37723071-6739d6c4-2d25-11e8-9ca5-287b8d87ea88.png)

**Comment by vsch** [comment]
@marekoti, no the javafx is related to lack of scroll preview to source position.

However, the screenshot is showing that spell checker is working. It is showing an error. If you open the yellow bulb for intentions, does it show the Typo: Rename To: intention?

**Comment by marekoti** [comment]
Well no, it's not working mostly, as mentioned in the bug description it's only working for headers. As you can see exactly the same tyypo is not highlighted above in the paragraph text.

**Comment by vsch** [comment]
@marekoti, I released an EAP plugin version to fix the erroneous detection of JavaFX for Android Studio which does not have javafx and the download attempted by the plugin is for an old release of IDEA, which does not work for Android Studio.

The spellchecking works with exact text used as far as I can see in the snapshot.

<img width="326" alt="screen shot 2018-03-21 at 3 34 07 pm" src="https://user-images.githubusercontent.com/10299086/37733153-949066cc-2d1d-11e8-8f6a-e38dd4387915.png">

There must be some other difference or setting that would be causing the issue on your system. You can try the EAP version to see if it makes a difference but I suspect that this issue is from something else that I have not been able to duplicate yet.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by marekoti** [comment]
Installed the EAP version, unfortunately that hasn't fixed the spellchecking issue I'm experiencing. I've checked with your settings and they look pretty much the same as mine. I haven't changed anything, basically it's both fresh installation of Android Studio on a new Ubuntu machine and fresh installation of Markdown Navigator. The only difference is that I see "Installed version: 2.5.2.4" and some options are not available for me as I haven't upgraded yet to the paid license (indeed that issue is stopping me from upgrading). Please let me know if you need more info from me. In the meantime thought that those details from the About dialog of my Android Studio could be useful:
Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b01 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.13.0-37-generic

**Comment by marekoti** [comment]
Nice one, glad that we got to the bottom of the issue! Good luck with the fix! Do you know which was the last working version? In the meantime I may use it.

**Comment by vsch** [comment]
@marekoti, being able to duplicate the symptom is 90% of the problem resolution.

Give me a few more minutes and I will make an EAP release. I already have it fixed.

<img width="339" alt="screen shot 2018-03-22 at 12 57 39 pm" src="https://user-images.githubusercontent.com/10299086/37785525-c2e2aef0-2dd0-11e8-9433-d886cd947045.png">

**Comment by vsch** [comment]
@marekoti, EAP update with a fix for the issue is available.

**Comment by marekoti** [comment]
It works now but correcting typo doesn't work (no matter if used through `context menu/refactor/rename`, the light bulb or `alt+enter`) -- please see the attached screenshot. Also the spellchecker is very slow. It takes a few (~6) seconds for it to change upon both creating and correcting a typo. That shoudn't matter but I tested it in a small doc (<1k chars). IntelliJ's Markdown Support plugin is nearly instant with spellchecking. Until those two issues are fixed, I will stay using the IntelliJ's plugin.
![cannotperformrefactoring](https://user-images.githubusercontent.com/37408245/37824091-742664ec-2e83-11e8-898d-dbc5d68a42e8.png)

**Comment by marekoti** [comment]
OK regarding the performance, probably a more through tests/comparison should be conducted as actually I can observe even the simple Markdown Support plugin from IntelliJ, having locationally a few seconds lag. Still most of the time it is nearly instant. I haven't thoroughly tested Markdown Navigator, but just checked a few times that one typo example and was observing ~6s lag for that case.

**Comment by vsch** [comment]
@marekoti, the spell checking highlighting is performed after syntax highlighting. If you change the syntax highlighter to Lexer then it will happen as you type. Lexer set to annotator adds a delay for syntax highlighting but allows better typing response in large files.

![screenshot_settings_syntaxhighlighter](https://user-images.githubusercontent.com/10299086/37830089-cda2a67c-2e77-11e8-974a-4316393481a7.png)
 
Still trying to duplicate your inability to use correction. So far no luck. **However, why are you getting "rename/refactoring" since the type is not an element that can be renamed. You should see a `Typo: Change to:` not `Typo: Rename to:`** This is the problem. Text cannot be refactored since it is not a named element.

<img width="547" alt="screen shot 2018-03-23 at 8 58 57 am" src="https://user-images.githubusercontent.com/10299086/37830415-887cfe16-2e78-11e8-9076-87f5b9d804ad.png">

<img width="396" alt="screen shot 2018-03-23 at 8 59 33 am" src="https://user-images.githubusercontent.com/10299086/37830419-8b4f0d8c-2e78-11e8-9c9f-151701406f3f.png">

**Comment by marekoti** [comment]
OK maybe it's related to the fact that earlier I've as well installed RedPen, Thesaurus, and Gfm plugins? I'm pretty sure I was testing with them disabled as well and observed the same. Maybe restarting with clearing caches would be needed? When it comes to the RedPen plugin I had to download it directly from IntelliJ page as weirdly it didn't work from the IDE itself.

**Comment by vsch** [comment]
@marekoti, depending on how plugins implement their functionality, it is possible for plugins to conflict and cause issues because the API is huge and usually assumptions are made or guessed at how it is used. Often this assumption is too simplistic. 

I have hit on this reality many times. Additionally, the IDE does have bugs and these also add to the failures, which are readily blamed on the plugin that exposes it because statistically, it is most likely a plugin issue but not always. :)

**Comment by marekoti** [comment]
I understand that. Please let me know if there's anything I can do to help with the investigation.

**Comment by manovotny** [comment]
@vsch I wound up here with the same problem. Updating to the EAP brought back the squiggly underline, but I too could not cannot get `Alt + Enter` to work for suggestions.

![correct-spelling-alt-enter](https://user-images.githubusercontent.com/446260/40807266-6e9575da-64e9-11e8-95da-49615d9efa4a.gif)

This was happening on version 2.5.2.20 of Markdown Navigator using IntelliJ IDEA Ultimate 2017.3.4 (Build #IU-173.4548.28).

However, when I updated to IntelliJ IDEA Ultimate 2018.1.4 (Build #IU-181.5087.20), `Alt + Enter` started to work for me again. 🎉 

I don't know if this helps isolate an issues with older versions of JetBrains projects, but it's working for me again now being on the latest of everything, which makes me really happy! 😊 

Please let me know if you need any additional information from me or if there is anything else you'd like me to try so I can help isolate the issue for you further, if needed.

**Comment by vsch** [comment]
@manovotny, thank you for letting me know. I will try it on an older version. I have 2016.3.8 and 2017.3. installed.

There are so many changes between versions of the IDE and types of IDE that I cannot keep up with the "idiosyncrasies". It is also getting harder to support older versions since 2018.1 has a lot of changes and more coming in 2018.2, some of which are breaking changes. Meaning, I would either have to raise the version cut-off or have multiple versions of the plugin. One for older IDEs.

**Comment by vsch** [comment]
@manovotny, thank you for the kind words. 

I have to admit that I enjoy using the plugin myself. I set out to make my life documenting projects less tedious. I never imagined I could enjoy doing documentation.
