### ISSUE TITLE
Vertical split - preview does not scroll to source

### ISSUE THREAD

**Issue by MikeMitterer** [vsch/idea-multimarkdown#576]
V 2.5.2.2

Android Studio 3.0.1
Build #AI-171.4443003, built on November 9, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.11.6

**Comment by vsch** [comment]
@MikeMitterer, I will have to test it in android studio. So far I have been testing it only in JetBrains IDEs, where it does work.

To make sure are you using JavaFX WebView preview? Swing does not support scrolling preview to source.

**Comment by vsch** [comment]
@MikeMitterer, I released an EAP plugin version to fix the erroneous detection of JavaFX for Android Studio **which does not have JavaFX**. The download attempted by the plugin is for an old release of IDEA and does not work for Android Studio.

**This means by default JavaFX WebView preview cannot be used with Android Studio.**

I did try it with the bundled JDK that comes with IDEA Community Edition 2018.1 EAP and JavaFX works without throwing any exceptions.

Oracle JDK does work for the preview but some mysterious exceptions get thrown for the core IDE. Which leads me to believe that Oracle JDK cannot be used to run Android Studio on OS X.

**I don't use Android Studio so it makes it impossible for me to test whether using another JDK which has JavaFX would cause issues for Android Studio projects.**

I create a separate JDK in my `/Library/Java` directory which is based on the JetBrains bundled JDK with any missing files filled in from the Oracle JDK using a directory diff utility. This allows me to use the Bundled JDK as a self-standing JDK for my debugging, to allow testing against the same JDK as used by the non-debug environment and to enjoy the superior text rendering quality of the bundled JDK. I have an old post, [Creating a Bundled JDK With JavaFX for OS X ](https://vladsch.com/blog/12), about the difference in text rendering and creating a JavaFX enabled JDK for old releases, the latter part is dated and does not apply.

In previous releases you could specify the `application/Contents/jdk` as a Java JDK but in later releases the IDE does not recognize it as a valid JDK because some files are missing from the release to make it a full fledged JDK. Creating a copy of the bundled JDK directory and filling it in with missing files using the Oracle JDK gets around this limitation.

If you want to enable JavaFX in Android Studio you would need to:

1. copy the `/Applications/IntelliJ IDEA 2018.1 CE EAP.app/Contents/jdk` directory to the `/Library/Java` directory.
2. rename it to something like `openjdk1.8.0_152_release_1136` which is the build number on the latest bundled jdk
3. copy files from the same version Oracle JDK as the open jdk which are **missing** from the above directory and sub-directories. There are not many.
4. Change the Android Studio boot JDK to the newly created JDK. By pressing Shift+Option+Cmd+/ on OS X and choosing the `Switch Boot JDK...` menu option or by going deeper into the configuration files  [Changing Boot JDK](https://github.com/vsch/idea-multimarkdown/wiki/Changing-Boot-JDK)
5. Test your real projects to see if it causes issues in Android Studio.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)
