### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by gonciarz** [vsch/idea-multimarkdown#579]
Hi, recently I opened a performance issue (memory leak) for Intellij.
https://youtrack.jetbrains.com/issue/IDEA-189994

As a result of JetBrain team investigation, they said that the problem may be connected with Markdown Navigator.
Please contact JetBrain support to share my heapDump and jstack results:
be0f3434c845f5d9c0ca25e80d4b863c heapDump-intellij-idea-1523388452030.hprof.zip
7b57930af2a34fee066868ba3b88f5bd jstack.tar.lzma

Best regards

**Comment by vsch** [comment]
@gonciarz, thank you for reporting it. I will take a look at the issue.

**Comment by s-nel** [comment]
I'm experiencing this issue as well. If it helps, my markdown file is [here](https://github.com/s-nel/rfcs/blob/ba0f9661b1755851dd21e1cd2d8def50573788fd/text/0000-navigate-to-url.md)

After opening the markdown file and editing it for 10-15 minutes I get an out of memory exception in WebStorm.

I'm using Mac OS X and WebStorm 2017.3.5

**Comment by vsch** [comment]
@s-nel, thank you for the sample.

Can you do me a favour and try editing the same file but with the HTML image with width/height changed to markdown image link. The image will not display the right size but I suspect that this may resolve the issue with WebView cacheing the resized image every time instead of just once.

JavaFX WebView has an internal cache implementation which saves everything from the big-bang till the end of time and the only way to reset it is to close the IDE to unload the JavaFX library. If the sized image causes a new instance of the resized image to be cached then this would cause the memory leak.

**Comment by vsch** [comment]
@gonciarz, @s-nel, I think this one is finally fixed for next release. #710 brought to my attention the  message bus registration which I completely missed as an external reference to the instance which would keep it alive for the life of the project.

Fixed for next release along with other bad old bugs and performance issues. I will post when an EAP with the fix will be available.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
