### ISSUE TITLE
Unresolved link reference

### ISSUE THREAD

**Issue by ddnexus** [vsch/idea-multimarkdown#583]
I have 3 files in a dir and I point to them with the following markdown:

```
  - [nav.html.erb](https://github.com/ddnexus/pagy/blob/master/lib/templates/nav.html.erb)
  - [nav.html.haml](https://github.com/ddnexus/pagy/blob/master/lib/templates/nav.html.haml)
  - [nav.html.slim](https://github.com/ddnexus/pagy/blob/master/lib/templates/nav.html.slim)
```
All 3 files are in the lib dir, but only the second is resolved to the actual file, the first and third are not. Why?

**Comment by vsch** [comment]
@ddnexus, I don't use ruby so I'll need to rely on your knowledge of specifics. Are the first and second some form of templating files?

Reason I ask, is I discovered recently that the IDE does not report extensions for template files, only their "last" extension, which it then refuses to recognize as the extension for the FileType for which it returned the extension. Effectively, the plugin does not see these files when it searches for possible files.

I have a fix but have not yet made an EAP release.

**Comment by ddnexus** [comment]
Yes, they are all template files. The weird thing is that they should have all the same problem, but only the 1st and 3rd have it.
It looks like it gets confused by the multiple suffixes, but again the second one works, which could reveal a different problem or some sort of workaround. What do you think?

**Comment by vsch** [comment]
@ddnexus, depends on how the extension is coded in the IDE, if it is defined as ".haml" then it will be recognized. If it was ".html.haml" it won't because the IDE will return its extension as ".haml" but when asked to give the file types for ".haml" will not return this file type.

The fix ignores the API and asks for a list of file associations and hacks on that to finds all the file types that end in the desired extensions.

**Comment by vsch** [comment]
@ddnexus, I had this problem with PHP Blade files. Drove me nuts because I was looking for a bug everywhere else in my code. Finally traced it to obtaining a list of file types for an extension. I can make an eap release because the bug also affects completions. None of these affected file types will show up for completions.

**Comment by vsch** [comment]
@ddnexus, please let me know if the fix works for you or if it is another issue.

EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by ddnexus** [comment]
:1st_place_medal: Yes sir! This definitely fixed it!
