### ISSUE TITLE
"Create directories and folder" does only create directory on first hit.

### ISSUE THREAD

**Issue by josefglatz** [vsch/idea-multimarkdown#590]
On 2nd hit: creates the file.

Could that be consolidated into just one click? The "bug" turns up to me in the licensed version.

**Comment by vsch** [comment]
@josefglatz, is this bug triggered by an intention to create a file?

**Comment by vsch** [comment]
@josefglatz, never mind. I tested it and the answer is yes. 

I'll fix it.

**Comment by vsch** [comment]
@josefglatz, EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)
