### ISSUE TITLE
uncomment does not remove leading space

### ISSUE THREAD

**Issue by K4zuki** [vsch/idea-multimarkdown#591]
### Conditions

- Windows7 x64
- PyCharm Community 2017.3.3
- Markdown Navigator 2.5.2

***

### What I did and what happend
type a line, and make it single line comment like this:
```html
<!-- This is a comment -->
    ^
```
and then uncomment. What is expected(what it was) is:
```html
This is a comment
^
```
but actually:
```html
 This is a comment
^
```
and again comment:
```html
<!--  This is a comment -->
    ^^
```
and uncomment:
```html
  This is a comment
^^
```

***

Is this the IDE issue or the plugin issue?

**Comment by vsch** [comment]
@K4zuki, this is caused by the plugin defining comment start/end as `<!-- ` / ` -->`for purposes of insertion and `<!--` / `-->` for detection and removal.

**Comment by vsch** [comment]
@K4zuki, EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by K4zuki** [comment]
Thanks! fix confirmed.
