### ISSUE TITLE
Indent level doesn't affect code blocks

### ISSUE THREAD

**Issue by C0deboy** [vsch/idea-multimarkdown#592]
Indent size is set to 2. Both optionts "Minimize code indent" checked. But it doesn't affect autoformating. For example:

```

> ```java
> public final class Task {
>     private String name;
>     private String description;
> 
>     public void someMethod() {
>     }
> }
> ```

```

Remains untouched. But I expect it to change indent level to 2.

**Comment by vsch** [comment]
@C0deboy, indent is not used by the plugin because markdown and CommonMark has tab size defined at size 4. It was added to satisfy a user's desire to use tab key to insert 2 spaces, as opposed to hitting the spacebar twice. #466.

The plugin does not format injected languages in fenced code or indented code blocks. These are black boxes from the point of view of markdown and other than common leading indent that can be removed on formatting the reset is not touched.

The IDE language defined formatting can be applied if you edit the injected fragment in a separate window and invoke the format action in that window.

**Comment by C0deboy** [comment]
Yeah, I was doing it this way but I expected some kind of automation. But ok, I understand. Thanks for your response. I'm closing the issue.

**Comment by vsch** [comment]
@C0deboy, automation is great until it does not do what you want. In this case the amount of edge cases and states would make this feature untestable or debuggable.

You example is a complete class and in this case it would work as expected. Most injected code fragments are really fragments and then the IDE formatting can get very confused.

As a test remove the class opener/closer and the code in the fenced code block will run red with syntax errors. If you remove only the first line, it is still a valid fenced code block but no longer valid java, even for formatting.
