### ISSUE TITLE
Font when exporting to PDF

### ISSUE THREAD

**Issue by Urs-Meili-CLX** [vsch/idea-multimarkdown#597]
When I use the "Export to PDF" function, the text in the exported PDF is rendered in an ugly Times New Roman font. Is there any way to customize the font? Best would be if the PDF has the same font as the preview panel.

**Comment by vsch** [comment]
@Urs-Meili-CLX, PDF conversion uses its own fonts for conversion. The plugin uses Open HTML to PDF software library [https://openhtmltopdf.com](https://openhtmltopdf.com/). The plugin converts the markdown to HTML then passes it to the PDF converter for final PDF output.

The converter does not handle 100% browser compatible conversion, which means experimentation is needed to figure out what CSS options will work, but you can use custom Rendering profiles to customize PDF output.

You can setup scope based profiles (if these are available in your specific IDE) to customize the rendering down to file granularity. Custom profile settings are documented in: https://github.com/vsch/idea-multimarkdown/wiki/Rendering-Profiles-Settings

The default profile for PDF conversion uses the same compact CSS which is used for the `Copy Markdown as HTML formatted text` action which puts the markdown as HTML mime content on the clipboard. This CSS has all the properties defined for each element since HTML mime has to have the style of each element defined without a CSS. PDF does not have this limitation and the converter will do its best to figure out the CSS attributes. However, to make life easier and more predictable I used the same CSS for PDF as copy html formatted text.

For minor tweaks there are options for PDF export:

1. font family in Languages & Frameworks > Markdown

   For PDF export “Helvetica” works to select sans-serif font. I tried a few others but they did not work. By default for this setting is blank so that PDF export will use its own default. You can use the dropdown to select fonts available in the PDF

2. max width option for PDF export of 504pt is 7” wide is used, export library does not handle percent based max width settings.

**Comment by Urs-Meili-CLX** [comment]
Hi Valdimir,
setting PDF Export Font Family to Helvetica works fine, thanks.
Best regrads,
Urs
