### ISSUE TITLE
Add Support for GitLab README.md styling

### ISSUE THREAD

**Issue by snics** [vsch/idea-multimarkdown#599]
Hi, it would be nice if there was also a GitLab styling for the Markdown Preview like this: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/user/markdown.md

**Comment by vsch** [comment]
@snics, yes it is on the todo list #545. I just have to find the time to implement it.

First as GitLab specific extensions to [flexmark-java](https://github.com/vsch/flexmark-java) library, then add specifics to support JetBrains functionality where needed for the new elements.

**Comment by vsch** [comment]
@snics, added  [GitLab Flavoured Markdown](https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/user/markdown.md)
  parsing and rendering functionality
  * Math inline using ```$``$``` and fenced code blocks with info of `math` using
    [Katex](https://github.com/Khan/KaTeX)
  * Charts fenced code blocks with info of `mermaid` using
    [Mermaid](https://github.com/knsv/mermaid)
  * Ins/Del via `{++}` and `[++]`/`{--}` and `[--]`
  * Multi-line block quotes
  * Video image link rendering

This only applies to parsing and rendering HTML not the style sheet. Also link completions are GitHub like. The latter is for release 3.0.

EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)
