### ISSUE TITLE
Switch between Markdown preview and HTML preview

### ISSUE THREAD

**Issue by CGick** [vsch/idea-multimarkdown#601]
Hello Team,

I just started using your plugin with Pycharm, and I noticed that I was only able to use Markdown Support from JetBrain or your plugin not both. I was wondering if you have or plan to have a toggle between a Markdown preview and the HTML preview.

**Comment by vsch** [comment]
@CGick, you cannot have both plugins enabled because both provide an editor, highlighter and all other language related customizations.

What do you mean by "to have a toggle between markdown preview and HTML preview?"

Markdown Navigator has more options than Markdown Support for preview control and customizations, amongst other features. 

You can use the preview toolbar buttons for selecting the layout and content for the previews: <img width="207" alt="image" src="https://user-images.githubusercontent.com/10299086/40863107-b673ab32-65bc-11e8-8686-d60bc57aab3e.png">

**Comment by vsch** [comment]
@CGick, BTW, all toolbar button actions (and more) are available for shortcut assignment in settings > Keymap > plugins > Markdown Navigator

This way you can define your own shortcut keys for toggle action.
