### ISSUE TITLE
Cursor jumps out of fenced code block editing Python code

### ISSUE THREAD

**Issue by obestwalter** [vsch/idea-multimarkdown#602]
Hi @vsch, I noticed that when I am editing Python code in a fenced code block like:

    ```python
    def func():
       print()
    ```

When I press enter e.g. after the print() the cursor jumps upwards to the beginning of the fenced code block (so ot just before the "```"). Is that error known already?

**Comment by vsch** [comment]
@obestwalter, that was a bug in the JetBrains EAP stream that was fixed in later releases. 

I had the same issue and switched to an earlier version until it was fixed. It happened across the board in almost all the IDEs based on the same code version. I had it in IDEA, WebStorm and PhpStorm.

**Comment by obestwalter** [comment]
o.k. - i am using the newest release though (2018.1) do you meant it is going to be fixed in the upcoming 2018.2 release?

**Comment by vsch** [comment]
I had it in earlier 2018.1 EAP release. Have not encountered since. Let me try 2018.1 PyCharm to confirm.

**Comment by obestwalter** [comment]
I am on 2018.2

**Comment by obestwalter** [comment]
I am on Arch Linux with i3wm Windowmanager btw, which might contribute to the problem? I have a lot of weird foscussin problems with popups also atm. Seems 2018.1 is particularly buggy regarding this.

**Comment by vsch** [comment]
@obestwalter, I am first trying it on previous 2018.2 EAP, then latest. If it craps out then it is part of the IDE issue. I had exactly this bug with IDEA, WebStorm and PhpStorm. I could not use them because I have a lot of fenced code in docs and this bug made it impossible to work with them.

Turning off language injections into fenced code solved the problem before but I like editing the language fragment in separate window to I could not be happy with that.

**Comment by vsch** [comment]
@obestwalter, can confirm that previous 2018.2 EAP gets an exception when editing fenced code with language injections. The cursor did not jump but I could not insert a line when hitting return.

The latest EAP that I installed just now seems to work for fenced code but was getting some exceptions not related to the plugin. I disabled cloud sync to stop the errors and it seems to be working.

The error does sound like it is an IDE issue. Last time it happened I tried Markdown Support and it too was getting these errors. You can see if Markdown Support also has the same problem.

If the plugin has issues with language injections then it happens on all versions and it happens if I change implementation code, which I have not touched in months, if not the last year.

Here is the latest version I installed:

PyCharm 2018.2 EAP (Professional Edition)
Build #PY-182.2757.17, built on May 30, 2018
PyCharm EAP User
Expiration date: June 29, 2018
JRE: 1.8.0_152-release-1226-b7 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.12.6
