### ISSUE TITLE
Strikethrough doesn't work for codeblocks

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#603]
![screen shot 2018-06-12 at 12 00 08 pm 1](https://user-images.githubusercontent.com/281413/41283925-2c77e112-6e38-11e8-9581-4e2997f0d205.png)

Here is a video of a few different cases where it is not working: http://recordit.co/QchCtzirSw

Try with toggle strikethrough shortcut key.

**Comment by vsch** [comment]
@vjpr, it works but does not show in the syntax highlighting.

There are many combinations which do not work. The reason is that for the IDE each combination requires a separate color token because the attributes are not combined automatically.

The plugin already creates just over 8000 combination for various combinations. This does not cover all possible combinations but adding more will overload the API.

See #519
