### ISSUE TITLE
Goland freezes when selecting JavaFX web view

### ISSUE THREAD

**Issue by cvigo** [vsch/idea-multimarkdown#606]
I open any MD file and click on "Change preview browser to JavaFX". Then Goland GUI freezes forever and keeps dumping threads every 5 seconds (latest dump attached, they are all identical).

GoLand 2018.1.4
Build #GO-181.5087.39, built on May 24, 2018
JRE: 1.8.0_152-release-1136-b39 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.4

[threadDump-20180613-115211.txt](https://github.com/vsch/idea-multimarkdown/files/2097644/threadDump-20180613-115211.txt)

[idea.log](https://github.com/vsch/idea-multimarkdown/files/2097645/idea.log)

**Comment by vsch** [comment]
@cvigo, there is an issue with JavaFX on High Sierra. #483

I have a trial build which should fix this but I cannot run High Sierra on my system and waiting for feedback to know if the issue is fixed for the hang and/or crash.

You can try this build by downloading the zip file and installing plugin from disk. Do not extract the zip. Simply select it from the IDE Plugins settings pane by clicking the install plugin from disk.

https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.2.5.2.22.zip

**Comment by cvigo** [comment]
Updated. Goland reported a plugin error de very first time (I send the report) but it did not complain again after a second restart... will be trying for a few days but looks ok

**Comment by vsch** [comment]
@cvigo, I saw the report and will fix it shortly. 

It is caused by timing. The first time around indexing is causing a delay in JavaFX initialization and some eager functions don't check if JavaFX is already initialized. 

Easy fix now that the main issue with JavaFX initialization is resolved.

**Comment by vsch** [comment]
@cvigo, EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by cvigo** [comment]
Nice, thanks!!
