### ISSUE TITLE
Support for Marp-compatible syntax

### ISSUE THREAD

**Issue by bkimminich** [vsch/idea-multimarkdown#608]
The [Marp](https://github.com/yhatt/marp) Markdown presentation writer renders line breaks as they appear in the Markdown. When Markdown Navigator does reformatting, it introduces line breaks which can then butcher the presentation layout.

Is it possible to turn just line breaks off for reformatting? Not sure if this even is a plugin setting or would have to be disabled in general in IntelliJ. A nice option would be having a setting for this in the parser options, maybe even adding a new [Marp](https://github.com/yhatt/marp) parser profile?

## Before reformatting
![image](https://user-images.githubusercontent.com/3531020/41529911-d8194adc-72ee-11e8-8e1f-0fe9a5618dd7.png)
![image](https://user-images.githubusercontent.com/3531020/41529944-ec46f4aa-72ee-11e8-993b-606d50309741.png)
![image](https://user-images.githubusercontent.com/3531020/41529951-f0a0e66e-72ee-11e8-8512-bbb8dd09ca03.png)

## After reformatting
![image](https://user-images.githubusercontent.com/3531020/41529964-fe075ed2-72ee-11e8-9894-fd36649231e9.png)
![image](https://user-images.githubusercontent.com/3531020/41529985-09434e0a-72ef-11e8-84ea-7d2d536cf8b3.png)
![image](https://user-images.githubusercontent.com/3531020/41529994-0f425bfc-72ef-11e8-9702-30760547b630.png)

**Comment by vsch** [comment]
## Reply

@bkimminich, there are a few settings that affect the formatting for hard breaks

First to have line breaks displayed in preview as Marp does it, select `Hard Wraps` in parser settings.

[Parser-Settings](https://github.com/vsch/idea-multimarkdown/wiki/Parser-Settings#syntax-options)

For not wrapping text when reformatting deselect `Wrap text` in the `Text` panel of code style settings that way formatting will not wrap text since line breaks are significant. This way you will control the wrapping.

To prevent image links and links from being wrapped to beginning of line change the the image and link options for `Keep at start of line` pane to `None`.

[Document-Format-Settings](https://github.com/vsch/idea-multimarkdown/wiki/Document-Format-Settings#text-formatting)

To prevent wrap on typing turn off the `Wrap on typing` check box.

**Comment by bkimminich** [comment]
Thanks, those settings work fine for Marp! 👍
