### ISSUE TITLE
Multimarkdown's code style doesn't provide option to enable soft wrapping

### ISSUE THREAD

**Issue by markwoon** [vsch/idea-multimarkdown#61]
Multimarkdown's code style doesn't provide option to enable soft wrapping.

(Reference: https://youtrack.jetbrains.com/issue/IDEA-72261)

**Comment by vsch** [comment]
@markwoon, thank you for bringing this point to my attention.

If I understand correctly you are talking about these 3 settings:

<img width="686" alt="screen shot 2015-11-10 at 6 10 10 pm" src="https://cloud.githubusercontent.com/assets/10299086/11078863/6b034a8e-87d6-11e5-825d-cb6e56c42a7d.png">

I will see about adding them into the next release. However, these will probably be the only code style settings I will get a chance to implement before I address automatic formatting as a whole, which I am planning to do as soon as refactoring and annotations are done for all markdown elements.

I will let you know as soon as it is ready.

**Comment by markwoon** [comment]
Sounds good, thanks.

**Comment by vsch** [comment]
Sorry, had to bump it to the next one because I ran out of time for this release.

**Comment by vsch** [comment]
@markwoon , version 1.4.5 has been released. It has wrap on typing and table formatting on typing. Took more effort than I thought but it is coming along.

**Comment by markwoon** [comment]
Hmm...  This isn't quite what I'm looking for.  This is great, but it's a hard wrap at the right margin.  What I really want is for markdown files to have soft wrap enabled.

**Comment by vsch** [comment]
@markwoon, I wish I understood what you meant earlier. This would be sooo much easier than hard wraps.

I'll add it. I don't see it being harder than creating an option in preview options: Default, Soft Wrap, No Soft Wrap and then enabling it in the editor.

I did not think of this because I just created a keyboard short-cut that toggles soft-wraps for the current editor. Soft wraps have not control for content so text and tables will be wrapped. Toggling allows switching within the same file.

**Comment by markwoon** [comment]
Wouldn't that be nice:  context-sensitive soft wrapping!

Sorry about the confusion.  In my mind it made sense  ;)  I just got tired of toggling soft-wrapping whenever I switched file types.

**Comment by vsch** [comment]
@markwoon, this one fell off my radar because I forgot to re-open it.

It is now implemented. This release has format buttons and soft-wraps setting for markdown documents. The setting only affects documents that are opened. After that you need to use toggle soft-wrap action to toggle the setting.

Setting is under Languages & Frameworks > MultiMarkdown

Download and install plugin from disk: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.4.8.2.zip>

**Comment by markwoon** [comment]
Works great!  Thanks.
