### ISSUE TITLE
hope can have more paste option

### ISSUE THREAD

**Issue by bluelovers** [vsch/idea-multimarkdown#610]
1. paste from html, keep link but remove format, or can choose keep what kind format

![2018-06-26-00-43-15-1](https://user-images.githubusercontent.com/167966/41863669-15595eb4-78da-11e8-8462-8cfec2f977c7.png)

2. if has line-break / space at end, remove it

3. do not auto add line-break / 2-space at end

**Comment by vsch** [comment]
@bluelovers, can you please provide the HTML as an example from which markdown is extracted.

The conversion from HTML to markdown is done in the flexmark-java library and it would be easier to add these options to the library rather than post-process the results.

**Comment by bluelovers** [comment]
> before

![2018-06-30-07-33-09-1](https://user-images.githubusercontent.com/167966/42118744-3478ba0e-7c38-11e8-8900-83170c232ba8.png)

every time paste, it add line break + 2 space + line break

## case 1

> copy

![2018-06-30-07-33-49-2](https://user-images.githubusercontent.com/167966/42118747-3966e950-7c38-11e8-9e9a-a795d607aeaa.png)

> paste

![2018-06-30-07-34-06-3](https://user-images.githubusercontent.com/167966/42118748-3999c0e6-7c38-11e8-911d-4cbc31bab789.png)

> after

![2018-06-30-07-34-22-4](https://user-images.githubusercontent.com/167966/42118749-39cac9e8-7c38-11e8-8697-71f7421e009f.png)

## case 2

https://wiki.guildwars2.com/wiki/Main_Page

![2018-06-30-07-40-42-5](https://user-images.githubusercontent.com/167966/42118838-356c984e-7c39-11e8-9f6e-0044929b6d24.png)

![2018-06-30-07-42-23-7](https://user-images.githubusercontent.com/167966/42118840-39354fc0-7c39-11e8-9b6d-8acafe22a3e8.png)

**Comment by vsch** [comment]
@bluelovers, thank you for the samples. I will see where the corrections can be made.

**Comment by bluelovers** [comment]
i think hook patse handler
then check it if patse from html
remove end 2 space and line break

---

just guess because i can't find any code about it at github
does this repo not fully source?

**Comment by vsch** [comment]
@bluelovers, the open source repo is out of sync. For the first year and a half I kept the repo updated. It was a manual effort since the two source bases differ due to licensing and feature differences. In that time there were zero contributions. The effort in maintaining the two source bases was significant and I stopped since it was not justified. I have not had the time to sync them up since.

**Comment by vsch** [comment]
@bluelovers, EAP update with a fix for the issue is available.

New HTML paste options in settings: 

<img width="911" alt="screen shot 2018-08-15 at 3 38 58 pm" src="https://user-images.githubusercontent.com/10299086/44169211-b912dc80-a0a1-11e8-973d-875e287b68dc.png">

The same dialog is shown on HTML paste if "Ask options on paste" is selected in settings. It will show clipboard content if it is HTML mime,. Shows the resulting markdown and rendered results. You can play with the options before pasting. "Save Defaults" shows "Paste" if the dialog is opened as result of html paste action.

<img width="1078" alt="screen shot 2018-08-15 at 3 39 31 pm" src="https://user-images.githubusercontent.com/10299086/44169263-d5af1480-a0a1-11e8-9434-b88b9c953294.png">

 

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by bluelovers** [comment]
issues with paste into code block ( 3 ` )

- `[]` => `\[\]` (should not escape at code block)
- every line get 2space at end (should not auto add it at code block)

**Comment by vsch** [comment]
@bluelovers, can you please provide sample HTML that is causing the extra characters.

The easiest way to do this is to turn off "Convert HTML content to Markdown" leaving the other options enabled. Pasting will then paste HTML which you can post here so I can see what is causing the extra characters during conversion.

**Comment by vsch** [comment]
@bluelovers, latest EAP 2.5.4.38 fixes erroneous escapes in inline code and fenced code elements, non-break space replacement by `&nbsp;` and a few more HTML to markdown conversion bugs.
