### ISSUE TITLE
Backspace in empty checkmark box deletes checkmark

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#611]
`I` = cursor position

```
- [ I] foo
```

Then say you want to add an `X`, and you press backspace...

```
- Ifoo
```

Note the deleted checkmark.

This makes it really difficult to check the checkmark, because normally you will want to backspace the blank space, and then add an `X`.

**Comment by vsch** [comment]
@vjpr, looks like a bug, previously the removal of TODO marker would only occur if the caret is after the marker. I will check the code.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)
