### ISSUE TITLE
Code folding eats one character for underline headers

### ISSUE THREAD

**Issue by habemus-papadum** [vsch/idea-multimarkdown#612]
See attached image
![screen shot 2018-06-29 at 12 09 03 pm](https://user-images.githubusercontent.com/1161604/42102899-5af8098a-7b95-11e8-9b86-f94d1ebdee1f.png)

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by habemus-papadum** [comment]
Thanks!  Fix works as expected.
