### ISSUE TITLE
Plugin can't initialize in multi-user setup

### ISSUE THREAD

**Issue by reitzig** [vsch/idea-multimarkdown#615]
Upon startup, I'm getting:

```
Plugin 'com.vladsch.idea.multimarkdown' failed to initialize and will be disabled.  Please restart RubyMine.

java.lang.ExceptionInInitializerError
...
Caused by: com.intellij.diagnostic.PluginException: /tmp/multimarkdown_taskitems.ttf (Permission denied) [Plugin: com.vladsch.idea.multimarkdown]
    ... 59 more
Caused by: java.io.FileNotFoundException: /tmp/multimarkdown_taskitems.ttf (Permission denied)
```

Sure enough, file `/tmp/multimarkdown_taskitems.ttf` exists and is owned by another user with 644 rights. Since the current user should thereby be allowed to read, I'm guessing the plugin tries to write the file without checking for existence, which is then denied.

Please fix by adhering to "tmp hygiene" standards: use a session-/user-unique folder for all things (e.g. `File.createTempDirectory`). 

FWIW, under GNU/Linux, a cache folder in the home directory may be the ideal solution, e.g. via `XDG_CACHE_HOME` (available on many modern distributions, afaik). It's probably a pain to get it to work in every scenario, and I don't know if there's a good Java wrapper for those things, so I feel for you.

Related, but old so I don't think fixes apply: #87, #95

**Comment by reitzig** [comment]
Workaround: 

    sudo chmod 666 /tmp/multimarkdown_*

**Comment by vsch** [comment]
@reitzig, I add a temp folder under the user directory. I agree that this is a more portable solution.

Another option is to use an embedded web server to eliminate the need for file URIs to the file system.

**Comment by reitzig** [comment]
> Another option is to use an embedded web server to eliminate the need for file URIs to the file system.

Without knowing the internals, that seems overkill.

**Comment by vsch** [comment]
@reitzig, the embedded server will have other advantages to address differences in browser security issues when using file URIs vs server URLs.

Debugging of file sourced pages is limited and now requires setting up a web server in order to debug JavaScript in a preview page. Having all pages served by an embedded server will remove these limitations and address temp file usage at the same time.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by vsch** [comment]
@reitzig, now temp files are always put into user's home directory under `.markdownNavigator` subdirectory.
