### ISSUE TITLE
Enhancement: Create / Update TOC in context menu

### ISSUE THREAD

**Issue by robertoschwald** [vsch/idea-multimarkdown#616]
As we rarely create a new TOC, it would be great if you can add generate / update to the context menu, so one doesn't have to remember the correct syntax of the TOC line.
Also, updating by using the quick fix icon as the only option is not smooth, as the quick fix icon some times takes a while until it is shown, so you click around until it appears (IDEA limitation I suppose).

**Comment by vsch** [comment]
@robertoschwald, I do not understand what you mean since the functionality you are requesting is already there. As for the delay for intentions it is an IDE delay but is ususally less than a second.

1. To create a toc there is a live template for it under markdown:

    <img width="934" alt="image" src="https://user-images.githubusercontent.com/10299086/42324934-b6be39b4-8032-11e8-8cb4-8b746a35e744.png">

    <img width="591" alt="image" src="https://user-images.githubusercontent.com/10299086/42324946-c19371ec-8032-11e8-860d-50b05baec711.png">

    <img width="426" alt="image" src="https://user-images.githubusercontent.com/10299086/42324965-cfec1a1e-8032-11e8-8fd0-d009f0a22d3c.png">

2. The update toc options intention will allow you to use a dialog to select options and provide a preview without needing to remember the syntax:

    <img width="478" alt="image" src="https://user-images.githubusercontent.com/10299086/42324996-e87f31ce-8032-11e8-8d53-2dc4e1100655.png">

   <img width="1161" alt="image" src="https://user-images.githubusercontent.com/10299086/42325027-fc4874a4-8032-11e8-902c-6e858fd89137.png">

**Comment by robertoschwald** [comment]
intentions sometimes do not show here in IDEA. But live template is fine with me. Thanks for the explanation!

**Comment by vsch** [comment]
@robertoschwald, intentions in the IDEA sometimes require a caret movement to update. Moving the caret on the element will update the intention menu.
