### ISSUE TITLE
GFM Task List does not render properly

### ISSUE THREAD

**Issue by breandan** [vsch/idea-multimarkdown#618]
[GFM task lists](https://blog.github.com/2013-01-09-task-lists-in-gfm-issues-pulls-comments/) do not seem to render properly:

![screen shot 2018-07-06 at 9 50 59 am](https://user-images.githubusercontent.com/175716/42382390-223ca9c6-8102-11e8-8738-dd245a1433f8.png)

Note the indentation issue. The GitHub rendering can be [found here](https://github.com/duckietown/hatchery/blob/master/readme.md#planning).

**Comment by vsch** [comment]
@breandan, the rendering on GitHub appears to be the same as the plugin preview:

<img width="838" alt="image" src="https://user-images.githubusercontent.com/10299086/42398300-5d58a9e4-8137-11e8-9709-82f385fd1176.png">

At the same time if I copy the sample file text (from Raw file) and paste into a markdown in the IDE I get the right rendering with all items displayed as task list.

The issue is that you don't have 4 spaces on lines that don't render correctly. You have a space, a non-break space, space, non-break space:

<img width="971" alt="image" src="https://user-images.githubusercontent.com/10299086/42398577-5af9f846-8138-11e8-8f36-3ceee378a8f9.png">

**Comment by vsch** [comment]
@breandan, common-mark does not treat non-break spaces as indentation spaces. This makes these lines not indented enough to be list items and instead they are treated as lazy continuation of previous items.

**Comment by vsch** [comment]
@breandan, BTW https://plugins.jetbrains.com/plugin/7448-zero-width-characters-locator plugin locates zero width unicode characters and nbsp.

**Comment by breandan** [comment]
@vsch Sorry, my bad. Good to know about that plugin. Thanks for your help!
