### ISSUE TITLE
Create unchecked list item when pressing enter next to a line with a checked list item

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#619]
```
- [x] foo<cursor>
```

_Press enter_

Actual:

```
- [x] foo
- [x] <cursor>
```

Expected:

```
- [x] foo
- [ ] <cursor>
```

**Comment by vjpr** [comment]
Also when using the keyboard shortcut to toggle the check, the cursor shifts to the right by one place. I am using `cmd+option+x` as the keyboard shortcut.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)
