### ISSUE TITLE
Check keyboard shortcut changes wrong list item

### ISSUE THREAD

**Issue by vjpr** [vsch/idea-multimarkdown#620]
See gif. Pressing keyboard shortcut for check. Notice cursor is on the bottom line

![51v9xdl6io](https://user-images.githubusercontent.com/281413/42541328-388a261a-84a2-11e8-93cd-124d58886d96.gif)

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)
