### ISSUE TITLE
plugin oom in goland

### ISSUE THREAD

**Issue by runzexia** [vsch/idea-multimarkdown#621]
I have install this plugin in my goland.And oom happend. I analyzed the heapdump using the eclipse memory analyzer.I suspect that some plugins may be in conflict. If you need a heapdump file, I will be happy to provide it.
```
65 instances of "com.vladsch.idea.multimarkdown.editor.MultiMarkdownEditorKit", loaded by "com.intellij.ide.plugins.cl.PluginClassLoader @ 0x7a121d490" occupy 563,065,784 (79.98%) bytes.

Biggest instances:

com.vladsch.idea.multimarkdown.editor.MultiMarkdownEditorKit @ 0x79a0221f0 - 11,064,248 (1.57%) bytes.
com.vladsch.idea.multimarkdown.editor.MultiMarkdownEditorKit @ 0x7975dd6e0 - 11,064,240 (1.57%) bytes.
com.vladsch.idea.multimarkdown.editor.MultiMarkdownEditorKit @ 0x799591770 - 11,064,240 (1.57%) bytes.
com.vladsch.idea.multimarkdown.editor.MultiMarkdownEditorKit @ 0x79806b890 - 11,064,096 (1.57%) bytes.
```

**Comment by runzexia** [comment]
[heapdump file](http://pcdlhq06i.bkt.gdipper.com/heapDump-goland-1532415103434.hprof.zip)

**Comment by vsch** [comment]
@runzexia, the class in question is for Swing browser. I think I found a potential memory leak. 

EAP update with a fix for the issue is available.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by vsch** [comment]
@runzexia, your help is very much appreciated.

**Comment by vsch** [comment]
@runzexia, with the help of #710 I found the real cause that the instances were kept alive. I completely missed the message bus connection registration.

The fix will be available in the next release which has a few bad old bugs nailed.
