### ISSUE TITLE
image pasting on OS-X doesn't appear to work

### ISSUE THREAD

**Issue by dph01** [vsch/idea-multimarkdown#627]
I'm trailing Markdown Navigator for Intellij IDEA on OS-X 10.13.6 but the paste image functionality doesn't appear to work. Is there some magic I need to do to activate it?

Steps... 
1) Markdown Navigator 2.5.4 plugin installed in Intellij IDEA Ultimate 2018.1.6. Intellij restarted.
2) Trial licence for Markdown Navigator installed (licence activation confirmation notice is showing)
3) Capture a section of the screen using Skitch. Ctrl-C to copy the image to the paste buffer.
2) Paste into Gmail editor to check copy / paste works OK
3) Paste into a markdown file on Intellij ... nothing happens.

Thanks

Damian

**Comment by vsch** [comment]
@dph01, do you have the paste handler customization enabled? It is the first option in the red rectangle:

<img width="1010" alt="screen shot 2018-08-30 at 9 44 26 am" src="https://user-images.githubusercontent.com/10299086/44855583-6b69a880-ac39-11e8-962e-85f21426189f.png">

The option is there to allow disabling the custom handler in case it interferes with the result.

This option can be turned off if the IDE paste handler generated an exception and you confirmed turning it off to allow sending a bug report to JetBrains.

You will not see some of the other options for paste because they are in the EAP release of the plugin. You might want to update to the EAP version to get latest bug fixes and new features.

To enable EAP update channel:

1. Select "Early Access Program" in `Check updates for:`
2. Then make the IDE check for updates.

![Screen Shot Settings Update Channel](https://github.com/vsch/idea-multimarkdown/raw/master/assets/images/faq/ScreenShot_Settings_UpdateChannel.png)

**Comment by vsch** [comment]
@dph01, if paste handler is enabled but it still does not work, can you please try capturing the screen with the OS X built in functionality using SHIFT+COMMAND+4 and see if it works.

If it does then it would be an issue of recognizing Skitch pasted format.

**Comment by dph01** [comment]
Hi Vladimir, thanks for the response. I'm not sure how I missed it, but I think none of the premium features are available even though the licence is installed. Here's what the toolbar looks like 

![image](https://user-images.githubusercontent.com/497824/45207671-7d25fe00-b280-11e8-8736-84cc326f7526.png)

I've enabled the settings you suggested an tried SHIFT+CTRL+COMMAND+4 but nothing has changed. 

I enabled the EAP option and a Intellij -> Check for Update  but the installed version hasn't changed. Do I need to do something else to trigger an update? 

Here are my settings:
![image](https://user-images.githubusercontent.com/497824/45208040-8bc0e500-b281-11e8-9ced-67c9a8b4753d.png)

**Comment by vsch** [comment]
@dph01, to force update you need to make the IDE "Check for updates...", it is in the IDE menu below the "About IntelliJ"

From the toolbar and settings I can see that the enhanced features are enabled. The "wrap on typing" (first toolbar button) is disabled because you have "Soft Wrap" enabled. The other formatting buttons (Underline, Superscript, Subscript) are disabled because these optional markdown extensions, under Languages & Frameworks > Markdown > Parser, are not enabled. They are not supported by GitHub so disabled by default.

You may also want to enable "Soft wrap at right margin" in settings above, which will soft wrap at the right margin instead of right edge of text window, Switching "Soft Wrap" from "Default" to "Enabled" or "Disabled" to let you control soft wrap for Markdown documents separately from the global setting. Default uses IDE global setting for markdown documents.

If you copy an image and then click on the "Paste Image" in the "Change Defaults For" panel in settings above you should see the paste image dialog with your image used as a sample. If the clipboard does not contain an image you will see the Markdown Navigator logo: 
![image](https://user-images.githubusercontent.com/10299086/45216713-878bcc00-b26f-11e8-9395-d7abf5683559.png)

Here is one I displayed as a test:

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/10299086/45216991-827b4c80-b270-11e8-8316-93aebd62dadd.png">


**Q:** Are you seeing your copied image when you do that? If not can you make sure that SHIFT+CTRL+COMMAND+4 does copy the image to the clipboard. These standard shortcuts can be disabled in System Preferences under Keyboard > Shortcuts in OS X.

**Q:** Are you getting any exceptions when you try to paste an image?
