### ISSUE TITLE
Invoke renumbering ordered lists

### ISSUE THREAD

**Issue by ursqontis** [vsch/idea-multimarkdown#633]
Hi Vladim,
I often have the problem that my ordered list numbers don't reflect the real position anymore, e.g. when I insert a new header between two order list items.

![image](https://user-images.githubusercontent.com/42566119/45535812-faf98480-b7ff-11e8-86a4-225af38a5aff.png)

I didn't find a way to auto-renumber order list items. Is there any?
An alternative would be to just switch off the auto-number feature altogether, leaving all numbers at "1.". But I didn't find such an option either.

**Comment by vsch** [comment]
@ursqontis, sorry I missed this one.

The list items will be renumbered when formatting document if the option is enabled in code style settings https://github.com/vsch/idea-multimarkdown/wiki/Document-Format-Settings#list-item-options

Note that CommonMark allows specifying a starting number for a list so your list will start with 15 not 1. You need to use 1 for the first list item to start numbering. Otherwise, whatever number you use will be the starting number for the list.

**Comment by ursqontis** [comment]
Thanks Vladimir, I wasn’t even aware that there is a code style settings page for markdown.
BTW It would be nice to have a “default” list marker for numbered lists, as you already have for “bullet list marker”. We’d prefer to always have “1.”, so the document could be reformatted to always use “1.” (which will render to the proper number), even if somebody used individual numbers.
Thanks & best regards,
Urs

**Comment by vsch** [comment]
@ursqontis, I can add an option to format style to "Reset first numbered item to 1" to get the functionality you are looking for. It will effectively eliminate the CommonMark ability to start a numbered list from a specific number.

Personally, I think that this CommonMark feature is of limited use since it requires that you manually keep the continuation list's starting number updated. It would have made more sense to have non-1 values continue numbering from the last numbered list.

**Comment by vsch** [comment]
@ursqontis, I checked and formatting a document with list renumbering enabled always started a list with 1. So the fix will involve adding an option to renumber from 1 and fix formatter to not change the first item if the list parser setting is CommonMark.

The option to reset first item to 1 will be there in the next release.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by vsch** [comment]
@ursqontis, I added editing and updating of ordered list numbering if you enable ordered item renumbering. It looks like you work with lists a lot so please give me feedback on what you think of latest changes. I tried to make the lists update, but at the same time to allow manual editing and detect when this occurs automatically.

* Fix: any renumbering of list items required indentation change of child elements otherwise
  they could fall out of parent indent scope. ie. `9. text` changing to `10. text` requires
  adding 1 space to child indents or they would no longer be under the parent, according to
  CommonMark.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
