### ISSUE TITLE
Mermaid and Russian language is breaking when exporting to PDF

### ISSUE THREAD

**Issue by Melodyn** [vsch/idea-multimarkdown#642]
I expected to see text and images in PDF as in the preview of the plug-in, but something went wrong
![pdf](https://user-images.githubusercontent.com/26752238/46674880-e8e3e980-cbe5-11e8-8bba-e06796d18843.PNG)

----

Я ожидал увидеть в PDF текст и изображения такие же, как в превью плагина, но что-то пошло не так

**Comment by vsch** [comment]
@Melodyn, I have not figured out how to change the PDF converter to use a font which has the required unicode code pages for multi-byte characters. 

I will see if I can override the font with one available on the system.

**Comment by vsch** [comment]
@Melodyn, btw, mermaid is implemented in JavaScript in the preview browser so PDF conversion cannot convert mermaid diagrams. Neither can Swing preview browser since it does not support JavaScript.

In the latest EAP releases PlantUML charting was added which will render via embedded PlantUML library or gravizo.com. In both cases Swing browser and PDF export will work.

I am still unable to resolve the non-latin character sets for PDF preview. I am trying a few ideas to see if they resolve this issue.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by vsch** [comment]
@Melodyn, fixed for non-latin fonts by including [Noto](https://www.google.com/get/noto/) Serif/Sans/Mono fonts with the plugin allowing adding `noto-serif`, `noto-sans` and `noto-mono` families to CSS to allow PDF to use these for rendering text.

By creating a custom rendering profile with CSS Text:

```css
.markdown-body,
.wiki-body {
    font-family: 'noto-sans';
    font-size: 16px;
    line-height: 1.6;
}

var,
code,
kbd,
pre {
    font: 0.9em 'noto-mono';
}
```

And turning off all stylesheets and turning off HTML Generation option: `Add page header`.

Then setting Rendering Settings PDF profile to the above created rendering profile so PDF uses the custom CSS and HTML Generation.

The following markdown:

``````markdown
1. 0.40.68 test
   ------------

## Reply

`Я ожидал`

```puml
A -> D 
```
``````

![screenshot_642pdf](https://user-images.githubusercontent.com/10299086/51688231-29634980-1fc2-11e9-9394-3ffe580fe11d.png)

[642.pdf](https://github.com/vsch/idea-multimarkdown/files/2792327/642.pdf)

I will let you know when the EAP with the fix is available.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available. (see [Rendering-Profiles-Settings](https://github.com/vsch/idea-multimarkdown/wiki/Rendering-Profiles-Settings))

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
