### ISSUE TITLE
Preview is not in sync with editor and keeps moving to beginning

### ISSUE THREAD

**Issue by huehnerlady** [vsch/idea-multimarkdown#653]
Hi,

I use the trial license atm. and so far I do like the table feature, but what drives me crazy is that the preview seems to be reset to the beginning of the page frequently. I feel like after every change I have to find the point I was currently working on. Is there an option to sync the preview with the editor like it is in the other markdown plugin from intellij?

**Comment by huehnerlady** [comment]
I tried the JavaFX as well. unfortunately that wasn't the only thing it broke so I had to deactivate it for now. But as it is an interesting feature I will have a look at it again when I have time.

**Comment by vsch** [comment]
@huehnerlady, 

The JavaFX Preview gives the best results and has the most features. The swing browser is very, very limited and not compatible with anything expected today from a browser.

However, some installations have issues with JavaFX, usually due to old Java or missing JavaFX.

What IDE (and version) and OS are you running on?

**Comment by huehnerlady** [comment]
I run intellij 2018.2 with java8 and macosx 10.13.6
The javaFX did indeed work for the preview, it just showed the same behaviour as the swing preview.

**Comment by vsch** [comment]
@huehnerlady, I am running with identical setup, including OS. Can you please tell me what problem did you have with the JavaFX preview browser. It should work on your system, if it does not it is either a bug or some missing configuration that I need to address.

**Comment by huehnerlady** [comment]
It is the same behaviour. Regularly the preview keeps moving to the beginning of the page so that I always have to scroll to where I was before, which is very tedious and does not weigh my only advantage (the auto format of the table) as it is really annoying to have to adapt the preview all the time. Then I prefer to just manually format the 4 tables I have and be done with it.

In addition I do not like the layout the javaFX browser has compared to the swing one...

Sorry, but I will not try it again with the work I am currently doing as I want to get it done.
I will stay tuned though and already subscribed to your releases so I will see how this develops.

**Comment by vsch** [comment]
@huehnerlady, 

The scroll synchronization not working sometimes occurs when switching scroll sync setting for open documents. Closing the document and re-opening it solves the glitch. I have not been able to figure out how this happens. It appears timing related and only happens when switching scroll sync options.

When you have the time you can change the JavaFX to use the Swing style sheet. Just do it after switching the browser to JavaFX as a browser switch tends to reset the style sheet to its own default.

![screenshot_swingcssinjavafx](https://user-images.githubusercontent.com/10299086/49292895-80461a00-f47c-11e8-98b6-e8813ab961ab.png)


You can also disable the file name heading in the preview for a simpler view:

![screenshot_nopageheader](https://user-images.githubusercontent.com/10299086/49292899-85a36480-f47c-11e8-8247-86a216869564.png)
