### ISSUE TITLE
dist idea-multimarkdown.2.7.0.10.zip is missing

### ISSUE THREAD

**Issue by simon-morgan** [vsch/idea-multimarkdown#654]
First, thanks for maintaining a most useful plugin.

Second, I just checked for updates in Intellij and it is now reporting that 2.7.0.10 is available but when I try to update to 2.7.0.10 it fails with the error message that 
idea-multimarkdown.2.7.0.10.zip is missing.

**Comment by vsch** [comment]
@simon-morgan, thank you very much for the heads up. I did miss the most important part of adding the distribution zip to the release. This is now fixed.

In my defence I did "try" to copy the distribution zip but having done this so often I did not check for errors.

I don't usually see the EAP release update notices because I have to make the installation so often, I have an update script doing it to all my IDE installations that I either use or need for testing.

```
updating IdeaIC2019.1 for latest idea-multimarkdown
updating IdeaIC2017.3 for latest idea-multimarkdown
updating IdeaIC2018.1 for latest idea-multimarkdown
updating IdeaIC2018.2 for latest idea-multimarkdown
updating IdeaIC2018.3 for latest idea-multimarkdown
updating IntelliJIdea2018.1 for latest idea-multimarkdown
updating IntelliJIdea2018.2 for latest idea-multimarkdown
updating IntelliJIdea2018.3 for latest idea-multimarkdown
updating PhpStorm2018.1 for latest idea-multimarkdown
updating PhpStorm2018.2 for latest idea-multimarkdown
updating PhpStorm2018.3 for latest idea-multimarkdown
updating WebStorm2018.1 for latest idea-multimarkdown
updating WebStorm2018.2 for latest idea-multimarkdown
updating WebStorm2018.3 for latest idea-multimarkdown
updating CLion2018.1 for latest idea-multimarkdown
updating CLion2018.2 for latest idea-multimarkdown
updating CLion2018.3 for latest idea-multimarkdown
updating DataGrip2018.2 for latest idea-multimarkdown
updating DataGrip2018.3 for latest idea-multimarkdown
```
