### ISSUE TITLE
Refactoring does not update reference to file after dragging files to different package

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#656]
2.7.0

Steps to reproduce:
1. Import this project into Android Studio
https://github.com/igorwojda/kotlin-coding-puzzle

2. Open `app/src/test/java/com/igorwojda/datastructure/linkedlist/base` in Project 
3. create new package `abc` like this `app/src/test/java/com/igorwojda/datastructure/linkedlist/base/abc`
4. Drag all files from `.../linkedlist/base` to newly cerated package `.../linkedlist/abc`

Result:
Reference in `README.md` the file is not updated
`1. [Linked list](app/src/test/java/com/igorwojda/datastructure/linkedlist/base/LinkedList.md)`

Expected Result
Reference should be updated
`1. [Linked list](app/src/test/java/com/igorwojda/datastructure/linkedlist/base/abc/LinkedList.md)`

**Comment by vsch** [comment]
@igorwojda, its a bug in multi-file move refactoring. It works if moving one file at a time and affects page relative links to other files being moved, all other link formats: repo relative (`/...`), `http://` or `file://` are not affected.

![MultiFileMove.gif](https://github.com/vsch/MarkdownTest/raw/master/image/MultiFileMove.gif)

I did not try it with Android Studio and will try your project exactly tomorrow.

The only workaround is to move one file at a time, a PITA or convert links to `http://` or another format using one of the convert link intentions.

I will fix and post an update as soon as an EAP build with the fix is available.

**Comment by vsch** [comment]
@igorwojda, thank you for a real project link, especially in android studio. I don't work on Android apps so have no experience in setting up a project nor have the time to do it just to test the plugin.

I benefit by seeing how the plugin is used and the structure of where markdown files are included. As you saw markdown can be very sensitive to file locations.

**Comment by vsch** [comment]
@igorwojda, I agree creating a project is easy but it is not a real project and any markdown usage in it will reflect my pre-conceptions that I already use in IntelliJ. Real benefit for me is to see how users use the plugin in real projects.

If there is an annoyance or discomfort, there is a feature that can be used or needs minor tweaks to make it painless to use. In the extreme case there is a need for a new feature or configuration.

Many features without which I cannot work were originally requested by users. So I am always eager to hear user suggestions. It is an opportunity to learn something new for both involved.

**Comment by vsch** [comment]
@igorwojda, 
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
