### ISSUE TITLE
JavaFX library jfxrt.jar not found

### ISSUE THREAD

**Issue by obestwalter** [vsch/idea-multimarkdown#67]
When I start Pycharm in the terminal I get this warning:

WARN com.vladsch.idea.multimarkdown  - JavaFX library jfxrt.jar not found in the provided jre: /usr/lib/jvm/java-7-oracle/jre, version 1.7.0_80
WARN com.vladsch.idea.multimarkdown  - MultiMarkdown HTML Preview will use a more limited implementation.

I am running PyCharm version 5.01 and the plugin version is 1.2.0

**Comment by vsch** [comment]
@obestwalter, this is just an information warning that the plugin will not use the JavaFX based WebView.

The first Java release that supports JavaFX is 1.8 and I would discourage anyone from trying to use the new preview with anything below 1.8.0u_40. Crashes are likely and I will disable even attempting to run it with anything below 1.8.0u_51 which has the first descent WebView versions.

Now this is not a fatal error. The java swing based preview is faster but has less HTML/CSS features so the preview is less fancy. To enable the new JavaFx preview requires running the IDE under a newer Java Version.

Some people do not want to change the JRE  and prefer to run the one that they have currently installed.

Instructions on changing the boot jdk that the IDE will use are in the wiki [Changing Boot JDK](../wiki/Changing-Boot-JDK) if you need more help in setting this up please let me know what OS you are using because the IDE boot jdk setup is different under every OS.

**Comment by obestwalter** [comment]
@vsch Thanks for clarifying that. As the log level was WARN I thought somethin is not working as it should.

**Comment by vsch** [comment]
@obestwalter, you are welcome and I will change the log to info. It was really a warning to me but not a real warning.
