### ISSUE TITLE
Refactoring does not update reference to file after renaming package

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#672]
Similar to https://github.com/vsch/idea-multimarkdown/issues/656

```
-README.md (containing a link to infoA.md)
-packageA
--infoA.md
```

Rename `packageA`
Result: Reference in `README.md` is not updated

2.7.0.40

**Comment by vsch** [comment]
@igorwojda, there are a lot of use cases where the refactoring does not work for files or links.

I recently discovered that java files will not generate file move/rename refactoring because they are considered Java class rename/move refactoring. If you select multiple java files and move them then no file refactoring is generated. If on the other hand you select the same java files but include a non-java file then the IDE will generate file move refactoring.

I was told this is expected behaviour. So I will need to figure out how to handle all the different modes of file location changes and generate my own file move refactoring events.

This includes package/directory move/rename.

**Comment by vsch** [comment]
@igorwojda, fixed for Java classes and packages. Unfortunately if the same issues exist in other IDEs with respect to their classes and packages then I will need to add it for every language Psi element for class and package.

* Fix: #672, Refactoring does not update reference to file after renaming package
  * Fix: find usages to find directory references in links
  * Fix: find usages to find package references in links
  * Fix: find usages to find java class file references in links
  * Fix: directory renaming to trigger link refactoring
  * Fix: package renaming to trigger link refactoring
  * Fix: java class renaming to trigger link refactoring
  * Fix: java class move to trigger link refactoring

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by vsch** [comment]
@igorwojda, one caveat with the rename package refactoring. I spent 3 hours debugging it for older IDEs (2018.3, .2 , .1, 2017.1) because it worked when debugging but not at run-time.

Finally, deleted the Application Support/IdeDir, Caches/IdeDir and relaunched and all versions worked. I also noticed that the package rename dialog showed only the package name not the full path as before.

Mainly what was failing was refactoring links to files when one of the parent packages was renamed. Links to packages (directories) would be renamed but links to any files in the path following the directory  would not be refactored.

If you have been upgrading your IDEs from previous versions and encounter the issue with package rename not refactoring links please try:

1. Launch the IDE
2. Export Settings so you can import them after cleanup without having to reconfigure everything.
1. close the IDE
2. delete the IDE's directory for the IDE in ~/Library/Application Support, ~/Library/Caches, it will be usually named after the IDE version: 2018.3 will have IdeaIC2018.3 or IntelliJ2018.3, etc.
3. rename the IDE's directory in Preferences to have a `.bak`, don't delete it just in case you want to recover some settings.
4. relaunch the IDE, do not import previous settings on startup. 
5. import settings saved in step 2.

You should have everything working. I suspect that application support or the cache has some old files which cause a problem. I had the same issue with 2018.3, .2, .1, 2017.1 after cleaning out old directories and effectively starting with a clean slate all versions worked.

**Comment by vsch** [comment]
@igorwojda, eap 2.7.0.48 also fixes an issue with directory move refactoring when directory is not a java package.

I can also confirm that RubyMine directory move refactoring is not working because of the way RubyMine implemented their directory move handler. CLion, PhpStorm, PyCharm, WebStorm and IntelliJ work.

**Comment by igorwojda** [comment]
`2.7.0.48 ` don’t work for me at all. 

I use Android Studio 3.2.1.

Steps to reproduce:
1. Checkout this project
https://github.com/igorwojda/kotlin-coding-puzzle

2. Open`app/src/test/java/com/igorwojda/string/anagram/Anagram.md`

3. Perform one of below tests (for me all failed - reference to`Anagram.md`  was not updated in README.md):
- Rename parent `anagram` package (parent of `Anagram.md` file)
- Drag package `anagram` package (containing md file to another package) 
- Drag a few files to another package, including `Anagram.md` file
- Rename `Anagram.md` file

**Comment by vsch** [comment]
@igorwojda, I did not test AS so it is probably implementing package renaming differently than IDE core.

I will look into it and update.

**Comment by vsch** [comment]
@igorwojda, seems that AS is not using the core rename API. Will need to figure out what is used instead.

**Comment by vsch** [comment]
@igorwojda, re-implement package/directory move/rename refactoring to make it compatible with Android  Studio and RubyMine.

Makes the code more robust because it depends on less implementation details so should not be affected by upgraded apps. A bit more convoluted on implementation but that is a trade-off.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by igorwojda** [comment]
`2.7.0.50` works perfectly with AS 3.3. Thanks

BTW your feedback and speed of fixes are very impressive. You are doing very good work. Thanks a lot

**Comment by vsch** [comment]
@igorwojda, thank you. 

Only users who bother to report issues get to find this out. There is a whole slew of "users" who think bitching and giving low star rating on the plugin page is their best plan of action, without ever reporting an issue or contacting me via e-mail to see if it a plugin issue or something else.

When an issue is reported, to me it is a signal that someone is using the feature and that its failure is serious enough for them to take the time to report it. Usually, this is all the motivation I need to fix it.

I appreciate all bug reports and suggestions. In almost every case the result is a better plugin, with functionality I find indispensable after I implement it and wishing I had implemented it earlier.

**Comment by vsch** [comment]
@igorwojda, found a use-case for refactoring packages which does not update links to directories.

* Fix: package rename to sub-package did not adjust links to subdirectories of original package.
  ie. rename package `abc` to `abc.xyz` would not refactor links for `abc/def` to `abc/xyz/def`.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
