### ISSUE TITLE
Absolute wiki page link is treated as unresolved lin r

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#681]
I am starting with links to wiki pages in my README.md and I have noticed that some valid links are marked as unesolved.

![image](https://user-images.githubusercontent.com/530122/51370171-121deb00-1aee-11e9-906e-9a6de2441961.png)

```
1. [Solve puzzle](https://github.com/igorwojda/kotlin-coding-puzzle/wiki/Solving-coding-chalenges)
```

**Comment by vsch** [comment]
@igorwojda, GitHub wiki is located in a separate VCS root than the main project and requires setting up a wiki directory under the project for the plugin to be able to resolve links from main project to wiki pages.

[Adding GitHub Wiki to IntelliJ Project](
https://github.com/vsch/idea-multimarkdown/wiki/Adding-GitHub-Wiki-to-IntelliJ-Project)

**Comment by igorwojda** [comment]
OK, this is expected, so I will follow instructions.

BTW I know it's not an ideal approach, however, it's valid/working URL (a bit different from other, external URLs, but still valid). Also if we want to treat this URL as invalid maybe we should have detter error description.

**Comment by vsch** [comment]
@igorwojda, up until the last release, there was no validation of remote links. 

The wiki link support was there from the beginning and with remote links the code was never changed to not show an error for wiki links for the project repository.

I am still not sure it is a good idea to use remote link validation instead of embedding wiki repo in the project. There is a lot of wiki specific rules addressed by completions that would not be available.

Creating an annotation to offer creating the wiki directory and repository for the project is a possible solution. I did not go this way because there will be a few conditions to figure out and handle proper creation of the wiki and I was not ready to go there. I think this would be the best option to address wiki creation for projects.

**Comment by silkentrance** [comment]
This should be handled as an external link and not be treated as a part of the documentation.
Simplification is the key. One can add link checks later on.

**Comment by vsch** [comment]
@silkentrance, and how do you suggest the plugin determine if you mistyped and it is an error or if it exactly how you want it but it cannot validate it?

If you do not want links checked, disable the annotations and link checking options. That way there is no confusion and no mind reading AI needed to determine what to check and what to ignore.

The other option is to add `<!-- @IGNORE PREVIOUS: link -->` right after a link element and no error annotations will be done on it. There are intentions to do that on invalid links as a short cut.

Simplicity is great until you find docs where an external URL was pointing to a non-existent page for over a year and you had no clue since you did not look at that file longer than that.

I prefer to err on the side of highlight suspicious stuff and if the user does not want it, they can turn off the feature. 

It is easier to see a highlight you don't want and turn it off than to figure out that there are highlights you would like to see.

**Comment by silkentrance** [comment]
@vsch there is no AI involved - just check for whether it is local or remote, e.g. there is a scheme present, e.g. http(s), or even ftp(s). these would then be considered remote. While other, e.g. `/local` would be considered local links.

**Comment by vsch** [comment]
@silkentrance, your model of markdown documents and what this plugin has does with links is too simplistic.

You can have 4 types of links to a file in the project: page relative, repo relative, http:// and file:// 

The plugin determines whether it is a project file by looking whether the link represents a file in the project. Otherwise, http:// links to project files would not be checked.

**Comment by silkentrance** [comment]
@vsch you should abstract away the page relative and repo relative and make this a local link.
there is no such notion as a repo relative. it is always local in terms of the current working checkout or branch or whatever.

and even if there is a wiki included with the repository, it should be considered an external resource, since it is going to be rendered by github or similar such platforms. (meaning that you cannot switch to the wiki branch in order to check on whether there is such a resource unless you go to lengths and overly complicate the current solution.)

that being said, checking for 404 on the remote link should do the trick.

**Comment by vsch** [comment]
@silkentrance, 

> you should abstract away the page relative and repo relative and make this a local link, similarly so for the file scheme.
there is no such notion as a repo relative. it is always local in terms of the current working checkout or branch or whatever.

Really? What if you are creating a page where the final result will not be rendered by GitHub but by some other processor not aware of GitHub link resolution? Many users have this type of use case.

All 4 types of links are needed depending on the use.

>and even if there is a wiki included with the repository, it should be considered an external resource, since it is going to be rendered by github or similar such platforms. (meaning that you cannot switch to the wiki branch in order to check on whether there is such a resource unless you go to lengths and overly complicate the current solution.)

Rally? What if you want your wiki kept as part of your project so that links between your project files and wiki (and vice versa) are refactored together so they are always in sync and you can use completions for links in the project files to the wiki and vice versa? 

I get the distinct feeling that you do not use most of the Markdown Navigator features to maintain sizeable documentation and see all the extras as complicating the task of writing a page or two of markdown. The plugin is not a markdown rendering `Notepad` for writing a quick read me page but is intended to make maintenance of large document base manageable. For simple uses there are other choices, including the bundled Markdown Support plugin which does an excellent job for that.

> that being said, checking for 404 (500, 503, ...) on the remote link should do the trick.

It is great to check for 404 and other errors but websites do not consistently report these and in some cases redirect to a generic page.

I love the simplicity of your suggestions. However, I think you need to try them in real life application to see if they work consistently or at least well enough to be considered as solution.

**Comment by silkentrance** [comment]
@vsch the markdown navigator plugin is basically not about providing a content mangement solution, unless you want it to be, but then you need to integrated other platforms as well.

as for website redirection, I would postpone this to a later iteration, as we are talking developers here... and not something that will go into production... and even if that is gone in production, well, it is the basic principle of the internet - burned bridges, knowledge being lost unless someone cares.

so the solution should embrace change and resort well to errors as they appear.

As for not getting the complexity, I am currently working on a documentation that spans multiple folders and links to both local and external resources, involving a deep hierarchy of local folders.

**Comment by vsch** [comment]
@silkentrance, you claim to maintain large documentation set, yet not see the need for  maintaining links between all the documents in sync. I guess you like broken links and manual editing. To each his own.

You seem to be under the mistaken assumption that your simple use cases cover all users' use cases and as such the plugin is too complex for its intended users. There are users using it to write books with multiple chapters split across folders.

I am not going to simplify features which were made complex by user requests that  needed the extra complexity to resolve their use case.

I don't see the point in this discussion. If you don't want the features, turn them off or don't use them.
