### ISSUE TITLE
ToDo markup not working in IntelliJ with trial plugin

### ISSUE THREAD

**Issue by jimkohl** [vsch/idea-multimarkdown#69]
Hello,
Went ahead and downloaded your trial.  Created a quick list of to do items:

# TODO Items
- [ ] item 1
- [ ] item n

but the checkboxes aren't rendering in the render pane.
Brought in the default css also, makes no difference.
tx
Jim

![image](https://cloud.githubusercontent.com/assets/5053517/11158219/b95a2626-8a24-11e5-996b-bd4e8f3aad23.png)

**Comment by vsch** [comment]
@jimkohl, thanks for letting me know. It exposed a small bug, the Preview can only handle lower case x, since it uses a custom font to render the task items and X is not in the font. It's and oops on my part. 

However, your issue is that **you have `Markdown Support` plugin enabled** and it is the preview you are seeing. You need to disable all the other Markdown plugins, otherwise idea-multimarkdown will not be the one handling Markdown files.

Please use lower case x for now. I'll fix it in the next release. 

You also need to enable JavaFX WebView preview by unselecting the 'Use Old Preview' in Preferences > Other Settings > MultiMarkdown, on the General tab. Otherwise the preview will always show open tasks since swing based preview lacks modern HTML / CSS support.

Here is what the two previews look like, left os old preview, right is the new JavaFX WebView based:
<img width="995" alt="screen shot 2015-11-13 at 4 44 50 pm" src="https://cloud.githubusercontent.com/assets/10299086/11158518/b231fda4-8a26-11e5-9f42-da44d920d908.png">

**Comment by vsch** [comment]
@jimkohl, Just double checked the code and it does handle upper and lower case. Sometimes the WebView HTML rendering fails to refresh correctly. Other than that you can use either [x] or [X] to close tasks.

**Comment by vsch** [comment]
It is the old preview that cannot handle [X], I'll fix it for next release.

**Comment by jimkohl** [comment]
Thanks for the quick response!  Yep I've been trying out a bunch of Markdown viewers for IJ.
I *thought* I had those all turned off / removed them.  gfm is off.  FreeMarker and Markdown support are now off.  And I tweaked per your instructions.

For the most part I can see as you show.  However, when I mark an item with X, a bullet appears before the item.  See:
<img width="292" alt="screen shot 2015-11-13 at 5 03 10 pm" src="https://cloud.githubusercontent.com/assets/5053517/11158796/8fc2a1f4-8a28-11e5-9da8-13aa87a01ac5.png">

Also, is there any way (besides cloning an open markdown window tab) to show non-rendered / rendered side by side?  Some of the other tools support that and I really like that.  Just can't seem to find an option for that.

**Comment by jimkohl** [comment]
in you screen snap above, looks like you've got rendered below the md.

**Comment by jimkohl** [comment]
your

**Comment by vsch** [comment]
@jimkohl not yet. I really like the `Markdown Support` split editor viewing. I already have it earmarked for the very near future. As you can imagine I am constantly flipping between markdown, preview and html text. I use Vertical split for now, it does the job but having the editor split in two or three panes will be more comfortable.

The screenshots show the preview. I habitually double the markdown and put one copy inside code-fence so that when I put it on GitHub the source and rendered text show up. People keep posting issues for markdown syntax but forget to code fence it or indent so I get to see the source. Instead I see the rendered version by GitHub and it usually looks fine. :)

Here is how make test markdown source so it is obvious from all angles:

    ```
    # Test 
    - [ ] To do \[ ]
    - [x] To do \[x]
    - [X] To do \[X]
    ```     
    
    # Test 
    - [ ] To do \[ ]
    - [x] To do \[x]
    - [X] To do \[X]
     
Then pasted into a post it looks like:

```
# Test 
- [ ] To do \[ ]
- [x] To do \[x]
- [X] To do \[X]
```     

# Test 
- [ ] To do \[ ]
- [x] To do \[x]
- [X] To do \[X]

**Comment by vsch** [comment]
@jimkohl for split view I set the zoom option of the WebView version to 0.75 and then adjust the second pane to be just wide enough to show the preview without the horizontal scroll bar. WebView has rendering bugs when a horizontal bar is displayed. I am hoping it will be fixed but have decided to add Lobo Evolution renderer to the list of ones the plugin will support. 

I am visual and any rendering issues annoy me. Swing rendering is limited and no retina support. WebView does a great job but is slow and has font kerning issues. Lobo Evolution does an excellent job of font rendering and I will see how much JavaScript support it can handle once I add it as a rendering engine.

Here is how I view both source and preview at the same time:

<img width="1616" alt="screen shot 2015-11-13 at 5 21 04 pm" src="https://cloud.githubusercontent.com/assets/10299086/11159101/f5073bf4-8a2a-11e5-85ba-c45e6ea1d94f.png">

**Comment by jimkohl** [comment]
Txt for the detail.  Because I have a lot of markdown content I won't want to be having to do this for each file. When do u think auto side by side will be completed?

**Comment by vsch** [comment]
@jimkohl I concur. I have releases scheduled every two weeks, with the next, one week from now. It will not make it into that one. I have a lot of new implementation features already in progress. I will see if I can add it into the next release. I don't see it as a major effort but those are famous last words. I want it badly myself so it will definitely be in one of the next two or three releases.

I have an unscheduled release going out this weekend. There a lot of bugs and optimizations from all the feedback and I want to get those into users' hands so I can have less support requests. :)

After that it will be new features, including split editor implementation. I will let you know as soon as this feature is in.
