### ISSUE TITLE
Link title should not be selected when pressing space

### ISSUE THREAD

**Issue by igorwojda** [vsch/idea-multimarkdown#690]
Pressing keys `c o d e SPACE`
As you see after pressing space first item from the popup is selected. This feels wired as I wanted to type `Code Forces`

![space](https://user-images.githubusercontent.com/530122/51794505-32c00200-21cc-11e9-926e-d34d2b71b891.gif)

**Comment by vsch** [comment]
@igorwojda, I am going to disable auto-popup completions for link text. This is used for most completions in markdown that have no well defined constraints. 

Typing will be as expected. To get completions you will need to hit ^Space.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by igorwojda** [comment]
This works much better and I am happy with it.

I just want to point out that hitting space and getting autocompletion still seems super intuitive. For me, it would more natural to treat space as another character that does not exist and display `no suggestion` in the popup
![image](https://user-images.githubusercontent.com/530122/51799946-fb7b4080-221f-11e9-881a-cef9bbfd8d5a.png)

or do what IDEA does - just hide the popup when none of the string in the popup match

**Comment by vsch** [comment]
@igorwojda, completions are controlled for the most part by the IDE. The plugin provides the choices and the IDE filters them by the characters before the caret.

The choices are supplied when the IDE first requests the choices. Subsequent typing causes the IDE to filter that list. The plugin can either provide choices or not. Pre-filtering the list based on current pre-caret content is problematic because it will affect all subsequent filtering by the IDE without the plugin providing an updated list.

For completions of link text there is no criteria for what makes sense to put for the choices and a guess from the link path with permutations of capital case and replacement of symbols for spaces is used.

In some cases there are more appropriate choices like the first heading in the file, heading referenced by an anchor ref, etc. However, there is no hard rule that would make sense in all cases.

Turning these choices off is the only other option.

Space causing un-intended insertion of completion when just a space was intended is not limited to markdown and this plugin. Kotlin completions give me Tourette's because I touch type fairly quickly and typing `null` followed by a space @#$@#@#$ inserts `nullsFirst()`. I have to either turn off space doing completions or slow down and hit escape after a space. 

BTW, removing the packages from completions using completion config does not work. I have not been able to figure out why.

**Comment by vsch** [comment]
@igorwojda, one option could be to disable completions for link text on space. I will play with this and see how it behaves or whether it works as expected.

**Comment by vsch** [comment]
@igorwojda, I created a plugin to disable auto-pop completions from inserting on a typed space. 

It drove me nuts in Kotlin which has a long auto-popup delay and suggests everything including the kitchen sink, so anything you type will always match something. Until it "learned" from my repeated choices it would routinely replace `var`, `val` and `null` by random crap and it drove me crazy. At the same time I like the way auto-popup and space work in Java. Now I get to tweak when auto-popup can complete on a space and when it cannot. Will work on Markdown auto-popups too. I think ;)

[Touch Typist's Completion Caddy](https://plugins.jetbrains.com/plugin/12043-touch-typist-s-completion-caddy)
