### ISSUE TITLE
Click on structure view does not update preview

### ISSUE THREAD

**Issue by holgerbrandl** [vsch/idea-multimarkdown#695]
When clicking on elements in the (simplified) structure view, the caret changes in the editor, but the preview pane is not adjusted to show the content at the caret. 

Both double (which changes focus to editor) and single (which just jumps but does not change focus)  click events in structure view suffer from this issue.

`Scroll preview to source position` is enabled and works in general when changing the caret position by clicking in the source editor.

**Comment by vsch** [comment]
@holgerbrandl, I am trying it and it does work. 

If anything it would be related to the IDE. The plugin does not handle structure view clicks. It provides a navigation element which resolves to location in the text. When you click the IDE moves the caret to that location.

The plugin listens to editor caret changes and scrolls/highlights the preview. It does this for all caret changes so if the IDE does not generate editor caret events (doubtful, it must be something else).

What elements are you clicking on? I could only get what you describe by clicking on non-rendering elements. In other words, there is nothing in the preview to scroll to.

For example: reference definitions.

**Comment by holgerbrandl** [comment]
Here's an example https://gist.github.com/holgerbrandl/4517fed2594e38945d0951958744ce6e

To reproduce
1. Open the document and move the caret to the very end
![image](https://user-images.githubusercontent.com/200952/52149912-9df75180-266e-11e9-9555-1c537d2b53ff.png)

2. Double click on `Foo` in the structure view. The editor scrolls and puts the caret at the right place, but the preview does not update
![image](https://user-images.githubusercontent.com/200952/52149992-db5bdf00-266e-11e9-8b7c-90744b6868f0.png)

Typically I use the simplified structure view, but it's the same there.  When doing so I just click on header elements in the structure view.

I've noticed that there is one exception: When (using the non-simplified struture and) clicking on _Unordered Lists_ and _Ordered Lists_ it updates caret **AND** preview! 

My version is
```
IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
JRE: 1.8.0_152-release-1343-b26 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

and MD Navigator is on v2.7.0.

**Comment by vsch** [comment]
@holgerbrandl, thank you. I can duplicate it. It happens if preview `Highlight preview element` is disabled.

![image](https://user-images.githubusercontent.com/10299086/52158867-b6656d00-266a-11e9-852d-16c6a8314c8b.png)

The IDE seems to perform two consecutive operations scroll/caret move and without highlighting I suspect one is resetting the other. Highlighting has a time delay so it changes the results. I will debug and fix.

**Comment by vsch** [comment]
@holgerbrandl, correction: happens if highlight mode is not set to `Line`. Only works in `Line` hightlight mode.

As a workaround, select `Line` mode and set timeout to 1 second. The selected element will flash and turn off.

If you want to go to more trouble then add the following to custom CSS text for the profile to make the highlight transparent:

```css
.focus-highlight {
    background-color: rgba(255, 0, 255, 0) !important;
}

img.focus-highlight {
    border: solid rgba(255, 0, 255, 0) 0 !important;
}
```

**Comment by vsch** [comment]
@holgerbrandl, the HTML did not have the right offset information without Line based highlights.

Fixed to now try to find the caret offset or any tag whose source range overlaps the line start-end range for the caret offset. Works like  a charm in all modes. 

Thank you for the reports. Your effort is very much appreciated.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
