### ISSUE TITLE
[2.8.0] Icon size

### ISSUE THREAD

**Issue by K4zuki** [vsch/idea-multimarkdown#701]
Congrats for new version but new icon seems "out of standard size"... Can you fix this?

![image](https://user-images.githubusercontent.com/9379328/52188552-cfdb0480-2876-11e9-9017-75f8b3c23932.png)

**Comment by vsch** [comment]
@K4zuki, definitely funny looking. About half the icons in this version were changed to SVG and I suspect that it is so because the SVG view box is 32x32. Go figure. I thought because this is a vector format it will downsize the icons.

I will try and make a new official release to correct for this. I do not have a non-hires monitor and if you are willing to try an EAP version with the fix to confirm I would very much appreciate it.

Thank you for reporting this. It never occurred to me that the SVG would not resize to any icon size.

**Comment by K4zuki** [comment]
@vsch Thanks for the fix. Yes I would like EAP.

**Comment by vsch** [comment]
@K4zuki, please let me know if this solves the issue with the icons.'

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by vsch** [comment]
@K4zuki, I can confirm that was the issue. I checked under parallels by configuring scaling for the display and 2.8.0 all icons were doubled. With 2.8.2 the sizes are back to normal.

You can ignore the EAP and just update to the official release.

**Comment by K4zuki** [comment]
@vsch Fix confirmed at 2.8.2! Thanks!

**Comment by vsch** [comment]
@K4zuki, thank you for reporting this.
