### ISSUE TITLE
URLs with a fragment identifier are treated as syntax errors

### ISSUE THREAD

**Issue by breandan** [vsch/idea-multimarkdown#706]
It seems like URLs with valid fragments are treated as a syntax error, "Anchor reference id is not resolved".

![image](https://user-images.githubusercontent.com/175716/52731734-79637980-2f8c-11e9-9710-2d4b3cd576dd.png)

It would be nice if it were possible to connect these to the actual source code somehow, for example when linking to a specific line in the source code, to provide navigation to that particular line (for example, if the Markdown link target was relative to the current project).

**Comment by vsch** [comment]
@breandan, I cannot see the full URL (I need the prefix) but guessing it is not GitHub. The plugin is trying to validate the anchor for the link and does not find it in the response for a remote link.

The plugin understands GitHub link anchors for line selection (`#Lxxx` for line and `#Lxxx-Lyyy`
for line range) and will validate it against the project file if the link is to a project file,
otherwise just pass it through for external links. It will also select the line range if
navigating to declaration from the anchor.

I also added a check for remote links to GitLab which uses a slightly modified pattern:
`#Lxxx-yyy` and a check when the wrong pattern is used ie. GitHub link with GitLab format and
vice versa.

**Q:** Where is the format `#Lxxx:Lyyy` used?

**Comment by breandan** [comment]
@vsch It's a GitHub permalink, this is the full URL: https://github.com/breandan/kotlingrad/blob/09f4aaf789238820fb5285706e0f1e22ade59b7c/src/main/kotlin/edu/umontreal/kotlingrad/functions/Function.kt#L24:L38

**Comment by vsch** [comment]
@breandan, didn't know they accept `Lxx:Lyy` as an alternative. Change it to `Lxx-Lyy` for now. 

I will add it to the pattern accepted by GitHub for the next EAP release.

**Comment by breandan** [comment]
It turns out GitHub is quite flexible, it looks like you don't even need a delimiter for line ranges [`#L24L38`](https://github.com/breandan/kotlingrad/blob/09f4aaf789238820fb5285706e0f1e22ade59b7c/src/main/kotlin/edu/umontreal/kotlingrad/functions/Function.kt#L24L38).

**Comment by vsch** [comment]
@breandan, I wish they would have  a spec for their links. It is all trial and error trying to match their processing.

At least now there is a spec (CommonMark) for their markdown.

**Comment by vsch** [comment]
@breandan, it is better than that. Seems it uses the following regex to extract a line range `^#(?:L(\\d+).*){1,2}$` so I have to do the same. Anything between `Lxxx` and `Lyyy` is accepted including a bunch of `L` and digits as long as the pattern does not match `L\\d+` it can be used as a spacer.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
