### ISSUE TITLE
does check all link when render ?

### ISSUE THREAD

**Issue by bluelovers** [vsch/idea-multimarkdown#707]
does plugin check all link when render ?
when i open a include many url link and local link md
it will very slow, and happen every time with switch tab or render new

if is yes, i think can make it only check link when hover / click a link, and also cache check stat, make it do not check again in ttl timeout

for example, open this file
https://gitlab.com/novel-group/txt-source/blob/master/wenku8_out/%E5%B9%B3%E5%87%A1%E8%81%B7%E6%A5%AD%E9%80%A0%E5%B0%B1%E4%B8%96%E7%95%8C%E6%9C%80%E5%BC%B7/%E5%B0%8E%E8%88%AA%E7%9B%AE%E9%8C%84.md#blob-content-holder

---
another issues

sometime open a url link, didn't open in browser, it replace in current preview

**Comment by vsch** [comment]
@bluelovers, thank you for reporting this one. To figure it out I downloaded your project and added git. Otherwise it was impossible to duplicate what was going on.

1. There are several old features responsible for the slow down which I will address in the next EAP release.

   Nothing can be done in the current version about slow rendering with many links. The only tolerable solution is to turn off the preview while editing.

   The rendering does try to resolve the link, mostly so it can color code invalid links. This was a feature early on when the plugin had no error annotations and was the only way to see if the links are invalid. Today this is quite a useless feature because the source shows the errors.

   I will add an option in HTML generation to generate resolved links and have it off by default.

   Links will be resolved when clicked on instead. This will save a ton of time in rendering especially when the file is full of nothing but links. 😄

2. The links will open project files by default, if you want them to open project files as if they were remote then you need to turn on:

   ![image](https://user-images.githubusercontent.com/10299086/53045681-3c9bf480-345c-11e9-8805-4b3d6b74c9c4.png)

   This will work if the logical file structure on your VCS git cloud is the same as on GitHub because that is what the plugin expects. GitLab is mostly the same for the repo so it should work.

**Comment by vsch** [comment]
@bluelovers, I just tested the fix and it was simpler than I thought. In fact all the code is already in the plugin to resolve links on click and all I had to do was disable the function to resolve links during rendering.

As a result the file renders instantly. With typing rendering delay set to 50ms, I can touch type with no lag and see the updated preview as I type. 

I was trying to figure out what was causing the delay for a very, very long time and optimized the rest of the code, but forgot about the effects of this redundant code.

**Can you please contact me by e-mail in my GitHub profile**, I want to send you a complimentary license or extend your current license if you already have one, as a small thank you gesture for helping me resolve this annoying rendering and typing delay.

**Comment by vsch** [comment]
@bluelovers, I responded to your e-mail and sent one to your GitHub profile but did not get a response. Are you able to receive e-mails on your GitHub listed e-mail?

**Comment by bluelovers** [comment]
i see it now, sorry about sourceforge email delay

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by bluelovers** [comment]
it work, no delay now

**Comment by vsch** [comment]
@bluelovers, I am still buzzing from having no typing delay.

I will find a way to address image links which still need the old logic to display in preview but not having links introduce delay into typing response is a joy for me. I touch type fairly fast and having even a small delay is extremely annoying.

**Comment by bluelovers** [comment]
can't close when click don't show again

![image](https://user-images.githubusercontent.com/167966/54083972-cd803480-4365-11e9-8279-14c631551b68.png)

**Comment by vsch** [comment]
@bluelovers, looks like a bug. I either forgot to set the property or probably setting the wrong property due to cut and paste.

**Comment by vsch** [comment]
I added a new issue for this #719

**Comment by vsch** [comment]
It was copy/paste but not as I thought. Unicode Line separators file inspection also cannot be shut off via the link. It sets the property to not show, but never checks it before displaying the notification.

**Comment by vsch** [comment]
@bluelovers, 
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by vsch** [comment]
@bluelovers, next release has serious speed gains. I used the project you sent me for testing performance and fix bugs in link resolution which did not handle all URL encoded links properly.

Here is an example of speed up from link caching typing in one of the files in the project with only 13 images with and without link caching:

![WithLinkCaching](https://user-images.githubusercontent.com/10299086/69975405-28aa1680-14f5-11ea-87c1-089dd66b4a59.gif)


The jumpiness without caching is the pause in UI response as the preview is updated and does image link resolution. This is already about 2x to 4x faster than previous releases. Caching speed ups are on top of these gains:

![NoLinkCaching](https://user-images.githubusercontent.com/10299086/69974868-18de0280-14f4-11ea-881e-c217276fae4e.gif)

Now typing in files with no images is the same as typing in files with images. All are much faster.
