### ISSUE TITLE
Separate "local" plugin configuration

### ISSUE THREAD

**Issue by adrianguenter** [vsch/idea-multimarkdown#71]
My IDE config (`~/.IntelliJIdea15/config`) is version controlled, so I'm looking for a way to persist the MultiMarkdown configuration without including license information and other local state.

To achieve this `wasShownLicensedAvailable`, `licenseCode`, `activationCode`, etc. should either be moved to `config/options/multimarkdown.local.xml` or (preferably, for me anyway) into `system`.

Thanks!

**Comment by vsch** [comment]
@adrianguenter, thanks for the request. I will be reworking the Preferences in the version scheduled for release 1 to 3 weeks from now. I will make this change at the same time.

**Comment by adrianguenter** [comment]
@vsch — Glad to hear it (no offense :laughing:). Awesome, thanks!

**Comment by vsch** [comment]
@adrianguenter, as a quick fix I can mark the storage type for all MultiMarkdown settings as RoamingType.DISABLED. I cannot change the directory because it is OS dependent but with roaming disabled the data should not be shared between users or installations. This is how all other IDE settings are handled.

I only have time to make all settings not shared for this release. I don't want to churn a lot of code just to get a half-assed implementation. I already rewrote the link resolving model and inspection logic for this release which took twice as long as I estimated but was well worth it. The links are now resolved and inspected as per GitHub rules and both relative and https:// absolute links within the repository are handled, with non-markdown files also available in completions with intention actions to change between relative to absolute formats.

I want to do the same rewrite for all settings to include per project settings for the plugin which is badly needed since a lot of the options vary by project. This will cause major code churn and I don't want to risk delaying the release by another week since I am already a week behind schedule.

In your setup, the app config directory is version controlled. Does that mean that no matter what the setting is in the IDE for roaming all or the configuration storage for the IDE is modified so that only shared settings are put under the per user directory in config and unshared go to system?

Please let me know if setting roaming type to disabled will be properly handled in your configuration and if moving all settings to non-shared will not cause other issues.

**Comment by vsch** [comment]
@adrianguenter, I put on my consultant hat and solved the problem with a bit of a hack but without affecting code outside the global settings class.

Now all non-roaming settings will be stored in **multimarkdown.local.xml** and are configured for roaming disabled persistence. So the IDE will handle it correctly. 

All shared settings are stored in **multimarkdown.shared.xml** and have default roaming persistence.

The old settings are removed by the IntelliJ automatically after they have been loaded by the plugin and saved to new storage.

Please let me know if you see a problem with the name change for the shared file.

**Comment by adrianguenter** [comment]
Thank you!
