### ISSUE TITLE
Memory leak in HTML preview window

### ISSUE THREAD

**Issue by radomirm-g** [vsch/idea-multimarkdown#710]
Android Studio's memory use reports show unusually high number of objects allocated by Markdown Navigator plugin. Analysis of memory dump indicates that MultiMarkdownEditorKit objects are not correctly disposed. For each MultiMarkdownEditorKit registers itself as a settings listener, but never disposes the MessageBusConnection object that represent this connection.

This connection keeps instances of MultiMarkdownEditorKit alive even if the MultiMarkdownEditorKitis no longer needed.

Repro steps:
1. Open .md file in MultiMarkdown editor. Make sure HTML preview pane is visible.
2. Modify a document and wait for HTML pane to refresh
3. Repeat previous step five times.
4. Capture heap dump for Android Studio process and inspect it in a profiler of choice.

Result:
5 MultiMarkdownEditorKit instances kept alive through MessageBusConnection

Depending on the .md document (large, with images) it is possible to get OOM dialog after extensive use. Some reports show as many as ~1000 strongly-referenced MultiMarkdownEditorKit objects. MultiMarkdownEditorKit objects can be very big - hey contain object references to other controls, char arrays, etc.

Excerpt from a report below shows 92% of all EventListenerList objects - 231K of them are referenced though 1377 MultiMarkdownEditorKit objects, that are kept alive though a disposer tree: 
CLASS: javax.swing.event.EventListenerList (249078 objects)
ROOT: Static field: com.intellij.openapi.util.Disposer.ourTree: 243173 objects (97%)
    243173  97%          1 com.intellij.openapi.util.objectTree.ObjectTree
    243173  97%          1 gnu.trove.THashMap
    243173  97%          1 java.lang.Object[]
    231172  92%       1377 com.vladsch.idea.multimarkdown.editor.MultiMarkdownEditorKit

**Comment by vsch** [comment]
@radomirm-g, thank you for the report. I will fix the code.

**Comment by vsch** [comment]
@radomirm-g, double and triple thank you. I spent hours and hours on many attempts over the last year with YourKit looking for the memory leak some people reported but I was never able to see anything or duplicate in my use.

I was convinced it was in the JavaFx Html preview browser and since I don't use Swing except for limited testing, obviously could not find the problem. 

Took 10 minutes to fix now that I knew what setup caused it and where to look. A deep and sincerest thank you for the report.

I would like to offer you a complimentary license for Markdown Navigator but your GitHub profile has no e-mail which I can use on the license. Can you please contact me on my GitHub profile e-mail so I can provide you with a license to enjoy a full featured Markdown Navigator plugin.

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
