### ISSUE TITLE
Autocomplete links as "repository relative" by default

### ISSUE THREAD

**Issue by demisolutions** [vsch/idea-multimarkdown#713]
Hello. 

Not sure if this relates to PHPStorm or multimarkdown editor but nonetheless, I thought you might now the answer:

Is it possible that autocompleted links are "repository relative" by default?

Right now they are relative to current file, and then I use an intent (which is brilliant), to change it to repository relative.

Thanks!

**Comment by vsch** [comment]
@demisolutions, I have been wanting to add an option for that for a while but since no one asked, did not bother just for me.

Right now you can invoke completion again to switch to the next format: page relative -> repo relative -> https:// -> file:// -> page relative.

![cycleavailablecompletions](https://user-images.githubusercontent.com/10299086/53683572-5b0db580-3cd0-11e9-8dc7-ff79346cf3ea.gif)


I will add an option in the next release to make default start the cycle at a point other than page relative.

**Comment by demisolutions** [comment]
@vsch thank you for fast response!

And great workaround! 👏

Looking forward for next release! 

Great job with the plugin, really takes markdown editing to a whole another level! ☺️

**Comment by vsch** [comment]
@demisolutions, thank you for your appreciation.

Next release will have plain text completions which will show references defined in the file and complete as corresponding referencing element. ie. references complete as ref links, footnotes as footnote refs, etc.

Double invocation of plain text completion will add links and references used in other markdown documents as completion choices for ref links which automatically insert their reference definition on completion.

I do a lot of support correspondence and "how to" markdown snippets using the plugin. Having to search for links which I know I used somewhere or having to create the link then convert to reference got to be too much of a PITA.

Now I use Drag/Drop of external links from the browser into a file to automatically create the references which I will need in the response, then start writing and use plain text completion to insert ref links which I dropped into the file or used in other files.

Makes the response process much smoother and quicker.

**Comment by vsch** [comment]
@demisolutions, new option added to set the starting format for link completions:

* Add: Languages & Frameworks > Markdown > Editor option `Default link completion format`, sets the starting format for link completions. Use multiple invocation to cycle to other formats.

![image](https://user-images.githubusercontent.com/10299086/54874833-60d75200-4dc9-11e9-9847-729fdf9745e3.png)

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
