### ISSUE TITLE
Completed task list items not rendered with checkmark

### ISSUE THREAD

**Issue by tmalaher** [vsch/idea-multimarkdown#715]
Using Markdown navigator v2.8.2 in GoLand 2018.3.5.

These look identical in the rendered output:

```markdown
* [ ] To do item
* [x] Done item
```

Shouldn't that last one have a checkmark in the box?

**Comment by vsch** [comment]
@tmalaher, they do in the JavaFX browser. Originally, there were issues trying to do the same in Swing. However, that was back 3 years ago and my understanding of how all pieces interacted was limited.

I will put add this to my Swing browser improvements and see if I can make it work properly in swing and JavaFX.

**Comment by vsch** [comment]
@tmalaher, I can do a bit better by using an image instead of a bullet but the Swing browser is very limited in what you can do with an image. I would probably have to use a table for task list items to get better results and I don't really want to go in that direction because I suspect it will be a nightmare to maintain and make it work with all elements.

Here is how it is now:

<img width="523" alt="Screen Shot 2019-03-08 at 7 42 00 PM" src="https://user-images.githubusercontent.com/10299086/54063537-f1fbd580-41da-11e9-993c-ab3de614ef36.png">


Just using an image I cannot vertically align it with the text:

<img width="527" alt="Screen Shot 2019-03-08 at 7 45 25 PM" src="https://user-images.githubusercontent.com/10299086/54063528-e7d9d700-41da-11e9-9d8c-86b8879d56cc.png">

<img width="518" alt="Screen Shot 2019-03-08 at 7 45 59 PM" src="https://user-images.githubusercontent.com/10299086/54063531-ea3c3100-41da-11e9-844a-37f54f874897.png">


If I added an option in Languages & Frameworks > Markdown > Debug:

![image](https://user-images.githubusercontent.com/10299086/54063582-4dc65e80-41db-11e9-9951-486c4509407b.png)

**Comment by vsch** [comment]
EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
