### ISSUE TITLE
Indentation in a numbered list 'flickers' when typing and deleting text

### ISSUE THREAD

**Issue by UlrichCech** [vsch/idea-multimarkdown#720]
This occurs since the new version of Markdown Navigator.

If I have a numbered list, and the text breaks into next line, the indentation is one space to much; when I type further and then hit the "Backspace", the indentation is "fixed", but if I type again, the space is added again... so between "typing" and "hitting backspace", the indentation flickers back and forth.

**Comment by vsch** [comment]
@UlrichCech, can you please give me the plugin version number you are using. This part of the code had a lot of changes due to #684 enabling wrapping on every typed character instead of only space as in previous versions. BTW, you can disable this in Languages & Frameworks > Markdown > Editor settings.

Getting this to handle all cases is actually very hard and takes a while to "discover" and fix.

I am fixing every case that comes to my attention in the EAP releases and will make one sometime today or tomorrow for the next batch of issues.

Can you give a screen shot of the text when "the indentation is one space too much" or better if you can do a screen grab GIF animation (I use [LICEcap] on OS X for quick animation captures) of what you described. Sometimes the important details are hard to convey in words and I may see something in the animation to help me understand what is going on.

[LICEcap]: https://www.cockos.com/licecap/

**Comment by UlrichCech** [comment]
The version number is 2.8.2 from the Official Plugin Releases.

Changes to "Tab/Backspace: List item indentation"
and/or
"Wrap only after space is typed"
does not have any effect on the 'flickering', which persists.

I made a small Quicktime-Movie (780KB), which shows the effect. You can find it here:
https://www.dropbox.com/s/hc7lcmf4hb00vyq/MarkdownNavigator_Indentation-issue.mov?dl=0

**Comment by vsch** [comment]
@UlrichCech, that is new. Can you try the EAP update channel. It has a lot of bugs fixed since last release, including a bunch in wrap on typing.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by UlrichCech** [comment]
Unfortunately, EAP-Version does not fix that

**Comment by vsch** [comment]
@UlrichCech, definitely weird behaviour. From the animation I cannot see the full list item.

Can you remove any proprietary information from the list item which exhibits this behaviour and post the markdown here so I can try and duplicate it. I can see it happening but cannot think of the conditions that could cause the indentation to jump.

**Comment by UlrichCech** [comment]
This is easy to recreate:

1. first item
2. second item
3. This is long text trying to show the weird problems with indentation asdhl dashjlg dsblhj This is long text trying to
   show the weird problems with indentation asdhl dashjlg dsblhj shjal DBHSJla adghal halsgd alsdbljabJASBDJLABASVD
   AGSGDLA ALSHGD ALH XXX dljasa vhljasdgh

Then put your cursor directly after 'XXX' and hit space and backspace... then the one space is added and removed as you hit the keys.

**Comment by vsch** [comment]
@UlrichCech, I wish it was that easy. I am not getting this. 

![WeirdWrappingJump](https://user-images.githubusercontent.com/10299086/54130373-a453b880-43e6-11e9-9184-d8d0a6bd16c6.gif)

What are your settings for Code Style > Markdown > Lists

And your parser settings in Languages & Frameworks > Markdown > Parser

Both affect how lists are generated/formatted.  Also what do you get if you format the whole document? The typing indentation or the backspace indentation for the list?

It could be related to "Use character font width" which is dynamically collected before formatting or wrap on typing and could be messed up by timing, but I have not seen that.

![image](https://user-images.githubusercontent.com/10299086/54130638-204e0080-43e7-11e9-8c06-5b881650ebc2.png)

If you disable it, do you still get the same behaviour?

**Comment by UlrichCech** [comment]
Disabling the "Use character font witdh" does not change anything, but I figured something out:
The behavior occurs only, if you have a line-break (via 2 or more spaces at the end of the line) and only, if the numbers are lower than 10 (so only single character numbers):

1. first item
2. second item
This is long text trying to show the weird problems with indentation asdhl dashjlg dsblhj This is long text trying toYYYY
show the weird problems with indentation asdhl dashjlg dsblhj shjal DBHSJla adghal halsgd alsdbljabJASBDJLABASVD
AGSGDLA ALSHGD ALH XXX dljasa vhljasdgh

the YYYY must be replaces by "spaces" to have a manual line break

**Comment by vsch** [comment]
@UlrichCech, I saw the hard-break spaces in your animation and was the first thing I tried. It is possible you have some Unicode zero width characters in your text. You can use [Zero Width Characters locator] plugin which is easiest, or use the show hex for selection in the plugin's toolbar. 
![Screenshot_ShowHexForSelection](https://user-images.githubusercontent.com/10299086/54131768-660bc880-43e9-11e9-8650-92d0bbd78774.png)

I added this originally to allow me to see what text is really in the file. It is a bit weird and unpolished but gets the job done:

![Screenshot_ShowHexForSelection_1](https://user-images.githubusercontent.com/10299086/54131834-8b003b80-43e9-11e9-9d3a-9efd11c75d1f.png)

I would look for any unicode characters in your text where you did not insert any intentionally.

[LICEcap]: https://www.cockos.com/licecap/
[Zero Width Characters locator]: https://plugins.jetbrains.com/plugin/7448-zero-width-characters-locator

**Comment by UlrichCech** [comment]
In addition, I have these settings:

[Image](https://www.dropbox.com/s/evkg2p1jq70xd86/Bildschirmfoto%202019-03-11%20um%2015.35.10.png?dl=0)

**Comment by vsch** [comment]
@UlrichCech, thanks I will try them. I did suspect the lists setting and tried the Fixed 4 spaces but I will try all conditions at the same time. I can see it happening on your system and need to figure out how to make it happen on mine.

**Comment by UlrichCech** [comment]
I think, you are right, the setting with the 4 fixed spaces makes a lot of trouble, when using the default settings for CommonMark and only change to "4 fixed spaces"... then many numbers are not correct auto-indended and numbered...
For example:
1. asdasdas
2. asdsada
    1. sdshö
    2. huisahdsa

are auto-changed to:
1. asdasdas
2. asdsada
3. sdshö
4. huisahdsa

**Comment by vsch** [comment]
@UlrichCech, Eureka!! I am getting the same behaviour now. I don't know how I missed your comment about BACKSPACE un-indenting. It seems to ignore the fixed 4 setting for lists. I will fix it.

As for CommonMark list indentation "rules" they are a bit weird and cause problems for longer lists when suddenly you need to indent items numbered 10+ by 4 spaces instead of 3 for single digit list items. Don't hit 100+ because then you will need to use 5 spaces for indents on those items.

I will see if there is something I can do in format document to mitigate this. For example allow 3 space list indentation for all items and format them to the correct level.

**Comment by UlrichCech** [comment]
Very cool, then I'am waiting for the next EAP release and try that out immediatly. Thanks for your support!

**Comment by vsch** [comment]
@UlrichCech, I was very reluctant to touch the wrapping code knowing it is a pandora's box. I do like the wrapping on each character though, so it is worth the pain.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by UlrichCech** [comment]
Ok, seems to work now as expected. Thanks!!!
