### ISSUE TITLE
EAP: QuickFix for "Wrap Links" shows the message-key instead of description

### ISSUE THREAD

**Issue by UlrichCech** [vsch/idea-multimarkdown#721]
The quickfix for the "wrap links" feature displays the message-key and not the description text.
This text is shown "!wrap.auto.link.in.angles.intention.name!" ;-)

Found in current EAP-release 2.8.2.32

**Comment by vsch** [comment]
@UlrichCech, thanks for catching it.

**Comment by vsch** [comment]
@UlrichCech, you should upgrade to the new EAP. Lots of fixes and improvements. Including, copying Markdown in one IDE instance and pasting in another now adjusts links and adds missing references.

EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)
