### ISSUE TITLE
Self referencing links do not generate appropriate markup.

### ISSUE THREAD

**Issue by rquadling** [vsch/idea-multimarkdown#73]
Hi.

Hopefully I'm not misunderstanding what is supported.

With the following markdown,

```
# Section

Link to [section](#section)
```

The HTML generated looks like ...

```
<h1><a href="#section" name="section"></a>Section</h1>
<p>Link to <a href="#">section</a></p>
```

Which I think is incorrect.

I think it should be ...

```
<h1><a href="#section" name="section"></a>Section</h1>
<p>Link to <a href="#section">section</a></p>
```

Currently, I have to use ...

```
#Section

Link to <a href="#section">section</a>
```

**Comment by vsch** [comment]
@rquadling, thank you for reporting this bug. It affects the HTML Text tab when 'Show Modified' option in preferences is turned off. Am I right in guessing you are using the HTML Text tab contents to copy the HTML into another file? Otherwise, you should not have to use the raw HTML linking since GitHub will render the correct HTML when you commit the file.

If you are using the content of HTML please let me know how you use it. I did not think of that the plugin would be used this way until another user reported one use case in #51. I am interested in better understanding your use case. Maybe there is a feature that can be added to the plugin to make it more convenient.

I will upload a fix shortly and post a link in this issue.

**Comment by vsch** [comment]
@rquadling you can download the fixed build from <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.2.2.1.zip>

**Comment by rquadling** [comment]
Yep! Now just need to see if BitBucket will support that.

...

Yay. Nearly.

They prefix their IDs with 'markdown-header-'.

So I can now get it working in BitBucket ...

```
1. __[DB](#markdown-header-1-db-top)__           - Copy company specific data from production to your local database.
2. __[TidyPMP](#markdown-header-2-tidypmp-top)__ - Process the __PHPMaker__ `digitickets.pmp` file.
```

and ...

```
# 1. DB [(top)](#markdown-header-packages)
...
# 2. TidyPMP [(top)](#markdown-header-packages)
```

but that doesn't work in multimarkdown. Which is sort of OK I suppose.

Is there anything you can think of that would work in both places?

If not, that's OK. Not sure exactly what engine and trying to support 1 engine at a time, per difference ... could be a massive pain ... but if MultiMarkdown had per-engine configuration, with the engine being remembered for the project (or whatever ways is suitable for IDEA), then that could work.

But, again, if not, consider this closed as you fixed the initial issue.

Thanks.

Richard.

**Comment by vsch** [comment]
@rquadling, if I understand correctly, you use the plugin to validate your links for the particular repo, so for GitHub it works but for bit bucket it doesn't because the anchor links use different id generation logic.

Are you using the generated HTML from the HTML Text tab at all or is it just for link validation? 

BitBucket support was requested #30 but only for the stylesheet and I do have it on the todo list. I plan on addressing this once the GitHub version is fully implemented because I will need to spend quite a bit of time with BitBucket to learn all their idiosyncrasies. Markdown is not really a "standard" beyond the basics and each engine has its differences and especially what can be considered bugs in implementation. These too need to be handled and it takes a while to even discover what to look for. Once GitHub is done, I will have at least a base understanding of what to look for. 

Without a configuration option for anchor id generation per project there is no way to address differences in engines. A better solution is to detect the engine from the remote URL of the VCS root. This is the way I will implement it so the configuration will be automatic.

Right now the plugin does not even handle GitHub precisely, yet. I have that on the list too, pegdown parser needs to be modified to make it work. If you use non-alphanumeric characters in the titles and if you have two titles with identical ids then the anchors will not match GitHub. This is a todo item that I will address in the very near future. If not the next release then definitely the one after that. The next release I am planning to split out the preferences into System - local only, Global - shared and per Project settings. At that point per project configuration can be added.

I can add a kludge to settings that will at least allow you to change the algorithm for anchor links. It will be global until project settings are implemented and BitBucket repo URLs are recognized but at least with a single change you can validate the links for a specific markdown engine but I still have no idea of the differences I need to address. If you know how BitBucket generates anchor link id's, especially if you use "%&$#()*@" and other non-alpha characters please let me know. It will definitely speed up my ability to deliver a usable solution.

**Comment by rquadling** [comment]
At the moment, I think the issue lies solely with BitBucket. I've got the links working fine there.
