### ISSUE TITLE
apache pdfbox vulnerability

### ISSUE THREAD

**Issue by gregallen** [vsch/idea-multimarkdown#731]
please upgrade your dependency owing to CVE-2018-11797

thx

**Comment by vsch** [comment]
@gregallen, thank you for the information. 

I will update the dependencies which are from OpenHtmlToPDF through flexmark-java. 

This should not affect any code in these libraries because PDF files are not parsed but generated from HTML. So there is no chance to carefully craft the PDF to exploit the bug.
