### ISSUE TITLE
[Request] Soft-wrapping for paragraphs

### ISSUE THREAD

**Issue by pbowyer** [vsch/idea-multimarkdown#75]
I discovered the plugin through a link to your Black Friday sale - it looks awesome!

One feature I would like to see is soft wrapping for paragraphs and similar text? At present I can have my paragraphs extend out of the window or turn on editor wrapping and have my tables messed up; is it possible to implement wrapping in the plugin?

**Comment by vsch** [comment]
@pbowyer, what I am planning to implement is not soft wrapping because that requires serious modifications to the text editor, from just a cursory glance. However, I am planning on implementing hard wrap for paragraphs as you type and during reformat where the breaks will not affect rendered HTML. 

Since markdown ignores line breaks unless a line ends with two or more spaces, this seems like the best solution to have reasonable width text and any width formatted tables.

This is part of the request #61 except I will have to modify how it works or just implement it myself, to handle markdown specifics.

I also want to implement removal of non-significant trailing white-space on save. Right now in the IDE it is either remove all, which messes up hard line breaks with two spaces trailing, or have a lot of spurious white spaces. There are options to only affect modified lines but this does not handle the issue for markdown.

I want white space cleaned up: two spaces where they are significant and none where they are not. 

These are on the to do list for the next two releases. I am running a bit behind schedule for the next release, but if these don't make it into the next release they will be in the the one two weeks later.

**Comment by pbowyer** [comment]
Thank you very much for your detailed response -- looking forward to seeing the results!

**Comment by vsch** [comment]
Sorry, had to bump it to the next one because I ran out of time for this release.

**Comment by vsch** [comment]
@pbowyer, version 1.4.5 has been released. It has wrap on typing and table formatting on typing.

**Comment by pbowyer** [comment]
Awesome, thank you!
