### ISSUE TITLE
Attributes support is broken/incompatible with fenced code blocks

### ISSUE THREAD

**Issue by skalpa-rld** [vsch/idea-multimarkdown#760]
Attributes added to fenced code blocks are not applied to HTML. 

Additionally they just break PlantUML support in the preview (which is actually my use-case. I need to be able to add attributes to `plantuml` code-blocks as I convert my Markdown using [pandoc](https://pandoc.org/MANUAL.html#extension-fenced_code_attributes). 

### Examples

The attribute is ignored:
\```lang {style="border: 2px solid #000"}
echo 42;
\```

This breaks PlantUML preview:
\```plantuml {caption="Some text"}
Some puml code
\```

Ideally, attributes should be supported on code blocks. If that's not possible if would be great if, at least, there were just ignored by the PlantUML support code so they don't break the preview anymore.

**Comment by vsch** [comment]
@skalpa-rld, 

1. The attribute should be added after the code-fence because if it is added on the first line it is treated as part of the info string of the code fence.

2. The attributes are not passed to PlantUML in rendering because the code fence is converted to an image and the attribute is applied to the wrapping `p` tag:

````markdown
```plantuml
Some puml code
```
{caption="Some text"}
````

Gives:

````
<p caption="Some text"><img src="https://g.gravizo.com/svg?Some%20puml%20code%0A" alt="" /></p>
````

For non-image type code fences it works as expected:

````markdown
```text
Some puml code
```
{caption="Some text"}
````

Gives:

````
<pre caption="Some text"><code class="text" caption="Some text">Some puml code
</code></pre>
````

What is the resulting HTML in the renderer that you would expect? I can see if I can add code to special code fence rendering to address this.

**Comment by skalpa-rld** [comment]
@vsch Thank you for your answer.

1. This is not how the other projects I saw handle attributes on code blocks. Now, I understand that attributes are a Markdown extension and that we can't expect consistency between all projects. This is a minor issue, but you might still want to do something about it as someone else might have the same problem in the future. For reference:
* [Fenced code blocks](https://python-markdown.github.io/extensions/fenced_code_blocks/) in python-markdown
* [Fenced code blocks](https://michelf.ca/projects/php-markdown/extra/#fenced-code-blocks) in PHP Markdown extra
* [Fenced code attributes](https://pandoc.org/MANUAL.html#extension-fenced_code_attributes) in pandoc

2. I understand that attributes will not be passed to PlanUML, the problem is that anything after the `plantuml` language identifier seems to confuse the parser. 

I would expect these two examples to produce the exact same code:
````
```plantuml
Some code
```

```plantuml this_should_be_ignored
Some code
```
````

However, while the first one correctly generates an image and gives the expected:
```
<p><img src="https://g.gravizo.com/svg?Some%20code%0A" alt="" /></p>
```

The second one doesn't even trigger Plantuml support and gives:
```
<pre><code class="plantuml">Some code</code></pre>
```

For info, this is inconsistent with how code blocks work if the language identifier is something else than `plantuml`. If you replace `plantuml` with `java` in the examples I just gave, you will get the same output in both cases (eg: everything after the language identifier on the first line is ignored):

```
<pre><code class="java">Some code</code></pre>
```

**Comment by vsch** [comment]
@skalpa-rld, the issue for plantUML rendering of fenced code blocks is a bug in the plugin recognition of plant uml and other special code fenced blocks. The rendering uses the first word of the info string to generate the HTML class attribute but the code uses the whole string. I will fix this.

The attribute coming after the fenced code is an issue for CommonMark which does not have a limitation on the info string. So anything can be used for the info string. I will see if I can add handling of attributes after the info string (as being the tail end of the info string) so that attributes can be added after it.

I will fix it shortly and make an EAP release with the fix.

**Comment by vsch** [comment]
@skalpa-rld, both issues fixed. Now attributes at the end of the info string will be parsed.

:information_source: For fenced code elements, only attributes elements at the end of the info
string line will be parsed.

For example:

````
```info {#not-id} not {title="Title" caption="Cap"} {caption="Caption"}

```
````

The `{#not-id}` is not parsed as attributes because it is followed non-attributes element and
will result in the following HTML:

```html
<pre title="Title" caption="Caption"><code class="language-info">
</code></pre>
```


EAP update with a fix for the issue is available.

[Installing EAP Plugin Version](https://github.com/vsch/idea-multimarkdown/wiki/EAP-Update-Channel)

**Comment by skalpa-rld** [comment]
@vsch I can confirm that the fixes in the latest EAP work as expected, so I'm closing this issue.

Thanks a lot.
