### ISSUE TITLE
Linking to indexes

### ISSUE THREAD

**Issue by silkentrance** [vsch/idea-multimarkdown#783]
Linking to folders will resolve in that the solution will select the linked-to folder in the project tree.

However, we would not like the solution to just select the folder, but instead would like it to navigate to the index document underneath that folder. And if no such document exists, it should either put out some warning or simply  just select the folder in the project tree.

E.g. `[SomeLink](./foobar)`

where foobar is a folder, should resolve to

E.g. `[SomeLink](./foobar/(INDEX|index|README).md)`

The same works well on github and the likes.

## Related Issues

- #681

**Comment by vsch** [comment]
@silkentrance, and what if your link is really to a folder, which happens when you want to select a  directory display page?

There are a ton of complexities in figuring out what the link is pointing to and it depends on type of link (image, link or wiki link), the URL used and the link target location. 

Links to wiki with extension refer to the raw markdown content, not rendered. So this too has to be taken into account because it is rarely desired and is instead and error made by the user who is not aware of that. 

Rendered Markdown: <https://github.com/vsch/idea-multimarkdown/wiki/Home>
Raw Markdown: <https://github.com/vsch/idea-multimarkdown/wiki/Home.md>

When I started I too had a simplistic view of what the plugin needed to do. It slowly dawned on me as I rewrote the link resolution engine 4 times that there is non-obvious complexity to the job.

It it still not ideal but works 99% of the time. Maybe I will be able to hit 100% on the next rewrite.

**Comment by silkentrance** [comment]
Having a LinkResolver, e.g. a LocalLinkResolver or an UrlLinkResolver, which would then return you either a Directory or an Index sort of object would do the trick.

Both would be implementing the Navigatable interface, where you would just call the NavigateTo method.

Where the LocalLinkResolver would further elaborate on the available types of documents, e.g. search for an index.md or a README.md and then navigator to that or just to the folder in case of both are missing.

**Comment by vsch** [comment]
@silkentrance, if you want a specific file then put it into the link URL, links to folders result in folder targets.

Here is a link to a folder:

https://github.com/vsch/idea-multimarkdown/tree/master/resources

**Comment by silkentrance** [comment]
This would still be an external resource. What I would like, would be to link to link to a local resource, which would also kinda work with github, e.g. `./local/somedir`, where in somedir there would be an index.md or a README.md or similar kind of stuff that will allow me to traverse the hierarchy of my documentation without having to explicitly link to `./local/somedir/index.md`.

**Comment by silkentrance** [comment]
@vsch 
And this specifically about the local visualization of the fact and the ability to navigate in the IDE.
Why did you close this?

**Comment by vsch** [comment]
@silkentrance, because if you want a link that resolves to a file then add the file to the link URL.

Effectively, I am closing it because your request has no use case justification that cannot be currently addressed.

**Comment by silkentrance** [comment]
@vsch I basically want to link to `./localdir` without having to instruct the plugin to also navigate to `./localdir/index.md`.

This would be a shortcut, which is also a basic mechanic in standard http(s) when fetching the content of remote directories.
