### ISSUE TITLE
Copy/paste from markdown file into Windows Remote Desktop connection suddenly not working

### ISSUE THREAD

**Issue by AEHamrick** [vsch/idea-multimarkdown#809]
With a recent update it seems like copy/paste (clarification: from the editor window)  'through' RDP to a remote windows server doesn't work anymore; up til recently it's been fine.  

Plugin version 2.9.11  (Settings are default as far as I know)
PyCharm version 2019.3 and 2019.3.1 
Windows 10 client, windows server something or other remote connection.

Works:
c/p from non-markdown (e.g., .py) file to remote
c/p from markdown file with plugin disabled to remote
c/p from other apps to remote

Doesn't work:
c/p from markdown file with plugin enabled to remote

Tried:
Restarting PyCharm
Updating PyCharm
Restarting RDP clipboard manager local and remote

If there are settings I could try or other info I can collect to verify an issue please let me know :)

**Comment by vsch** [comment]
@AEHamrick, are there any exceptions when you try to paste to the remote?

I cannot think of what could be responsible since copy is implemented by the plugin but paste to non-markdown file is not done by the plugin. However, there was a lot of code churn related to 2019.3 compatibility in the plugin and changes in the IDE API/ Something could have been changed on either side to break the functionality.

If you check the IDE log file can you see any markdown navigator exceptions?

<img width="449" alt="image" src="https://user-images.githubusercontent.com/10299086/72826202-63ebda80-3c46-11ea-833d-b32fbec9d4f7.png">

I will try to duplicate this so see if I can figure out what is causing it.

**Comment by AEHamrick** [comment]
Thanks @vsch -- the log I have is from Dec 17 to now, it did not show any markdown navigator exceptions, or mentions of markdown navigator at all except back in December warning it was incompatible with my current build---presumably that was when I updated the plugin. I will keep an eye on it though and see if my normal usage makes anything show up.

PyCharm is also telling me that 2019.3.2 is released, I can update if you want to see if that resolves it, or wait if that would cause extra confusion.

**Comment by vsch** [comment]
@AEHamrick, go ahead and update to newest version. I will try to duplicate this issue on my end.

**Comment by AEHamrick** [comment]
Sorry for the delay--updating did not seem to impact anything.

Would it be helpful if I could export settings/config for the plugin/Pycharm at large?

**Comment by AEHamrick** [comment]
This might be some help--I just realized that copying from the preview does still work.

**Comment by AEHamrick** [comment]
@vsch Having just updated the plugin to 3.0.197.62 it seems like it's working now.

**Comment by vsch** [comment]
@AEHamrick, thank you for the update. I think it was inadvertently addressed by some other code change, since on my end, using my dev version of the plugin, I was not able to duplicate the issue.

The IDE operations can get (very) complex and some code changes cause strange interaction between seemingly unrelated features.

**Comment by AEHamrick** [comment]
I don't doubt it! In any case thanks for looking into it, and I think we can close this. Thanks for all your work on the plugin, it's a lifesaver.
