### ISSUE TITLE
Intellij IDEA 15 support?

### ISSUE THREAD

**Issue by dkowis** [vsch/idea-multimarkdown#83]
I'm sure it's on the road map, but I didn't find an issue specific for it, and I'm missing my multimarkdown support :)

**Comment by vsch** [comment]
@dkowis, what exactly is happening in Idea 15 on your system?

I am always running the smoking latest EAP and release versions. If the plugin does not work on the latest version I have no choice but to fix it immediately or I cannot work at all.

Sometimes the smoke is coming out of my ears because of new bugs or changes that break some plugin function. That stops my work in its tracks but that is the price for the bleeding edge.

What is your OS and JRE and have you upgraded to the latest plugin version?

**Comment by dkowis** [comment]
I asked because it doesn't show up in the list of plugins, but I realize now that's probably my fault, it's not in the jetbrains repository? I probably have to install it by hand. Lemme do that and make sure I'm not derpy. I'll close this issue if it works (It probably will.)

**Comment by vsch** [comment]
<img width="709" alt="screen shot 2015-12-15 at 3 32 27 pm" src="https://cloud.githubusercontent.com/assets/10299086/11823274/2ed8f104-a341-11e5-9740-3f1e825ff24c.png">


It is there, the latest release is 1.2.3 dated Dec 4, 2015.

**Comment by dkowis** [comment]
Yep, entirely my fault being stupid. I didn't see it in the "install from Jetbrains Repository" and I didn't think to download it by hand and install it. Everything works great! Thanks!

**Comment by vsch** [comment]
@dkowis, not a problem and thanks for nearly giving me a heartattack. I am hip deep in rewriting all the Preferences and Editor classes and have not checked the website in a while. Thought that I might have missed the plugin going missing. ;)
