### ISSUE TITLE
How to modify the text style?

### ISSUE THREAD

**Issue by hejiafeng** [vsch/idea-multimarkdown#859]
![9_UNX~I6X{SDA8)QDW48V`9](https://user-images.githubusercontent.com/23006914/83970925-f695c900-a90a-11ea-980b-ef4c4b825471.png)
As shown in the figure.
When previewing, the background is black and the font is also black.How to Change the text color to white?
Look forward to your reply,Thx

**Comment by vsch** [comment]
@hejiafeng, I cannot see which element you are referring to from the figure because your preview appears to have a grey background but the text editor has a dark background.

However, if you are referring to the text are then you can change the element syntax highlighting in settings (preferences or OS X) Editor | Color Scheme | Markdown:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/10299086/84067290-3903e800-a995-11ea-85f5-3c5b402ffe0b.png">

On the other hand if you are referring to the HTML preview, then it is more difficult since the colours in HTML have to be modified via CSS. It can be done but will require adding CSS styles for specific elements. See https://github.com/vsch/idea-multimarkdown/wiki/Customizing-HTML-Preview.

**Comment by hejiafeng** [comment]
> @hejiafeng, I cannot see which element you are referring to from the figure because your preview appears to have a grey background but the text editor has a dark background.
> 
> However, if you are referring to the text are then you can change the element syntax highlighting in settings (preferences or OS X) Editor | Color Scheme | Markdown:
> 
> <img alt="image" width="982" src="https://user-images.githubusercontent.com/10299086/84067290-3903e800-a995-11ea-85f5-3c5b402ffe0b.png">
> 
> On the other hand if you are referring to the HTML preview, then it is more difficult since the colours in HTML have to be modified via CSS. It can be done but will require adding CSS styles for specific elements. See https://github.com/vsch/idea-multimarkdown/wiki/Customizing-HTML-Preview.

Thank you
