### ISSUE TITLE
Absolute link references are broken on 1.3.0

### ISSUE THREAD

**Issue by breandan** [vsch/idea-multimarkdown#88]
![image](https://cloud.githubusercontent.com/assets/175716/11932193/6f7ec5b0-a7c1-11e5-8a8a-afda221b147c.png)

**Comment by vsch** [comment]
@breandan, you are right. 

It was caused by my misunderstanding of how github resolves absolute addresses relative to the repo (/...). I tested it for directories and fixed it, but then links to files starting with / would resolve in the plugin but not on GitHub. I finally clicked that only files in subdirectories from / should resolve but not references to bare files /filename.ext. 

It's been a long three weeks. I'll make a quick fix and give you an updated build.

**Comment by breandan** [comment]
Thanks! Great work though, really impressed by your progress.

**Comment by vsch** [comment]
Thanks. I learn quickest if I have good examples and I found a treasure trove of these in the intellij-plugins project. When I "stumbled on it" I thought I died and went to heaven. All my questions were there in working code samples and manageable in size, unlike the open-api source.

**Comment by vsch** [comment]
@breandan, fixed version available here: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.0.2.zip>

This also fixes a bug where sub-modules would not be recognized causing a files in the submodule to be treated as part of the main repository, just in a subdirectory, instead of completely separate repository.

The confusion I had has cleared up.
