### ISSUE TITLE
CSS files created in home directory

### ISSUE THREAD

**Issue by jotomo** [vsch/idea-multimarkdown#92]
On Arch Linux, when starting Idea 15.02 with MM 1.3.0, the following files appear in my home folder:
```
nullmultimarkdown_darcula.css
nullmultimarkdown_default.css
nullmultimarkdown_layout.css
```

I'm using the darcula theme. Let me know what further information to provide to help.

**Comment by vsch** [comment]
@jotomo, thank you for bringing this to my attention. it is in part of the code that I had concern for but it has been in the plugin for months and no one had an issue so I assumed it worked in all cases where IntelliJ IDE worked. Bad assumption.

The plugin is trying to create a file in the temp directory but without going through Java temporary file API so that the files do not have the random prefix. My bad. I'll make a quick fix that will fall back to using the API if getting access to the temp directory fails.

I'll post a link to an updated zip file as soon as it is ready.

**Comment by vsch** [comment]
@jotomo, I came back to post the link and saw that I never pressed comment in my original response. It has been a long 3 weeks. ;)

Here is the fixed version: <https://github.com/vsch/idea-multimarkdown/raw/master/dist/idea-multimarkdown.1.3.0.1.zip> please download and install plugin from disk.

I tested it by artificially setting the variable to null to simulate the condition. That said, I will wait for your response before considering the issue solved.

**Comment by jotomo** [comment]
Thanks @vsch 1.3.0.1 fixes the issue. 
P.S. Note that the issue only appeared after installing 1.3.0, I've been using the plugin for weeks now and only after the update today those files showed up in my home folder. I've tested it on both my desktop machine and my notebook and I'm pretty sure the only thing that changed was the plugin upgrade to 1.3.0. So it should be connected to something in the 1.3.0 release - in case that might be relevant.

**Comment by vsch** [comment]
@jotomo, Kotlin returns null where Java throws an exception. When I converted this part to Kotlin, the exception went away and Kotlin did not highlight that the variable can be null. I am so used to the IDE taking care of this that I don't even think about it anymore. I should since Kotlin is still pre-release. My bad.

I am glad it solved the issue.
